const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');const {encode}=require('../UI/wav-export'),{validateWave,registerAudioExport}=require('../audio-export');
const range={inSeconds:.25,outSeconds:.75,duration:1};
async function wave(){const channels=[Float32Array.from({length:48000},(_,i)=>i<12000?0:.5),Float32Array.from({length:48000},()=>-.5)];return encode({sampleRate:48000,numberOfChannels:2,length:48000,getChannelData:c=>channels[c]},range,async()=>{});}
test('WAV export has sample-exact range, stereo interleaving and signed PCM24 data',async()=>{const bytes=await wave(),r=validateWave(bytes,range);assert.equal(r.frames,24000);assert.equal(r.channels,2);assert.equal(r.seconds,.5);assert.equal(r.buffer.readIntLE(44,3),4194304);assert.equal(r.buffer.readIntLE(47,3),-4194304);assert.equal(r.buffer.length,44+24000*6);});
test('reject malformed WAV, mismatch range and out-of-bounds source',async()=>{assert.throws(()=>validateWave(Buffer.from('bad'),range));const bytes=await wave();assert.throws(()=>validateWave(bytes,{inSeconds:0,outSeconds:1}));await assert.rejects(encode({sampleRate:48000,numberOfChannels:1,length:1,getChannelData:()=>new Float32Array(1)},range));});
async function setup(){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'hnh-export-')),src=path.join(dir,'source.wav'),dest=path.join(dir,'out.wav');await fs.writeFile(src,await wave());const st=await fs.stat(src),file={path:src,size:st.size,mtimeMs:st.mtimeMs,extension:'wav'},handlers={},choice={filePath:dest,canceled:false};registerAudioExport({ipcMain:{handle:(k,f)=>handlers[k]=(...a)=>f(null,...a)},dialog:{showSaveDialog:async()=>choice},getWindow:()=>null,loadIndex:async()=>({files:[file]})});return {dir,src,dest,file,handlers,choice};}
test('prepare/save writes new file, keeps source byte-identical, token cannot replay',async()=>{const x=await setup(),before=await fs.readFile(x.src),job=await x.handlers['export:prepare']({file:x.file,range});const r=await x.handlers['export:save'](job.token,await wave());assert(r.ok);assert.deepEqual(await fs.readFile(x.src),before);assert.deepEqual(await fs.readFile(x.dest),Buffer.from(await wave()));await assert.rejects(x.handlers['export:save'](job.token,await wave()),/hết hạn/);});
test('cancel creates nothing, rejects existing destination/source, never overwrites race-created file',async()=>{const x=await setup();x.choice.canceled=true;assert.deepEqual(await x.handlers['export:prepare']({file:x.file,range}),{canceled:true});x.choice.canceled=false;x.choice.filePath=x.src;await assert.rejects(x.handlers['export:prepare']({file:x.file,range}),/file mới/);x.choice.filePath=x.dest;const job=await x.handlers['export:prepare']({file:x.file,range});await fs.writeFile(x.dest,'keep');await assert.rejects(x.handlers['export:save'](job.token,await wave()),/EEXIST/);assert.equal(await fs.readFile(x.dest,'utf8'),'keep');});
test('source changes between prepare and save abort export',async()=>{const x=await setup(),job=await x.handlers['export:prepare']({file:x.file,range});await fs.appendFile(x.src,'changed');await assert.rejects(x.handlers['export:save'](job.token,await wave()),/thay đổi/);await assert.rejects(fs.stat(x.dest),/ENOENT/);});
