const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {AutoBin,classify}=require('../auto-bin');
async function setup(){let seq=0;const folders=[],calls=[],config={key:'project',fail:false,failAfter:false};const item=(name,type='Audio',file='D:/'+name)=>({GetUniqueId:async()=>name,GetName:async()=>name,GetClipProperty:async()=>({Type:type,'File Path':file})});const folder=name=>{const f={uid:'folder'+(++seq),name,clips:[],children:[],GetUniqueId:async()=>f.uid,GetName:async()=>f.name,GetClipList:async()=>f.clips,GetSubFolderList:async()=>f.children,GetIsFolderStale:async()=>!!f.stale};folders.push(f);return f;};const root=folder('Master'),custom=folder('User footage');root.children.push(custom);root.clips.push(item('sound.wav'),item('video.mp4','Video + Audio'),item('pic.png','Still'),item('unknown.xyz',''),item('Timeline 1','', ''),item('compound.mov','Compound Clip'));custom.clips.push(item('keep.wav'));
 const pool={GetUniqueId:async()=>'pool',GetRootFolder:async()=>root,GetCurrentFolder:async()=>custom,AddSubFolder:async(parent,name)=>{calls.push('create');const f=folder(name);parent.children.push(f);return f;},MoveClips:async(items,target)=>{calls.push('move');if(config.fail)return false;for(const f of folders)f.clips=f.clips.filter(c=>!items.includes(c));target.clips.push(...items);if(config.failAfter){config.failAfter=false;return false;}return true;}};
 const project={GetUniqueId:async()=>config.key,GetMediaPool:async()=>pool,GetTimelineCount:async()=>1,GetTimelineByIndex:async()=>({GetMediaPoolItem:async()=>item('Timeline 1')})};const getResolve=async()=>({GetProjectManager:async()=>({GetCurrentProject:async()=>project})});const dir=await fs.mkdtemp(path.join(os.tmpdir(),'hnh-auto-bin-'));const options={dir,getResolve};return {service:new AutoBin(options),options,root,custom,folders,calls,config,pool,project,item,folder};}
test('classification prefers Resolve and excludes special/uncertain items',()=>{assert.equal(classify({Type:'Video','File Path':'a.png'}).kind,'video');assert.equal(classify({Type:'Audio','File Path':'a.mov'}).kind,'audio');assert.equal(classify({Type:'Still','File Path':'a.mov'}).kind,'image');assert.equal(classify({'File Path':'a.BRAW'}).kind,'video');assert.equal(classify({'File Path':'a.bin'}).kind,'other');for(const Type of ['Multicam Clip','Fusion Composition','Compound Clip','Timeline','Unknown special'])assert.equal(classify({Type,'File Path':'a.mp4'}).kind,null);assert.equal(classify({Type:'Video','File Path':'a.mp4'},true).kind,null);assert.equal(classify({Type:'Audio'}).kind,null);});
test('scan is read only; root scope ignores nested contents and skips timelines',async()=>{const x=await setup(),r=await x.service.scan();assert.deepEqual(r.counts,{video:1,audio:1,image:1,other:1,timeline:0,compound:0,skip:2});assert.equal(x.calls.length,0);assert.equal(r.rows.some(i=>i.name==='keep.wav'),false);assert.equal(r.rows.some(i=>'file' in i),false);});
test('real folder moves reuse existing bin, preserve item identity and survive service restart for undo',async()=>{const x=await setup(),audio=x.folder('02_AUDIO');x.root.children.push(audio);const old=x.root.clips.slice(),scan=await x.service.scan(),result=await x.service.apply(scan.token);assert.equal(result.moved,4);assert.equal(x.calls.filter(x=>x==='create').length,3);assert.equal(audio.clips[0],old[0]);assert.equal(x.custom.clips.length,1);assert.equal(x.root.clips.length,2);const undo=await new AutoBin(x.options).undo();assert.equal(undo.remaining,0);assert.equal(x.root.clips.length,6);assert(x.root.clips.includes(old[0]));assert.equal(x.root.children.length,5);});
test('current scope creates target bins under current folder only',async()=>{const x=await setup(),scan=await x.service.scan('current');assert.equal(scan.counts.audio,1);assert.equal((await x.service.apply(scan.token)).moved,1);assert.equal(x.root.clips.length,6);assert.equal(x.custom.children[0].name,'02_🎵 AUDIO');});
test('preview token is single use and refuses project changes',async()=>{const x=await setup(),scan=await x.service.scan();x.config.key='other';await assert.rejects(x.service.apply(scan.token),/thay đổi/);assert.equal(x.calls.length,0);await assert.rejects(x.service.apply(scan.token),/hết hạn/);});
test('new media or bin since preview requires rescan without writes',async()=>{const x=await setup(),scan=await x.service.scan();x.root.clips.push(x.item('new.wav'));await assert.rejects(x.service.apply(scan.token),/thay đổi/);assert.equal(x.calls.length,0);});
test('false return after partial native move rolls back the actual moved item',async()=>{const x=await setup(),scan=await x.service.scan();x.config.failAfter=true;const r=await x.service.apply(scan.token);assert.equal(r.failed,true);assert.equal(r.recovery.remaining,0);assert.equal(x.root.clips.length,6);});
test('failure before moving does not remove source clips',async()=>{const x=await setup(),scan=await x.service.scan();x.config.fail=true;const r=await x.service.apply(scan.token);assert.equal(r.failed,true);assert.equal(r.recovery.remaining,0);assert.equal(x.root.clips.length,6);});
test('undo refuses another project and skips media moved by user',async()=>{const x=await setup(),scan=await x.service.scan();await x.service.apply(scan.token);x.config.key='other';await assert.rejects(x.service.undo(),/đúng project/);x.config.key='project';const audio=x.root.children.find(f=>f.name==='02_🎵 AUDIO');await x.pool.MoveClips([audio.clips[0]],x.custom);const r=await x.service.undo();assert.equal(r.remaining,1);assert.equal(x.custom.clips.length,2);const next=await x.service.scan();assert.equal(next.recoveryNeeded,true);await assert.rejects(x.service.apply(next.token),/chưa phục hồi/);});
test('duplicate target names and stale collaboration bins fail closed',async()=>{const x=await setup();x.root.children.push(x.folder('01_VIDEO'),x.folder('01_VIDEO'));await assert.rejects(x.service.scan(),/cùng nhóm/);x.root.children=[];x.root.stale=true;await assert.rejects(x.service.scan(),/cộng tác/);});
test('journal write failure prevents clip movement',async()=>{const x=await setup(),scan=await x.service.scan();x.service.write=async()=>{throw Error('disk full');};await assert.rejects(x.service.apply(scan.token),/disk full/);assert.equal(x.calls.length,0);});
test('unknown collection response is not treated as an empty bin',async()=>{const x=await setup();x.root.GetClipList=async()=>null;await assert.rejects(x.service.scan(),/danh sách/);assert.equal(x.calls.length,0);});
test('deleted source folder is reported rather than recreated during undo',async()=>{const x=await setup(),scan=await x.service.scan('current');await x.service.apply(scan.token);x.root.children=[];const r=await x.service.undo();assert.equal(r.remaining,1);assert.equal(x.root.children.length,0);});

test('decorated targets are reused and mixed old/new aliases never create duplicate groups',async()=>{const x=await setup(),audio=x.folder('02_🎵 AUDIO');x.root.children.push(audio);const scan=await x.service.scan();assert.equal(scan.destinations.audio,'02_🎵 AUDIO');await x.service.apply(scan.token);assert.equal(audio.clips.length,1);assert.equal(x.calls.filter(c=>c==='create').length,3);x.root.children.push(x.folder('02_AUDIO'));await assert.rejects(x.service.scan(),/cùng nhóm/);});

test('Ctrl+Z returns clips to source and removes target bins: rescan unlocks without native writes',async()=>{const x=await setup(),scan=await x.service.scan();await x.service.apply(scan.token);for(const f of x.root.children.filter(f=>f!==x.custom)){x.root.clips.push(...f.clips);f.clips=[];}x.root.children=[x.custom];const before=x.calls.length;const fresh=await new AutoBin(x.options).scan();assert.equal(fresh.recoveryNeeded,false);assert.equal(x.calls.length,before);assert(fresh.recoveryRows.every(r=>r.state==='source'));assert.equal((await x.service.undo()).remaining,0);const next=await x.service.scan();assert.equal((await x.service.apply(next.token)).moved,4);});
test('partial Ctrl+Z reconciles source clips and undo restores only remaining destination items',async()=>{const x=await setup(),scan=await x.service.scan();await x.service.apply(scan.token);const audio=x.root.children.find(f=>f.name==='02_🎵 AUDIO');await x.pool.MoveClips([audio.clips[0]],x.root);x.root.children=x.root.children.filter(f=>f!==audio);const fresh=await x.service.scan();assert.equal(fresh.recoveryNeeded,true);assert.equal(fresh.recoveryRows.filter(r=>r.state==='source').length,1);assert.equal((await x.service.undo()).restored,3);assert.equal(x.root.clips.length,6);});
test('missing item cannot be matched by filename; explicit archive preserves history without moves',async()=>{const x=await setup(),scan=await x.service.scan();await x.service.apply(scan.token);const audio=x.root.children.find(f=>f.name==='02_🎵 AUDIO');audio.clips=[];const fresh=await x.service.scan();assert(fresh.recoveryNeeded);assert.equal(fresh.recoveryRows.filter(r=>r.state==='missing').length,1);await assert.rejects(x.service.archive('wrong'),/quét/);const review=await x.service.scan();const before=x.calls.length;await x.service.archive(review.archiveToken);assert.equal(x.calls.length,before);assert.equal((await fs.readdir(path.join(x.options.dir,'auto-bin-history'))).length,1);assert.equal((await x.service.scan()).recoveryNeeded,false);assert.equal((await x.service.undo()).restored,0);});
test('archive refuses media changes after review',async()=>{const x=await setup(),scan=await x.service.scan();await x.service.apply(scan.token);const audio=x.root.children.find(f=>f.name==='02_🎵 AUDIO');await x.pool.MoveClips([audio.clips[0]],x.custom);const review=await x.service.scan();await x.pool.MoveClips([x.custom.clips.at(-1)],x.root);await assert.rejects(x.service.archive(review.archiveToken),/thay đổi/);});
test('custom destination names, disabled groups and shared target create only one bin',async()=>{const x=await setup(),scan=await x.service.scan({scope:'root',groups:{video:{name:'Sources'},audio:{name:'Sources'},image:{enabled:false},other:{enabled:false}}});assert.equal(scan.counts.skip,4);assert.equal(scan.destinations.video,'Sources');assert.equal((await x.service.apply(scan.token)).moved,2);assert.equal(x.calls.filter(c=>c==='create').length,1);assert.equal(x.root.children.find(f=>f.name==='Sources').clips.length,2);});
test('existing folder selected by ID wins over typed name, missing target ID rejected',async()=>{const x=await setup();const scan=await x.service.scan({groups:{audio:{name:'ignored',targetId:x.custom.uid}}});assert.equal(scan.destinations.audio,'User footage');await x.service.apply(scan.token);assert.equal(x.custom.clips.length,2);await assert.rejects(x.service.scan({groups:{audio:{targetId:'absent'}}}),/không còn/);});
test('Timeline and exact Compound Clip opt-in; unknown special types stay excluded',async()=>{const x=await setup();x.root.clips.push(x.item('ambiguous.mov','Compound Something'));const scan=await x.service.scan({groups:{timeline:{enabled:true},compound:{enabled:true}}});assert.equal(scan.counts.timeline,1);assert.equal(scan.counts.compound,1);assert.equal(scan.counts.skip,1);assert.equal((await x.service.apply(scan.token)).moved,6);assert.equal((await x.service.undo()).remaining,0);});
test('invalid destination name rejected before scan or mutation',async()=>{const x=await setup();for(const name of ['', 'a/b','a\\b'])await assert.rejects(x.service.scan({groups:{audio:{name}}}),/Tên Bin/);assert.equal(x.calls.length,0);});
