const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {between}=require('../changelog'),{Updater}=require('../updater');const temp=()=>fs.mkdtemp(path.join(os.tmpdir(),'hnh-history-'));
const release=v=>({tag_name:'v'+v,body:'Notes '+v,assets:[{name:'HNH_SFX_Finder_v'+v+'.zip',size:20,state:'uploaded'}]});
test('skipped releases include every bundled version strictly after old through target',()=>{const x=between('0.6.1','0.8.1');assert.deepEqual(x.map(r=>r.version),['0.8.1','0.8.0','0.7.4','0.7.3','0.7.2','0.7.1','0.7.0']);assert(!x.some(r=>r.version==='0.6.1'));});
test('remote notes replace bundled version, stable numeric ordering and dedup',()=>{const r=between('0.8.5','0.10.0',[{version:'0.9.0',notes:'remote'},{version:'0.10.0',notes:'ten'},{version:'0.9.0-beta',notes:'no'}]);assert.deepEqual(r.map(x=>x.version),['0.10.0','0.9.10','0.9.9','0.9.8','0.9.7','0.9.6','0.9.5','0.9.4','0.9.3','0.9.2','0.9.1','0.9.0']);assert.equal(r.find(x=>x.version==='0.9.0').notes,'remote');});
test('upgrade notification persists until acknowledged, repeat launch does not reset it',async()=>{const dir=await temp();await fs.writeFile(path.join(dir,'update-state.json'),JSON.stringify({lastSeenVersion:'0.6.1'}));const u=new Updater(dir,'0.9.0');let r=await u.state();assert(r.installed.pending);assert.equal(r.installed.from,'0.6.1');assert(r.installed.entries.some(x=>x.version==='0.7.0'));r=await u.acknowledge();assert(!r.installed.pending);const again=await new Updater(dir,'0.9.0').state();assert(!again.installed.pending);assert.equal(again.installed.from,'0.6.1');});
test('unknown prior version uses explicit unknown history; downgrade does not claim upgrade',async()=>{const u=new Updater(await temp(),'0.9.0');assert((await u.state()).installed.unknown);const dir=await temp();await fs.writeFile(path.join(dir,'update-state.json'),JSON.stringify({lastSeenVersion:'1.0.0'}));assert.equal((await new Updater(dir,'0.9.0').state()).installed,null);});
test('installer receipt recovers old version including PowerShell UTF-8 BOM',async()=>{const dir=await temp(),data=await temp();for(const f of ['updater.js','changelog.js','release-history.json'])await fs.copyFile(path.join(__dirname,'..',f),path.join(dir,f));await fs.writeFile(path.join(dir,'install-receipt.json'),'\uFEFF'+JSON.stringify({from:'0.6.1',to:'0.9.0'}));const {Updater:Installed}=require(path.join(dir,'updater.js'));const r=await new Installed(data,'0.9.0').state();assert.equal(r.installed.from,'0.6.1');assert.equal(r.installed.unknown,false);assert(r.installed.entries.some(e=>e.version==='0.7.0'));});
test('upcoming release combines history; incomplete history/network errors surfaced without hiding update',async()=>{const dir=await temp(),u=new Updater(dir,'0.6.1',async()=>release('0.9.0'),()=>1000000,async()=>({entries:[{version:'0.8.0',notes:'remote body'}],partial:true}));let r=await u.check();assert(r.available);assert.match(r.historyNotice,/chưa đầy đủ/);assert.equal(r.historyEntries.find(x=>x.version==='0.8.0').notes,'remote body');const v=new Updater(await temp(),'0.6.1',async()=>release('0.9.0'),()=>1000000,async()=>{throw Error('offline');});r=await v.check();assert(r.available);assert.match(r.historyNotice,/offline/);assert(r.historyEntries.some(x=>x.version==='0.7.0'));});
