const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),zlib=require('node:zlib');
const {Portable,validate}=require('../portable'),lib=require('../library');
const defaults=()=>({libraries:[],tags:{},favorites:[],recent:[],usage:{},collections:[],ui:{trackIndex:2,previewVolume:80}});
async function setup(){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'hnh-portable-'));const read=async(n,f)=>{try{return JSON.parse(await fs.readFile(path.join(dir,n),'utf8'));}catch(e){if(e.code==='ENOENT')return f;throw e;}};const write=(n,v)=>fs.writeFile(path.join(dir,n),JSON.stringify(v));await write('settings.json',defaults());await write('sfx-index.json',{version:3,files:[]});const portable=new Portable(dir,{loadSettings:()=>read('settings.json',defaults()),loadIndex:()=>read('sfx-index.json',{files:[]})});return {dir,read,write,p:portable};}
async function audio(root,name,bytes='audio test'){const file=path.join(root,name);await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,bytes);return file;}
async function source(){const x=await setup(),root=path.join(x.dir,'source'),a=await audio(root,'Whoosh/air.wav');const index=await lib.scan([{path:root}]);index.files[0].duration=2;await x.write('sfx-index.json',index);await x.write('settings.json',{...defaults(),libraries:[{path:root}],tags:{[a]:['gió','nhanh']},favorites:[a],recent:[a],usage:{[a]:5},collections:[{name:'Whoosh',filters:{library:root,folder:{root,path:'Whoosh'}}}]});const wave={peaks:Array(900).fill(.25),duration:2};await fs.mkdir(path.join(x.dir,'waveforms-v1'));await x.write('waveforms-v1/'+lib.fingerprint(index.files[0])+'.json',wave);const file=path.join(x.dir,'save.hnhbackup');await x.p.exportFile(file,{waveforms:true,history:true});return {...x,root,a,file,wave};}
test('export, relocated and renamed content, merge, cache rekey, collections, undo',async()=>{const s=await source(),t=await setup(),root=path.join(t.dir,'new'),dest=await audio(root,'renamed.wav');await t.write('settings.json',{...defaults(),tags:{[dest]:['existing']},favorites:['keep.wav'],ui:{trackIndex:7,previewVolume:20}});const before=await t.read('settings.json');const manifest=JSON.parse(zlib.gunzipSync(await fs.readFile(s.file)));assert.equal(manifest.files[0].sha256.length,64);assert.equal(manifest.files[0].waveform.peaks.length,900);await t.p.openFile(s.file);const plan=await t.p.prepare({[s.root]:root});assert.equal(plan.exact,1);const r=await t.p.apply(plan.token,{}, {ui:true,history:true});assert.equal(r.matched,1);assert.deepEqual(r.settings.tags[dest],['existing','gió','nhanh']);assert(r.settings.favorites.includes('keep.wav'));assert(r.settings.favorites.includes(dest));assert.equal(r.settings.usage[dest],5);assert.equal(r.settings.ui.trackIndex,7);assert.equal(r.settings.ui.previewVolume,80);assert.equal(r.settings.collections[0].filters.folder.root,root);assert.equal(r.waveforms,1);const f=r.index.files.find(f=>f.path===dest);assert.deepEqual(await t.read('waveforms-v1/'+lib.fingerprint(f)+'.json'),s.wave);await t.p.undo();assert.deepEqual(await t.read('settings.json'),before);assert.equal((await t.read('sfx-index.json')).files.length,0);});
test('same name with different bytes is manual; cache must not transfer',async()=>{const s=await source(),t=await setup(),root=path.join(t.dir,'new'),dest=await audio(root,'Whoosh/air.wav','wrong data');await t.p.openFile(s.file);const plan=await t.p.prepare({[s.root]:root});assert.equal(plan.exact,0);assert.equal(plan.review,1);const r=await t.p.apply(plan.token,{0:dest},{});assert.equal(r.waveforms,0);assert(r.settings.favorites.includes(dest));});
test('identical copies are ambiguous unless mapped relative path identifies one',async()=>{const s=await source(),t=await setup(),root=path.join(t.dir,'new');await audio(root,'one.wav');await audio(root,'two.wav');await t.p.openFile(s.file);let plan=await t.p.prepare({[s.root]:root});assert.equal(plan.review,1);assert.equal(plan.exact,0);await audio(root,'Whoosh/air.wav');plan=await t.p.prepare({[s.root]:root});assert.equal(plan.exact,1);});
test('missing file remains pending and reconnects later with tags and favorite',async()=>{const s=await source(),t=await setup(),root=path.join(t.dir,'later');await fs.mkdir(root);await t.p.openFile(s.file);let plan=await t.p.prepare({[s.root]:root});let r=await t.p.apply(plan.token);assert.equal(r.pending,1);assert.equal(r.matched,0);const dest=await audio(root,'moved.wav');await t.p.openPending();plan=await t.p.prepare({[s.root]:root});r=await t.p.apply(plan.token);assert.equal(r.pending,0);assert.deepEqual(r.settings.tags[dest],['gió','nhanh']);assert(r.settings.favorites.includes(dest));});
test('changed target rejects apply without changing database',async()=>{const s=await source(),t=await setup(),root=path.join(t.dir,'new'),dest=await audio(root,'Whoosh/air.wav');await t.p.openFile(s.file);const plan=await t.p.prepare({[s.root]:root}),before=await t.read('settings.json');await fs.writeFile(dest,'changed completely');await assert.rejects(t.p.apply(plan.token),/thay đổi/);assert.deepEqual(await t.read('settings.json'),before);});
test('cancellation during matching preserves state',async()=>{const s=await source(),t=await setup();await t.p.openFile(s.file);t.p.hooks.progress=()=>t.p.cancel();await assert.rejects(t.p.prepare({[s.root]:s.root}),/hủy/);assert.deepEqual(await t.read('settings.json'),defaults());});
test('reject corrupt files, unsupported schema and parent traversal; tolerate null UI',async()=>{const t=await setup(),f=path.join(t.dir,'bad.hnhbackup');await fs.writeFile(f,'bad');await assert.rejects(t.p.openFile(f));assert.throws(()=>validate({format:'hnh-sfx-backup',version:2,files:[]}));assert.throws(()=>validate({format:'hnh-sfx-backup',version:1,files:[{originalPath:'x',filename:'x.wav',relativePath:'../x.wav',size:1}]}));assert.deepEqual(validate({format:'hnh-sfx-backup',version:1,files:[],settings:{ui:null}}).settings.ui,{});});
test('crash recovery restores snapshot and rejects an external snapshot path',async()=>{const t=await setup(),before=await t.read('settings.json'),backup=await t.p.snapshot();await t.write('settings.json',{broken:true});await t.write('restore-journal.json',{backup});await t.p.recover();assert.deepEqual(await t.read('settings.json'),before);await assert.rejects(t.p.restoreSnapshot(path.join(t.dir,'outside')),/không hợp lệ/);});
test('transaction failure rolls back all core data',async()=>{const s=await source(),t=await setup();await t.p.openFile(s.file);const plan=await t.p.prepare({[s.root]:s.root}),before=await t.read('settings.json');const rename=fs.rename;let failed=false;fs.rename=async(a,b)=>{if(!failed&&b===path.join(t.dir,'pending-restores.json')){failed=true;throw Error('injected disk failure');}return rename(a,b);};try{await assert.rejects(t.p.apply(plan.token),/injected/);}finally{fs.rename=rename;}assert(failed);assert.deepEqual(await t.read('settings.json'),before);assert.equal((await t.read('sfx-index.json')).files.length,0);});
test('orphan tags/favorites survive export without readable audio',async()=>{const t=await setup(),missing=path.join(t.dir,'missing.wav');await t.write('settings.json',{...defaults(),favorites:[missing],tags:{[missing]:['keep']}});const out=path.join(t.dir,'orphan.hnhbackup');const r=await t.p.exportFile(out);assert.equal(r.warningCount,1);await t.p.openFile(out);assert.equal(t.p.active.files[0].favorite,true);assert.deepEqual(t.p.active.files[0].tags,['keep']);assert.equal(t.p.active.files[0].sha256,null);});

test('relink current library after drive move uses cached identity and transfers waveform',async()=>{const s=await source(),destRoot=path.join(s.dir,'moved');await fs.rename(s.root,destRoot);const before=await s.read('settings.json'),summary=await s.p.openLibrary(s.root);assert(summary.relink);assert.equal(summary.files,1);assert.deepEqual(await s.read('settings.json'),before);const plan=await s.p.prepare({[s.root]:destRoot});assert.equal(plan.exact,1);const r=await s.p.apply(plan.token,{}, {waveforms:true,history:true});const dest=path.join(destRoot,'Whoosh/air.wav');assert(r.settings.favorites.includes(dest));assert.deepEqual(r.settings.tags[dest],['gió','nhanh']);assert.equal(r.waveforms,1);await s.p.undo();assert.deepEqual(await s.read('settings.json'),before);});
test('relink without hash is review-only and suggested relative match requires explicit override',async()=>{const s=await source();await fs.unlink(path.join(s.dir,'identity-cache.json'));const root=path.join(s.dir,'new');await fs.rename(s.root,root);await s.p.openLibrary(s.root);const plan=await s.p.prepare({[s.root]:root});assert.equal(plan.exact,0);assert.equal(plan.review,1);assert.equal(plan.rows[0].suggested,path.join(root,'Whoosh/air.wav'));const r=await s.p.apply(plan.token,{},{});assert.equal(r.matched,0);assert.equal(r.pending,1);await s.p.openLibrary(s.root);const next=await s.p.prepare({[s.root]:root});const applied=await s.p.apply(next.token,{0:next.rows[0].suggested},{});assert.equal(applied.matched,1);assert.equal(applied.waveforms,0);});
test('relink excludes old location from candidates and never suggests ambiguous or changed-size files',async()=>{const s=await source();await fs.unlink(path.join(s.dir,'identity-cache.json'));const root=path.join(s.dir,'new');await audio(root,'Whoosh/air.wav');await audio(root,'Other/air.wav');await s.p.openLibrary(s.root);let plan=await s.p.prepare({[s.root]:root});assert.equal(plan.review,1);assert.equal(plan.rows[0].candidates.length,2);assert.equal(plan.rows[0].suggested,null);assert(plan.rows[0].candidates.every(f=>f.path.startsWith(root)));await fs.unlink(path.join(root,'Other/air.wav'));await fs.writeFile(path.join(root,'Whoosh/air.wav'),'different size bytes');plan=await s.p.prepare({[s.root]:root});assert.equal(plan.rows[0].suggested,null);});
test('relink keeps orphan tags/favorites for user review and validates library selection',async()=>{const t=await setup(),root=path.join(t.dir,'missing'),p=path.join(root,'keep.wav');await t.write('settings.json',{...defaults(),libraries:[{path:root}],tags:{[p]:['keep']},favorites:[p]});const r=await t.p.openLibrary(root);assert.equal(r.files,1);assert.equal(t.p.active.files[0].sha256,null);assert.deepEqual(t.p.active.files[0].tags,['keep']);await assert.rejects(t.p.openLibrary(path.join(t.dir,'other')),/không còn/);});
