const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {chooseAudioTrack,createSmartInserter}=require('../smart-audio');
const clip=(a,b)=>({GetStart:async()=>a,GetEnd:async()=>b});
function timeline(tracks){return {tracks,locked:new Set(),disabled:new Set(),GetTrackCount:async()=>tracks.length,GetIsTrackLocked:async(_,i)=>false,GetIsTrackEnabled:async()=>true,GetItemListInTrack:async(_,i)=>tracks[i-1],AddTrack:async(_,options)=>{if(options.index===1)tracks.unshift([]);else tracks.push([]);return true;}};}
const choose=(t,extra={})=>chooseAudioTrack({timeline:t,preferred:1,start:100,end:202,...extra});
test('requested track preferred, full interval checked, then first free track',async()=>{const t=timeline([[clip(150,170)],[],[]]);assert.equal((await choose(t,{preferred:3})).trackIndex,3);assert.equal((await choose(t)).trackIndex,2);t.tracks[0]=[clip(0,100),clip(202,300)];assert.equal((await choose(t)).trackIndex,1);});
test('locked and disabled tracks skipped; malformed clip collection fails closed',async()=>{const t=timeline([[],[],[]]);t.GetIsTrackLocked=async(_,i)=>i===1;t.GetIsTrackEnabled=async(_,i)=>i!==2;assert.equal((await choose(t)).trackIndex,3);t.GetItemListInTrack=async()=>null;await assert.rejects(()=>choose(t),/Không đọc/);});
test('create top A1 shifts original track objects; bottom appends; no creation without opt-in',async()=>{const old=[clip(0,300)],t=timeline([old]);await assert.rejects(()=>choose(t),/Không có track/);const r=await choose(t,{create:true});assert.equal(r.created,true);assert.equal(r.trackIndex,1);assert.equal(t.tracks[1],old);const b=timeline([old]);assert.equal((await choose(b,{create:true,placement:'bottom'})).trackIndex,2);});
test('changed context prevents creation; ignored insertion option aborts without second track',async()=>{const t=timeline([[clip(0,300)]]);await assert.rejects(()=>choose(t,{create:true,guard:async()=>{throw Error('changed');}}),/changed/);assert.equal(t.tracks.length,1);t.AddTrack=async()=>{t.tracks.push([]);return true;};await assert.rejects(()=>choose(t,{create:true}),/không đặt/);assert.equal(t.tracks.length,2);});
async function setup(){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'hnh-smart-')),p=path.join(dir,'sound.wav');await fs.writeFile(p,'fixture');const stat=await fs.stat(p),file={path:p,size:stat.size,mtimeMs:stat.mtimeMs,extension:'wav',duration:4};const t=timeline([[clip(100,200)],[]]);let pos=100;const config={duration:100,track:2},appends=[],deletes=[];t.GetUniqueId=async()=>'timeline';t.DeleteClips=async(items,ripple)=>{deletes.push({items,ripple});return true;};const item={GetAudioMapping:async()=>({embedded_audio_channels:2,track_mapping:{1:{mute:false}}}),GetClipProperty:async key=>key==='FPS'?25:100};const project={GetUniqueId:async()=>'project',GetCurrentTimeline:async()=>t,GetMediaPool:async()=>({AppendToTimeline:async infos=>{appends.push(infos);return [{GetTrackTypeAndIndex:async()=>['audio',config.track],GetStart:async()=>100,GetDuration:async()=>config.duration}];}})};const insert=createSmartInserter({getResolve:async()=>({GetProjectManager:async()=>({GetCurrentProject:async()=>project})}),loadIndex:async()=>({files:[file]}),importItem:async()=>{if(config.changed)pos=150;return {ok:true,item};},resultItems:x=>x,getPosition:async()=>({recordFrame:pos,fps:25,timecode:'00:00:04:00'})});return {dir,file,t,config,appends,deletes,insert};}
test('smart insertion chooses A2, rejects changed playhead, rolls back only mismatched result',async()=>{const x=await setup();try{let r=await x.insert(x.file.path,1,null,{create:true});assert.equal(r.ok,true,r.error);assert.equal(x.appends[0][0].trackIndex,2);x.config.duration=80;r=await x.insert(x.file.path,1,null,{});assert.equal(r.ok,false);assert.equal(x.deletes.length,1);assert.equal(x.deletes[0].ripple,false);x.config.changed=true;r=await x.insert(x.file.path,1,null,{});assert.equal(r.ok,false);assert.match(r.error,/Playhead/);assert.equal(x.appends.length,2);}finally{await fs.rm(x.dir,{recursive:true,force:true});}});
test('smart insertion uses selected source range rather than full duration',async()=>{const x=await setup();try{x.config.duration=25;const r=await x.insert(x.file.path,1,{inSeconds:1,outSeconds:2,duration:4},{});assert.equal(r.ok,true,r.error);assert.equal(x.appends[0][0].startFrame,25);assert.equal(x.appends[0][0].endFrame,49);}finally{await fs.rm(x.dir,{recursive:true,force:true});}});
