const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {Updater,newer,release,pickRelease,registerUpdater}=require('../updater');
const data=(tag='v0.7.5')=>({tag_name:tag,body:'New version <img src=x>',draft:false,prerelease:false,assets:[{name:'HNH_SFX_Finder_v'+tag.slice(1)+'.zip',size:10,state:'uploaded'}]});
test('numeric version ordering and stable release validation',()=>{assert(newer('v0.7.10','0.7.9'));assert(!newer('v0.7.4','0.7.4'));assert(!newer('v0.7.3','0.7.4'));assert(!newer('v0.8.0-beta','0.7.4'));assert.throws(()=>release({...data(),prerelease:true}));assert.throws(()=>release({...data(),tag_name:'https://bad.test'}));assert.equal(release({...data(),assets:[]}).ready,false);assert.equal(release(data()).ready,true);});
test('daily check, manual cooldown, ignored/deferred versions, disabled auto and persistence',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'hnh-update-'));let time=100000000,calls=0;const u=new Updater(dir,'0.7.4',async()=>{calls++;return data();},()=>time);let r=await u.check();assert(r.available);await u.check();await u.check(true);assert.equal(calls,1);time+=61000;await u.check(true);assert.equal(calls,2);r=await u.configure({defer:'0.7.5'});assert(r.deferred);time+=86400001;r=await u.state();assert(!r.deferred);r=await u.configure({ignore:'0.7.5'});assert(r.ignored);await u.configure({auto:false});await u.check();assert.equal(calls,2);await u.check(true);assert.equal(calls,3);const reload=new Updater(dir,'0.7.4');assert.equal((await reload.state()).auto,false);assert.equal((await reload.state()).ignored,true);});
test('offline and no assets are not successful update announcements',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'hnh-update-')),u=new Updater(dir,'0.7.4',async()=>{throw Error('offline');});const r=await u.check();assert.equal(r.error,'offline');assert(!r.available);const n=new Updater(await fs.mkdtemp(path.join(os.tmpdir(),'hnh-update-')),'0.7.4',async()=>({...data(),assets:[]}));assert.equal((await n.check()).available,false);});
test('external page uses fixed repository, never release-provided URL',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'hnh-update-')),handlers={};let opened;const u=registerUpdater({dir,current:'0.7.4',ipcMain:{handle:(name,fn)=>handlers[name]=fn},shell:{openExternal:async url=>opened=url}});u.fetchHistory=null;u.fetch=async()=>({...data(),html_url:'https://bad.test'});await u.check();await handlers['updates:open']();assert.equal(opened,'https://github.com/dmina97-cpu/mrm-media-resource-manager/releases/tag/v0.7.5');});

test('shared repo: plugin version comes from zip name, MRM-only releases are skipped',()=>{
 const mrmOnly={tag_name:'v0.9.0',draft:false,prerelease:false,body:'MRM',assets:[{name:'MRM_0.9.0_x64-setup.exe',size:5,state:'uploaded'}]};
 const both={tag_name:'v0.8.0',draft:false,prerelease:false,body:'both',assets:[{name:'MRM_0.8.0_x64-setup.exe',size:5,state:'uploaded'},{name:'HNH_SFX_Finder_MRM_v0.12.0.zip',size:9,state:'uploaded'}]};
 const r=release([mrmOnly,both]);
 assert.equal(r.version,'0.12.0');assert.equal(r.tag,'v0.8.0');assert.equal(r.assetName,'HNH_SFX_Finder_MRM_v0.12.0.zip');assert.equal(r.ready,true);
 assert.equal(pickRelease([mrmOnly]).tag_name,'v0.9.0');assert.equal(release([mrmOnly]).ready,false,'không có gói plugin -> không báo cập nhật');
 assert(!newer(r.version,'0.12.0'));assert(newer('0.12.1',r.version));
});
