const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const lib=require('../library'),{registerVisualMedia,clipRange}=require('../visual-media'),{Portable}=require('../portable');
async function setup(){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'hnh-visual-')),root=path.join(dir,'assets');await fs.mkdir(root);for(const f of ['sound.wav','ảnh #1.png','clip.mp4','._ignore.mp4','notes.txt'])await fs.writeFile(path.join(root,f),'fixture-'+f);const index=await lib.scan([{path:root}]);const handlers={},calls=[],config={locked:false,trackCount:2,fps:'60',frames:'600',type:'Video',duration:120};let thumbs=0,imports=0;const item={GetClipProperty:async key=>({FPS:config.fps,Frames:config.frames,Type:config.type})[key]};const timeline={GetTrackCount:async()=>config.trackCount,GetTrackName:async(_,i)=>'Track '+i,GetIsTrackLocked:async()=>config.locked};const pool={AppendToTimeline:async info=>{calls.push(info);return [{GetDuration:async()=>config.duration}];}};const project={GetCurrentTimeline:async()=>timeline,GetMediaPool:async()=>pool};const resolve={GetProjectManager:async()=>({GetCurrentProject:async()=>project})};registerVisualMedia({ipcMain:{handle:(name,fn)=>handlers[name]=(...args)=>fn(null,...args)},nativeImage:{createThumbnailFromPath:async()=>{thumbs++;if(config.thumbGate)await config.thumbGate;return {isEmpty:()=>false,toPNG:()=>Buffer.from('thumbnail')};}},dir,loadIndex:async()=>index,getResolve:async()=>resolve,importItem:async()=>{imports++;return {ok:true,item,reused:true};},resultItems:x=>x,getPosition:async()=>({fps:24,recordFrame:86424,timecode:'01:00:01:00'}),exclusive:fn=>fn()});return {dir,root,index,handlers,calls,config,get thumbs(){return thumbs;},get imports(){return imports;},image:index.files.find(f=>f.extension==='png'),video:index.files.find(f=>f.extension==='mp4')};}
test('mixed scanner classifies media, skips sidecars and preserves unchanged/offline records',async()=>{const x=await setup();assert.equal(x.index.files.length,3);assert.deepEqual(x.index.files.map(f=>lib.kind(f.extension)).sort(),['audio','image','video']);const scan=await lib.scan([{path:x.root}],x.index);assert.equal(scan.stats.unchanged,3);const missing=path.join(x.dir,'offline');await fs.rename(x.root,missing);const offline=await lib.scan([{path:x.root}],scan);assert.equal(offline.files.length,3);assert(offline.warnings.length);});
test('image duration uses timeline FPS and selected V2 at exact playhead',async()=>{const x=await setup();x.config.type='Still';const r=await x.handlers['media:insert'](x.image,{trackIndex:2,seconds:5});assert.equal(r.ok,true);const info=x.calls[0][0];assert.equal(info.mediaType,1);assert.equal(info.trackIndex,2);assert.equal(info.recordFrame,86424);assert.equal(info.startFrame,0);assert.equal(info.endFrame,119);assert.equal(r.warning,'');});
test('video In/Out uses source 60 FPS, not timeline 24 FPS',async()=>{const x=await setup();const r=await x.handlers['media:insert'](x.video,{trackIndex:1,range:{inSeconds:2,outSeconds:4,duration:10}});assert.equal(r.ok,true);assert.equal(x.calls[0][0].startFrame,120);assert.equal(x.calls[0][0].endFrame,239);const full=await x.handlers['media:insert'](x.video,{trackIndex:2});assert(full.ok);assert.equal(x.calls[1][0].endFrame,599);});
test('reject locked/missing track, invalid still length/range before append',async()=>{const x=await setup();x.config.locked=true;assert.equal((await x.handlers['media:insert'](x.video,{trackIndex:1})).ok,false);x.config.locked=false;assert.equal((await x.handlers['media:insert'](x.video,{trackIndex:3})).ok,false);assert.equal((await x.handlers['media:insert'](x.image,{trackIndex:1,seconds:0})).ok,false);assert.equal((await x.handlers['media:insert'](x.video,{trackIndex:1,range:{inSeconds:5,outSeconds:2,duration:10}})).ok,false);assert.equal(x.imports,0);assert.equal(x.calls.length,0);});
test('preview encodes file URL and rejects stale/missing/outside selection',async()=>{const x=await setup();const url=await x.handlers['media:preview'](x.image);assert(url.includes('%23'));assert(url.startsWith('file:///'));await assert.rejects(x.handlers['media:preview']({...x.image,size:9}));await assert.rejects(x.handlers['media:preview']({path:'C:/not-indexed.png'}));await fs.writeFile(x.image.path,'changed');await assert.rejects(x.handlers['media:preview'](x.image),/thay đổi/);});
test('thumbnail cache avoids repeated native decoding; import remains usable',async()=>{const x=await setup();assert.match(await x.handlers['media:thumbnail'](x.image),/^data:image\/png/);await x.handlers['media:thumbnail'](x.image);assert.equal(x.thumbs,1);const result=await x.handlers['media:import'](x.video);assert.equal(result.ok,true);assert.equal(x.calls.length,0);});
test('missing source FPS for trim rejects; image sequence blocked and duration discrepancy reported',async()=>{const x=await setup();x.config.fps='';let r=await x.handlers['media:insert'](x.video,{trackIndex:1,range:{inSeconds:0,outSeconds:1,duration:10}});assert.equal(r.ok,false);x.config.type='Video';r=await x.handlers['media:insert'](x.image,{trackIndex:1,seconds:5});assert.equal(r.ok,false);x.config.type='Still';x.config.duration=240;r=await x.handlers['media:insert'](x.image,{trackIndex:1,seconds:5});assert.equal(r.ok,true);assert(r.warning);});
test('mixed media tags/favorites survive backup and remap',async()=>{const x=await setup(),settings={libraries:[{path:x.root}],favorites:[x.image.path,x.video.path],tags:{[x.image.path]:['meme'],[x.video.path]:['overlay']},ui:{}};await fs.writeFile(path.join(x.dir,'settings.json'),JSON.stringify(settings));await fs.writeFile(path.join(x.dir,'sfx-index.json'),JSON.stringify(x.index));const read=n=>fs.readFile(path.join(x.dir,n),'utf8').then(JSON.parse),p=new Portable(x.dir,{loadSettings:()=>read('settings.json'),loadIndex:()=>read('sfx-index.json')});const save=path.join(x.dir,'mixed.hnhbackup');await p.exportFile(save);const dest=path.join(x.dir,'moved');await fs.cp(x.root,dest,{recursive:true});await fs.writeFile(path.join(x.dir,'settings.json'),JSON.stringify({libraries:[],favorites:[],tags:{},ui:{}}));await fs.writeFile(path.join(x.dir,'sfx-index.json'),JSON.stringify({files:[]}));await p.openFile(save);const plan=await p.prepare({[x.root]:dest});assert.equal(plan.exact,3);const result=await p.apply(plan.token);assert.deepEqual(result.settings.tags[path.join(dest,'ảnh #1.png')],['meme']);assert(result.settings.favorites.includes(path.join(dest,'clip.mp4')));});
test('frame range one-frame minimum and bounds',()=>{assert.deepEqual(clipRange('image',{seconds:.001},null,null,24),{startFrame:0,endFrame:0});assert.throws(()=>clipRange('image',{seconds:Infinity},null,null,24));assert.throws(()=>clipRange('video',{range:{inSeconds:9,outSeconds:10,duration:10}},30,200,24));});
test('video audio option reaches AV path and reports unverifiable source without appending picture alone',async()=>{const x=await setup();const tracks=await x.handlers['media:tracks']();assert.equal(tracks.audioTracks.length,2);const r=await x.handlers['media:insert'](x.video,{trackIndex:1,audioTrackIndex:2,includeAudio:true});assert.equal(r.ok,false);assert.match(r.error,/Không xác nhận được audio nguồn/);assert.equal(x.calls.length,0);});

test('cancelled queued thumbnails skip native decode; a new epoch still works',async()=>{const x=await setup();const old=x.handlers['media:thumbnail'](x.image);await x.handlers['media:cancel-thumbnails']();assert.equal(await old,null);assert.equal(x.thumbs,0);assert(await x.handlers['media:thumbnail'](x.image));assert.equal(x.thumbs,1);});

test('in-flight native decode is discarded after cancellation without writing stale cache',async()=>{const x=await setup();let release;x.config.thumbGate=new Promise(r=>release=r);const old=x.handlers['media:thumbnail'](x.image);while(!x.thumbs)await new Promise(r=>setTimeout(r,1));await x.handlers['media:cancel-thumbnails']();release();assert.equal(await old,null);assert.deepEqual(await fs.readdir(path.join(x.dir,'thumbnails-v1')).catch(()=>[]),[]);x.config.thumbGate=null;assert(await x.handlers['media:thumbnail'](x.image));assert.equal(x.thumbs,2);});
