const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];

const state = {
  files: [], settings: { libraries: [], favorites: [], recent: [], usage: {}, ui: {} }, selected: null,
  mode: 'search', resolveReady: false, visible: [], selectedIndex: -1, tracks: [],
  waveform: { path: null, peaks: null, duration: 0, loading: false }, audioContext: null, waveToken: 0
};

function setLibraryFiles(files){state.mediaFiles=files.filter(f=>!f.filename?.startsWith('._'));state.files=state.mediaFiles.filter(f=>HnhMediaTypes.fileKind(f)==='audio');if(state.selected&&!state.files.some(f=>f.path===state.selected.path)){document.querySelector('#audio').pause();state.selected=null;state.waveToken++;state.waveform={peaks:null};resetTrim();$('#nowName').textContent='Chọn SFX';$('#nowMeta').textContent='';$('#tagsInput').value='';$('#tagsInput').disabled=true;$('#saveTags').disabled=true;$('#similarBtn').disabled=true;$('#revealBtn').disabled=true;$('#waveHint').textContent='Chọn SFX để xem waveform';$('#waveHint').style.display='grid';drawWaveform();}window.HnhMedia?.updated();}
const norm=HnhSearch.norm;let audioSearchTimer;let favoriteSource,favoriteSet=new Set();function favoritesSet(){if(favoriteSource!==state.settings.favorites){favoriteSource=state.settings.favorites;favoriteSet=new Set(favoriteSource||[]);}return favoriteSet;}
let queryCache={raw:null,compiled:null};
function scoreFile(file,raw){
 if(queryCache.raw!==raw)queryCache={raw,compiled:HnhSearch.compile(raw)};
 const score=HnhSearch.score(file,queryCache.compiled,state.settings.tags?.[file.path]||[]);
 if(!score)return 0;
 return score+Math.min(1,(state.settings.usage[file.path]||0)*.02)+(favoritesSet().has(file.path)?.5:0);
}

function extensionGroupMatches(fileExt, filter) {
  if (filter === 'all') return true; if (filter === 'aiff') return ['aiff','aif'].includes(fileExt); if (filter === 'm4a') return ['m4a','aac'].includes(fileExt); return fileExt === filter;
}
function getFiltered() {
  const quickMatch=HnhQuickFilters.matcher('audio');const q=$('#searchInput').value; let list=state.files.map(f=>({...f,_score:scoreFile(f,q)}));
  const ext=$('#extensionFilter').value, lib=$('#libraryFilter').value;
  list=list.filter(f=>quickMatch(f)&&extensionGroupMatches(f.extension,ext)&&matchesFolder(f));
  const min=$('#durationMin').value,max=$('#durationMax').value,tag=norm($('#tagFilter').value);
  list=list.filter(f=>HnhSearch.durationMatches(f.duration,min,max)&&(!tag||(state.settings.tags?.[f.path]||[]).some(t=>norm(t)===tag)));
  list=list.filter(f=>!window.HnhSidebarTags||window.HnhSidebarTags.matches(f));
  if(q.trim())list=list.filter(f=>f._score>0); if(lib!=='all')list=list.filter(f=>f.root===lib);
  if(state.mode==='favorites')list=list.filter(f=>favoritesSet().has(f.path));
  else if(state.mode==='recent'){const order=new Map(state.settings.recent.map((p,i)=>[p,i]));list=list.filter(f=>order.has(f.path)).sort((a,b)=>order.get(a.path)-order.get(b.path));return list.slice(0,500)}
  
  const sort=$('#sortMode').value,ioSeconds=window.HnhTimelineRange?.fitSeconds?.()||0,ioRank=f=>{const d=Number(f.duration);return Number.isFinite(d)&&d>0&&d<=ioSeconds+.001?[0,ioSeconds-d]:[1,Number.isFinite(d)?Math.abs(d-ioSeconds):Infinity]};if(sort==='name')list.sort((a,b)=>a.filename.localeCompare(b.filename));else if(sort==='recent')list.sort((a,b)=>b.mtimeMs-a.mtimeMs);else list.sort((a,b)=>{if(ioSeconds){const ar=ioRank(a),br=ioRank(b);if(ar[0]!==br[0])return ar[0]-br[0];if(ar[1]!==br[1])return ar[1]-br[1];}return b._score-a._score||a.filename.localeCompare(b.filename)});return list.slice(0,500);
}

function render() {
  clearTimeout(audioSearchTimer);
  HnhQuickFilters.tags('audio',state.files,state.settings.tags||{});
  renderFolders();
  const list=getFiltered();window.HnhSidebarTags?.refresh();state.visible=list;window.HnhBatch?.visible('audio',list,list);
  if(state.selected){const idx=list.findIndex(x=>x.path===state.selected.path);state.selectedIndex=idx;}else state.selectedIndex=-1;
  $('#resultCount').textContent=`${list.length}${list.length===500?'+':''} / ${state.files.length} SFX`; const host=$('#results');host.textContent='';
  if(!state.files.length){host.innerHTML=state.settings.libraries.length?(state.scanning?'<div class="empty"><strong>Đang tải danh sách SFX.</strong>Các thư viện đã lưu vẫn còn. Xem tiến trình trong mục Thư viện.</div>':'<div class="empty"><strong>Chưa tìm thấy SFX trong các thư viện đã lưu.</strong>Mở Thư viện để kiểm tra đường dẫn và thông báo quét.</div>'):'<div class="empty"><strong>Chưa có SFX trong thư viện.</strong>Mở “Thư viện” → thêm thư mục chứa SFX.</div>';return}
  if(!list.length){host.innerHTML='<div class="empty"><strong>Không tìm thấy SFX phù hợp.</strong>Thử từ khóa ngắn hơn hoặc đổi bộ lọc.</div>';return}
  for(const f of list){const row=document.createElement('div');row.className='row'+(state.selected?.path===f.path?' selected':'');row.dataset.path=f.path;row.tabIndex=-1;const fav=favoritesSet().has(f.path);
    row.innerHTML=`<button class="play-mini" title="Preview">▶</button><div class="file-info"><div class="file-heading"><div class="file-name"></div><div class="name-tags"></div></div><div class="path"></div></div><div class="file-metrics"><span class="duration-badge"></span><span class="ext"></span><span class="score">${$('#searchInput').value.trim()?Math.round(f._score):''}</span></div><button class="star ${fav?'on':''}" title="Yêu thích">${fav?'★':'☆'}</button>`;
    const durationBadge=row.querySelector('.duration-badge');durationBadge.textContent=HnhDuration.format(f.duration);durationBadge.title=HnhDuration.title(f.duration);durationBadge.setAttribute('aria-label',durationBadge.title);row.querySelector('.file-name').textContent=f.filename;row.querySelector('.file-name').title=f.filename+' • '+HnhDates.label(f.addedAt);const added=document.createElement('small');added.className='added-date';added.textContent=HnhDates.valid(f.addedAt)?'Thêm: '+new Date(f.addedAt).toLocaleDateString('vi-VN'):'Ngày thêm: chưa rõ';added.title=HnhDates.label(f.addedAt);row.querySelector('.file-info').appendChild(added);
    const tags=state.settings.tags?.[f.path]||[],showTags=$('#showNameTags').checked,tagHost=row.querySelector('.name-tags');tagHost.hidden=!showTags||!tags.length;
    if(showTags){for(const tag of tags.slice(0,3)){const badge=document.createElement('span');badge.className='name-tag';badge.textContent=tag;badge.title=tag;tagHost.appendChild(badge);}if(tags.length>3){const more=document.createElement('span');more.className='name-tag tag-more';more.textContent='+'+(tags.length-3);more.title=tags.slice(3).join(', ');tagHost.appendChild(more);}tagHost.title=tags.join(', ');}
    row.querySelector('.path').textContent=f.relativePath+(!showTags&&tags.length?' • '+tags.join(', '):'');row.querySelector('.ext').textContent=f.extension;
    window.HnhSfxDrag?.decorate(row,f);window.HnhBatch?.decorate(row,f);row.addEventListener('click',e=>{if(e.target.closest('.star,.batch-check'))return;selectFile(f,true)});row.querySelector('.play-mini').addEventListener('click',e=>{e.stopPropagation();selectFile(f,true)});row.querySelector('.star').addEventListener('click',e=>{e.stopPropagation();toggleFavorite(f)});row.addEventListener('dblclick',e=>{if(!e.target.closest('.batch-check'))insertSelected();});
    row.addEventListener('contextmenu',e=>{e.preventDefault();selectFile(f,false);window.hnh.revealInExplorer(f.path)});host.appendChild(row)}
}

function fileUrl(p){const parts=p.replace(/\\/g,'/').split('/');return 'file:///'+parts.map((v,i)=>i===0?v:encodeURIComponent(v)).join('/');}
function scrollSelectionIntoView(){if(!state.selected)return;requestAnimationFrame(()=>document.querySelector(`.row[data-path="${CSS.escape(state.selected.path)}"]`)?.scrollIntoView({block:'nearest'}))}
function selectFile(f,play=false){if(!f)return;const changed=state.selected?.path!==f.path||state.selected?.size!==f.size||state.selected?.mtimeMs!==f.mtimeMs;state.selected=f;$('#tagsInput').disabled=false;$('#saveTags').disabled=false;$('#tagsInput').value=(state.settings.tags?.[f.path]||[]).join(', ');state.selectedIndex=state.visible.findIndex(x=>x.path===f.path);if(changed){$('#audio').src=fileUrl(f.path);resetTrim();}$('#nowName').textContent=f.filename;$('#nowMeta').textContent=f.relativePath;$('#similarBtn').disabled=false;$('#revealBtn').disabled=false;for(const row of $('#results').querySelectorAll('.row'))row.classList.toggle('selected',row.dataset.path===f.path);window.HnhSidebarTags?.refresh();scrollSelectionIntoView();if(changed)loadWaveform(f);if(play)playPreview()}
function moveSelection(delta){if(!state.visible.length)return;let idx=state.selected?state.visible.findIndex(x=>x.path===state.selected.path):-1;if(idx<0)idx=delta>0?-1:0;idx=Math.max(0,Math.min(state.visible.length-1,idx+delta));selectFile(state.visible[idx],true)}

async function persistUsage(f){state.settings.usage[f.path]=(state.settings.usage[f.path]||0)+1;state.settings.recent=[f.path,...state.settings.recent.filter(x=>x!==f.path)].slice(0,100);state.settings=await window.hnh.updateSettings({usage:state.settings.usage,recent:state.settings.recent})}
async function toggleFavorite(f){const set=new Set(state.settings.favorites);set.has(f.path)?set.delete(f.path):set.add(f.path);state.settings.favorites=[...set];state.settings=await window.hnh.updateSettings({favorites:state.settings.favorites});render()}
function currentUi(){return{audioOptions:window.HnhAudioOptions?.value(),showNameTags:$('#showNameTags').checked,showFolders:$('#showFolders').checked,folder:folderSelection,autoPreview:true,sortMode:$('#sortMode').value,extension:$('#extensionFilter').value,library:$('#libraryFilter').value,trackIndex:Number($('#trackSelect').value)||1,previewVolume:Number($('#previewVolume').value),previewMuted:$('#previewMute').checked,loopSelection:$('#loopSelection').checked}}
let uiSaveTimer=null;function saveUiSoon(){clearTimeout(uiSaveTimer);uiSaveTimer=setTimeout(async()=>{state.settings.ui=currentUi();state.settings=await window.hnh.updateSettings({ui:state.settings.ui})},180)}

async function importSelected(){if(!state.selected)return;const r=await window.hnh.importToMediaPool(state.selected.path);if(r.bridge)renderBridgeStatus(r.bridge);showStatus(r.ok?`Đã import vào Media Pool${r.reused?' (đã có sẵn)':''}`:`Import lỗi: ${r.error||'không xác định'}${r.detail?' • '+r.detail:''}`);if(r.ok)await persistUsage(state.selected)}
let insertingAudio=false;
async function insertSelected(){if(insertingAudio)return;if(window.HnhTimelineRange?.active())return window.HnhTimelineRange.insert();if(!state.selected)return;const file={...state.selected},track=Number($('#trackSelect').value)||1;insertingAudio=true;$('#insertBtn').disabled=true;try{const r=await window.hnh.insertAtPlayhead(file.path,track,trimState.active?trimRange():null,window.HnhAudioOptions?.value());if(r.bridge)renderBridgeStatus(r.bridge);showStatus((r.ok?`Đã chèn ${file.filename} vào A${r.trackIndex||track} tại ${r.timecode}`:`Chèn lỗi: ${r.error||'không xác định'}`)+(r.warning?' • '+r.warning:''));if(r.ok){await persistUsage(file);await window.HnhAudioOptions?.afterInsert(r);}}catch(e){showStatus('Chèn lỗi: '+e.message);}finally{insertingAudio=false;$('#insertBtn').disabled=!state.resolveReady;}}

function showStatus(t){$('#statusLine').textContent=t}

function renderLibraries(){const host=$('#libraries');host.textContent='';if(!state.settings.libraries.length)host.innerHTML='<div class="empty">Chưa thêm thư mục.</div>';for(const lib of state.settings.libraries){const d=document.createElement('div');d.className='library-item';d.innerHTML='<div class="library-path"></div><button class="remove">Xóa</button>';d.querySelector('.library-path').textContent=lib.path;
const types=Array.isArray(lib.types)?lib.types:['audio','image','video'],labels={audio:'Âm thanh',image:'Hình ảnh',video:'Video'};
const badge=document.createElement('small');badge.className='library-type-label';badge.textContent=types.map(t=>labels[t]).join(' · ');badge.title='Các loại tài nguyên đang quét';d.querySelector('.library-path').appendChild(badge);
const change=document.createElement('button');change.className='secondary library-edit-types';change.textContent='Loại quét';change.onclick=()=>window.HnhLibraryTypes.open(lib);d.insertBefore(change,d.querySelector('.remove'));const relink=document.createElement('button');relink.className='secondary library-relink';relink.textContent='Nối lại';relink.onclick=()=>window.HnhRelink.open(lib.path);d.insertBefore(relink,d.querySelector('.remove'));const rm=d.querySelector('.remove');
// Dùng chung với MRM: gỡ thư viện xóa metadata của cả thư viện trong MRM -> chỉ gỡ trong MRM; popup chỉ cách giữ tag (đổi đường dẫn, quét lại, Loại quét)
if(state.mrmMode){rm.textContent='Gỡ…';rm.className='secondary remove-in-mrm';rm.title='Thư mục dùng chung với MRM — xem cách gỡ hoặc sắp xếp lại mà không mất tag';}
const removeLib=async()=>{showStatus('Đang cập nhật thư viện…');const r=await window.hnh.removeLibrary(lib.path);state.settings=r.settings;setLibraryFiles(r.index.files);startMetadata();renderLibraries();renderLibraryFilter();render();showStatus(`Đã quét ${r.scan.count} tài nguyên`)};
rm.onclick=()=>window.HnhLibraryRemove.open(lib,{mrm:state.mrmMode,remove:removeLib});host.appendChild(d)}}
function renderLibraryFilter(){const sel=$('#libraryFilter'),wanted=sel.value||state.settings.ui?.library||'all';sel.innerHTML='<option value="all">Mọi thư viện</option>';for(const lib of state.settings.libraries){const o=document.createElement('option');o.value=lib.path;o.textContent=lib.path.split(/[\\/]/).filter(Boolean).pop()||lib.path;o.title=lib.path;sel.appendChild(o)}sel.value=[...sel.options].some(o=>o.value===wanted)?wanted:'all'}
function bridgeMessage(status){if(status?.ok){const v=status.moduleInfo?.version?` v${status.moduleInfo.version}`:'';return`Resolve đã kết nối • bridge${v}`}if(status?.error==='MISSING_WORKFLOW_INTEGRATION_NODE')return'Không tìm thấy WorkflowIntegration.node của Resolve';if(/ABI mismatch|NODE_MODULE_VERSION|different Node\.js/i.test(status?.detail||''))return'WorkflowIntegration.node không tương thích với Electron của Resolve';if(/Initialize\(.+\) returned false/i.test(status?.detail||''))return'Resolve bridge khởi tạo thất bại (plugin ID/SDK)';return'Resolve bridge chưa sẵn sàng'}
function renderBridgeStatus(status){state.resolveReady=!!status?.ok;const el=$('#bridgeDetail');if(el){const p=status?.modulePath?`\nModule: ${status.modulePath}`:'',d=status?.detail?`\nChi tiết: ${status.detail}`:'';el.textContent=`${bridgeMessage(status)}${p}${d}`;el.className=`bridge-detail ${status?.ok?'ok':'error'}`}$('#importBtn').disabled=!state.resolveReady;$('#insertBtn').disabled=!state.resolveReady}

async function refreshTracks(){const sel=$('#trackSelect'),previous=Number(sel.value)||Number(state.settings.ui?.trackIndex)||1;if(!state.resolveReady){sel.innerHTML='<option value="1">A1</option>';sel.disabled=true;return}const r=await window.hnh.getAudioTracks();if(!r?.ok||!r.tracks?.length){sel.innerHTML='<option value="1">A1</option>';sel.disabled=false;return}state.tracks=r.tracks;sel.innerHTML='';for(const t of r.tracks){const o=document.createElement('option');o.value=t.index;o.textContent=`A${t.index}${t.name&&t.name!==`Audio ${t.index}`?' • '+t.name:''}`;sel.appendChild(o)}sel.value=String(Math.min(previous,r.tracks.length)||1);sel.disabled=false;saveUiSoon()}

function similarQuery(file){const stop=new Set(['sfx','sound','effect','audio','fx','final','mix','stereo','mono']);let words=norm([...(file.folders||[]).slice(-2),file.basename].join(' ')).split(' ').filter(w=>w.length>2&&!/^\d+$/.test(w)&&!stop.has(w));words=[...new Set(words)];return words.slice(0,5).join(' ')}

let waveformQueue=Promise.resolve();
function loadWaveform(file){const token=++state.waveToken;state.waveform={path:file.path,peaks:null,duration:0,loading:true};$('#waveHint').textContent='Đang tạo waveform…';$('#waveHint').style.display='grid';drawWaveform();const work=async()=>{if(token!==state.waveToken)return;try{const cached=await window.hnh.getWaveform(file);if(token!==state.waveToken)return;if(cached){state.waveform={path:file.path,peaks:cached.peaks,duration:cached.duration,loading:false};$('#waveHint').style.display='none';renderTrim();return;}const bytes=await window.hnh.readAudioFile(file.path);if(token!==state.waveToken)return;const raw=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes);const arr=raw.buffer.slice(raw.byteOffset,raw.byteOffset+raw.byteLength);state.audioContext=state.audioContext||new (window.AudioContext||window.webkitAudioContext)();const decoded=await state.audioContext.decodeAudioData(arr);if(token!==state.waveToken)return;const channels=[];for(let c=0;c<decoded.numberOfChannels;c++)channels.push(decoded.getChannelData(c));const bins=900,peaks=new Float32Array(bins);const step=Math.max(1,Math.floor(decoded.length/bins));for(let i=0;i<bins;i++){const start=i*step,end=Math.min(decoded.length,start+step);let peak=0;for(let j=start;j<end;j+=Math.max(1,Math.floor(step/48))){let v=0;for(const ch of channels)v+=Math.abs(ch[j]||0);v/=channels.length;peak=Math.max(peak,v)}peaks[i]=Math.min(1,peak)}await window.hnh.putWaveform(file,{peaks:Array.from(peaks),duration:decoded.duration});if(token!==state.waveToken)return;state.waveform={path:file.path,peaks,duration:decoded.duration,loading:false};$('#waveHint').style.display='none';drawWaveform()}catch(e){if(token!==state.waveToken)return;state.waveform={path:file.path,peaks:null,duration:0,loading:false};$('#waveHint').textContent='Không đọc được waveform';$('#waveHint').style.display='grid';drawWaveform()}};const result=waveformQueue.then(work,work);waveformQueue=result.catch(()=>{});return result;}
function drawWaveform(){const canvas=$('#waveform'),wrap=$('#waveWrap');if(!canvas||!wrap)return;const dpr=window.devicePixelRatio||1,w=Math.max(1,Math.floor(wrap.clientWidth*dpr)),h=Math.max(1,Math.floor(wrap.clientHeight*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const ctx=canvas.getContext('2d');ctx.clearRect(0,0,w,h);const peaks=state.waveform.peaks;if(!peaks)return;const mid=h/2,barW=w/peaks.length;ctx.fillStyle='#aeb9c8';for(let i=0;i<peaks.length;i++){const amp=Math.max(1,peaks[i]*(h*.88));ctx.fillRect(i*barW,mid-amp/2,Math.max(1,barW*.75),amp)}drawTrimOverlay(ctx,w,h);const a=$('#audio');if(Number.isFinite(a.duration)&&a.duration>0){const x=(a.currentTime/a.duration)*w;ctx.fillStyle='#f2f4f7';ctx.fillRect(x,0,Math.max(1,dpr),h)}}
let raf=0;function animateWave(){cancelAnimationFrame(raf);const tick=()=>{previewBoundary();drawWaveform();if(!$('#audio').paused)raf=requestAnimationFrame(tick)};tick()}

async function boot(){const data=await window.hnh.getState();state.mrmMode=data.mrm?.mode==='mrm';state.scanning=!!data.backgroundScan;$('#storageDetail').textContent='Dữ liệu: '+(data.storage?.directory||'không rõ')+((data.storage?.notices||[]).length?'\n'+data.storage.notices.join('\n'):'');state.settings=data.settings;state.settings.ui=state.settings.ui||{};window.HnhAudioOptions?.restore(state.settings.ui.audioOptions);applyPreviewVolume(state.settings.ui.previewVolume??100,state.settings.ui.previewMuted);$('#loopSelection').checked=!!state.settings.ui.loopSelection;setLibraryFiles(data.index.files||[]);renderBridgeStatus(data.resolve);renderLibraries();renderLibraryFilter();$('#showNameTags').checked=state.settings.ui.showNameTags!==false;$('#showFolders').checked=state.settings.ui.showFolders!==false;folderSelection=state.settings.ui.folder||null;$('#autoPreview').checked=true;$('#sortMode').value=state.settings.ui.sortMode||'relevance';$('#extensionFilter').value=state.settings.ui.extension||'all';renderLibraryFilter();showStatus(data.resolve?.ok?`${bridgeMessage(data.resolve)} • ${state.files.length} SFX`:`Chế độ thư viện • ${bridgeMessage(data.resolve)}`);render();renderCollections();if(data.backgroundScan){$('#scanDetail').textContent='Đang đối soát thư viện ở nền; danh sách đã lưu vẫn dùng được.';}else startMetadata();await refreshTracks();if(state.settings.ui.trackIndex && [...$('#trackSelect').options].some(o=>Number(o.value)===Number(state.settings.ui.trackIndex)))$('#trackSelect').value=String(state.settings.ui.trackIndex)}

$('#searchInput').addEventListener('input',()=>{state.mode='search';$$('.chip').forEach(x=>x.classList.remove('active'));clearTimeout(audioSearchTimer);if(state.files.length>10000)audioSearchTimer=setTimeout(render,120);else render()});
$('#clearBtn').onclick=()=>{$('#searchInput').value='';state.mode='search';render();$('#searchInput').focus()};
for(const id of ['sortMode','extensionFilter','libraryFilter','showNameTags','showFolders'])$('#'+id).addEventListener('change',()=>{if(id==='libraryFilter')folderSelection=null;render();saveUiSoon()});$('#autoPreview').addEventListener('change',saveUiSoon);$('#trackSelect').addEventListener('change',saveUiSoon);
$('#settingsBtn').onclick=()=>$('#libraryPanel').classList.remove('hidden');$('#closePanel').onclick=()=>$('#libraryPanel').classList.add('hidden');
$('#addLibrary').onclick=()=>window.HnhLibraryTypes.open();
async function addLibraryWithTypes(types){showStatus('Đang quét thư viện…');const r=await window.hnh.addLibrary(types);if(!r){showStatus('Đã hủy');return}state.settings=r.settings;state.settings.ui=state.settings.ui||{};setLibraryFiles(r.index.files);startMetadata();renderLibraries();renderLibraryFilter();render();showStatus(`Đã lập chỉ mục ${r.scan.count} tài nguyên trong ${(r.scan.ms/1000).toFixed(1)} giây`)}
$('#rescan').onclick=async()=>{attempted.clear();showStatus('Đang quét lại…');const r=await window.hnh.rescan();setLibraryFiles(r.index.files);startMetadata();render();showStatus(`Đã quét ${r.scan.count} tài nguyên`)};
$('#retryResolve').onclick=async()=>{showStatus('Đang kết nối lại Resolve…');const r=await window.hnh.retryResolve();renderBridgeStatus(r);showStatus(r.ok?`${bridgeMessage(r)} • ${state.files.length} SFX`:`Kết nối lỗi: ${bridgeMessage(r)}`);await refreshTracks()};
$$('.chip').forEach(c=>c.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');if(c.dataset.mode){state.mode=c.dataset.mode;$('#searchInput').value=''}else{state.mode='search';$('#searchInput').value=c.dataset.query||''}render()});
$('#playBtn').onclick=()=>{if(!state.selected)return;const a=$('#audio');a.paused?playPreview():a.pause()};$('#audio').onplay=()=>{$('#playBtn').textContent='⏸ Pause';animateWave()};$('#audio').onpause=()=>{$('#playBtn').textContent='▶ Preview';drawWaveform()};$('#audio').ontimeupdate=drawWaveform;
$('#audio').onloadedmetadata=()=>{if(state.selected){const dur=Number.isFinite($('#audio').duration)?$('#audio').duration.toFixed(2)+'s':'';$('#nowMeta').textContent=`${state.selected.relativePath}${dur?' • '+dur:''}`;renderTrim();}};
$('#importBtn').onclick=importSelected;$('#insertBtn').onclick=insertSelected;$('#similarBtn').onclick=()=>{if(!state.selected)return;$('#searchInput').value=similarQuery(state.selected);state.mode='search';$$('.chip').forEach(x=>x.classList.remove('active'));render();$('#searchInput').focus()};$('#revealBtn').onclick=()=>state.selected&&window.hnh.revealInExplorer(state.selected.path);

new ResizeObserver(drawWaveform).observe($('#waveWrap'));
window.addEventListener('keydown',e=>{if(e.target.closest?.('.media-tabs,.header-actions'))return;if(document.body.dataset.mediaTab&&document.body.dataset.mediaTab!=='audio')return;const typing=/^(INPUT|TEXTAREA|SELECT)$/.test(document.activeElement?.tagName);if(typing&&document.activeElement!==$('#searchInput')&&!((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'){e.preventDefault();$('#searchInput').focus();$('#searchInput').select();return}if(e.key==='ArrowDown'){e.preventDefault();moveSelection(1);return}if(e.key==='ArrowUp'){e.preventDefault();moveSelection(-1);return}if(e.key==='Escape'){if(!$('#libraryPanel').classList.contains('hidden')){$('#libraryPanel').classList.add('hidden');return}if($('#searchInput').value){$('#searchInput').value='';state.mode='search';render();return}}if(e.key===' '&&!typing){e.preventDefault();$('#playBtn').click();return}if(e.key==='Enter'&&state.selected){e.preventDefault();if(e.ctrlKey||e.metaKey)importSelected();else if(!typing)insertSelected();}});
// Metadata probing uses one media element and never decodes entire files.
const metadataAudio=new Audio();metadataAudio.preload='metadata';
let metadataRunning=false,metadataRetry=false;const attempted=new Set();
const signature=f=>f.path+'|'+f.size+'|'+f.mtimeMs;
async function startMetadata(){
 if(metadataRunning){metadataRetry=true;return;}metadataRunning=true;
 const pending=[];async function flush(){if(!pending.length)return;const batch=pending.splice(0);try{const accepted=await window.hnh.saveDurations(batch);for(const {file,duration} of batch){const current=state.files.find(f=>signature(f)===signature(file));if(current&&accepted.includes(file.path))current.duration=duration;}render();}catch(e){showStatus('Không lưu được thời lượng: '+e.message);}}
 try{do{metadataRetry=false;
 for(const file of state.files.filter(f=>!Number.isFinite(f.duration)&&!attempted.has(signature(f)))){
  attempted.add(signature(file));$('#metadataStatus').textContent='Đang đọc thời lượng…';
  const duration=await new Promise(resolve=>{let timer;const done=value=>{clearTimeout(timer);metadataAudio.onloadedmetadata=null;metadataAudio.onerror=null;metadataAudio.removeAttribute('src');metadataAudio.load();resolve(value);};metadataAudio.onloadedmetadata=()=>done(metadataAudio.duration);metadataAudio.onerror=()=>done(null);timer=setTimeout(()=>done(null),4000);metadataAudio.src=fileUrl(file.path);});
  if(Number.isFinite(duration)){pending.push({file,duration});if(pending.length>=32)await flush();}
 }
 await flush();}while(metadataRetry);
 }finally{metadataRunning=false;const unknown=state.files.filter(f=>!Number.isFinite(f.duration)).length;$('#metadataStatus').textContent=unknown?unknown+' file chưa rõ thời lượng':'';render();}
}
function renderCollections(){const sel=$('#collectionSelect'),value=sel.value;sel.textContent='';sel.add(new Option('Smart Collections',''));for(const c of state.settings.collections||[])sel.add(new Option(c.name,c.id));sel.value=value;}
function collectionFilters(){return {...HnhQuickFilters.values('audio'),...window.HnhSidebarTags?.values(),folder:folderSelection,query:$('#searchInput').value,extension:$('#extensionFilter').value,library:$('#libraryFilter').value,min:$('#durationMin').value,max:$('#durationMax').value,tag:$('#tagFilter').value,mode:state.mode,sort:$('#sortMode').value};}
$('#saveTags').onclick=async()=>{if(!state.selected)return;const tags={...state.settings.tags,[state.selected.path]:[...new Set($('#tagsInput').value.split(',').map(t=>t.trim()).filter(Boolean))].slice(0,30)};state.settings=await window.hnh.updateSettings({tags});render();showStatus('Đã lưu tags');};
$('#saveCollection').onclick=async()=>{const name=$('#collectionName').value.trim();if(!name){showStatus('Nhập tên bộ lọc để lưu');$('#collectionName').focus();return;}const current=$('#collectionSelect').value,collections=[...(state.settings.collections||[])],entry={id:current||crypto.randomUUID(),name,filters:collectionFilters()},i=collections.findIndex(c=>c.id===current);if(i>=0)collections[i]=entry;else collections.push(entry);state.settings=await window.hnh.updateSettings({collections});renderCollections();$('#collectionSelect').value=entry.id;showStatus('Đã lưu Smart Collection');};
$('#deleteCollection').onclick=async()=>{const id=$('#collectionSelect').value;if(!id)return;state.settings=await window.hnh.updateSettings({collections:(state.settings.collections||[]).filter(c=>c.id!==id)});renderCollections();$('#collectionName').value='';};
$('#collectionSelect').onchange=()=>{const c=(state.settings.collections||[]).find(c=>c.id===$('#collectionSelect').value);if(!c){$('#collectionName').value='';return;}$('#collectionName').value=c.name;const f=c.filters;window.HnhSidebarTags?.restore(f);HnhQuickFilters.restore('audio',f);folderSelection=f.folder||null;for(const [id,key] of [['searchInput','query'],['extensionFilter','extension'],['libraryFilter','library'],['durationMin','min'],['durationMax','max'],['tagFilter','tag'],['sortMode','sort']])$('#'+id).value=f[key]??'';state.mode=f.mode||'search';render();};
for(const id of ['durationMin','durationMax','tagFilter'])$('#'+id).addEventListener('input',render);
window.hnh.onLibraryChanged(({index,scan,settings})=>{if(settings)state.settings={...settings,ui:state.settings.ui||settings.ui||{}};const selected=state.selected;setLibraryFiles(index.files);const current=selected&&state.files.find(f=>f.path===selected.path);if(selected&&!current){$('#audio').pause();state.selected=null;resetTrim();state.waveToken++;state.waveform={peaks:null};$('#nowName').textContent='File đã được xóa khỏi thư viện';$('#tagsInput').disabled=true;$('#saveTags').disabled=true;$('#similarBtn').disabled=true;$('#revealBtn').disabled=true;$('#nowMeta').textContent='';$('#waveHint').textContent='Chọn SFX để xem waveform';$('#waveHint').style.display='grid';drawWaveform();}else if(current&&signature(current)!==signature(selected)){selectFile(current,false);}render();startMetadata();showStatus(scan.warnings?.length?'Một số thư mục không truy cập được; đã giữ dữ liệu cũ.':`Tự cập nhật: +${scan.added}, đổi ${scan.changed}, xóa ${scan.removed}`);});
window.hnh.onResolveChanged(status=>{window.HnhMedia?.resolveChanged();renderBridgeStatus(status);if(status.ok){showStatus(bridgeMessage(status));refreshTracks();}else showStatus((status.retrying===false?'Chưa kết nối Resolve; mở Thư viện để thử lại. ':'Đang tự kết nối Resolve… ')+(status.error||''));});
window.hnh.onScanStatus(info=>{state.scanning=!!info.running;if(!state.files.length)render();const el=$('#scanDetail');if(info.running){el.textContent='Đang cập nhật thư viện ở nền…';return;}if(info.error){el.textContent='Không cập nhật được: '+info.error;showStatus(el.textContent);return;}const warnings=info.scan?.warnings||[];el.textContent=warnings.length?'Không truy cập được một số thư mục (giữ dữ liệu đã lưu):\n'+warnings.join('\n'):'Đã cập nhật '+(info.scan?.count||0)+' tài nguyên.';if(warnings.length)showStatus('Có thư mục không truy cập được; xem chi tiết trong Thư viện.');});
// bỏ tiền tố kỹ thuật của Electron: "Error invoking remote method 'x': Error: ..."
window.addEventListener('unhandledrejection',event=>{showStatus('Lỗi: '+String(event.reason?.message||event.reason).replace(/^Error invoking remote method '[^']*': (?:Error: )?/,''));event.preventDefault();});
$('#clearFolder').onclick=()=>chooseFolder(null);
setupTrimControls();
boot().then(()=>{const restore=()=>{window.HnhBrowserState?.restore();requestAnimationFrame(()=>window.HnhMedia?.restoreLast());};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',restore,{once:true});else restore();});
