(()=>{
 const select=document.getElementById('trackSelect'),box=document.createElement('details');box.id='audioTrackOptions';box.innerHTML='<summary title="Chọn track và tránh chồng lên clip có sẵn">Track thông minh</summary><div class="audio-track-popover"><label><input id="audioSmart" type="checkbox" checked> Tự tìm track đủ chỗ trống</label><label><input id="audioCreate" type="checkbox" checked> Tạo track khi cần</label><label>Track mới <select id="audioPlacement"><option value="top">Trên cùng (A1)</option><option value="bottom">Dưới cùng</option></select></label><p>Thử track đã chọn trước, rồi tìm từ A1 xuống. Bỏ qua track khóa/tắt. Chừa 2 frame ở cuối đoạn. Tạo A1 sẽ đẩy các audio track cũ xuống.</p><p>Áp dụng khi bấm Chèn; kéo thả do Resolve xử lý.</p></div>';select.insertAdjacentElement('afterend',box);
 const el=id=>document.getElementById(id),value=()=>({smart:el('audioSmart').checked,create:el('audioCreate').checked,placement:el('audioPlacement').value});
 function sync(){el('audioCreate').disabled=!el('audioSmart').checked;el('audioPlacement').disabled=!el('audioSmart').checked||!el('audioCreate').checked;box.querySelector('summary').textContent=el('audioSmart').checked?'Track tự động':'Track thủ công';}
 box.addEventListener('change',()=>{sync();saveUiSoon();});box.addEventListener('keydown',e=>e.stopPropagation());document.addEventListener('pointerdown',e=>{if(!box.contains(e.target))box.open=false;});
 window.HnhAudioOptions={value,restore(options={}){options=options||{};el('audioSmart').checked=options.smart!==false;el('audioCreate').checked=options.create!==false;el('audioPlacement').value=options.placement==='bottom'?'bottom':'top';sync();},async afterInsert(r){await refreshTracks();if([...select.options].some(o=>Number(o.value)===r.trackIndex)){select.value=String(r.trackIndex);saveUiSoon();}}};sync();
 const cache=new Map();
 function prepare(file){const key=JSON.stringify([file.path,file.size,file.mtimeMs]),old=cache.get(key);if(old&&(old.pending||old.expires>Date.now()))return old;const entry={pending:true,expires:0};cache.set(key,entry);if(cache.size>50)cache.delete(cache.keys().next().value);Promise.resolve(window.hnh.prepareSfxDrag?.({path:file.path,size:file.size,mtimeMs:file.mtimeMs})).then(r=>{entry.pending=false;if(r?.ok){entry.token=r.token;entry.expires=Date.now()+10000;}else entry.error=r?.error||'Chưa sẵn sàng kéo file.';},e=>{entry.pending=false;entry.error=e.message;});return entry;}
 window.HnhSfxDrag={decorate(row,file){const handle=document.createElement('span');handle.className='sfx-drag-handle';handle.textContent='⠿';handle.draggable=true;handle.tabIndex=0;handle.title='Kéo file SFX gốc vào Resolve (không áp dụng In/Out)';handle.setAttribute('aria-label',handle.title);row.querySelector('.file-heading').prepend(handle);handle.addEventListener('pointerenter',()=>prepare(file));handle.addEventListener('pointerdown',e=>{e.stopPropagation();prepare(file);});handle.addEventListener('click',e=>e.stopPropagation());handle.addEventListener('dblclick',e=>e.stopPropagation());handle.addEventListener('dragstart',e=>{e.preventDefault();e.stopPropagation();const entry=prepare(file);if(!entry.token||entry.expires<=Date.now()){showStatus(entry.error||'Đang chuẩn bị file. Thả chuột và kéo lại sau một chút.');return;}const token=entry.token;entry.token=null;entry.expires=0;window.hnh.startSfxDrag(token);showStatus('Đang kéo file SFX gốc. Thả vào vị trí mong muốn trong Resolve.');});}};
 window.hnh.onSfxDragError?.(message=>showStatus('Kéo thả: '+message));
})();
