(()=>{
 const defaults={video:['Video','01_🎬 VIDEO'],audio:['Audio','02_🎵 AUDIO'],image:['Image','03_🖼 IMAGE'],other:['Khác','04_📦 OTHER'],timeline:['Timeline','05_📋 TIMELINES'],compound:['Compound Clip','06_🧩 COMPOUND']};
 const el=id=>document.getElementById(id),dialog=document.createElement('dialog');dialog.id='autoBinDialog';dialog.setAttribute('aria-labelledby','autoBinTitle');
 dialog.innerHTML='<h2 id="autoBinTitle">Auto Bin</h2><p>Tạo Bin thật trong Media Pool. Chỉ xử lý media trực tiếp; giữ nguyên nội dung Bin con.</p><label>Phạm vi <select id="autoBinScope"><option value="root">Master — media trực tiếp</option><option value="current">Bin hiện tại — media trực tiếp</option></select></label><p>Tùy chỉnh tên hoặc chọn Bin có sẵn trước khi quét.</p><div id="autoBinGroups"></div><button id="autoBinReset" class="secondary">Khôi phục tên mặc định</button><p class="hint">Bỏ tích để giữ nguyên nhóm đó. Bin có sẵn được chọn trong phạm vi đang quét. Timeline được xác định bằng ID project; Compound chỉ nhận khi Resolve trả đúng loại Compound Clip. Không đoán theo tên file.</p><button id="autoBinScan">Quét / Làm mới xem trước</button><div id="autoBinSummary"></div><details><summary>Danh sách xem trước</summary><div id="autoBinRows"></div></details><details id="autoBinRecovery" hidden><summary>Đối chiếu lần Auto Bin trước</summary><div id="autoBinRecoveryRows"></div></details><p id="autoBinMessage" role="status"></p><div class="auto-bin-actions"><button id="autoBinClose" class="secondary">Đóng</button><button id="autoBinUndo" class="secondary">Hoàn tác lần gần nhất</button><button id="autoBinArchive" class="secondary" hidden>Kết thúc lần cũ</button><button id="autoBinApply" disabled>Sắp xếp</button></div>';
 document.body.append(dialog);let busy=false,token=null,archiveToken=null,confirmation=null,prefs={};try{prefs=JSON.parse(localStorage.getItem('hnh-auto-bin-groups')||'{}')||{};}catch{}
 const groups={};for(const [kind,[label,name]] of Object.entries(defaults)){const row=document.createElement('div');row.className='auto-bin-group';const title=document.createElement('label'),enabled=document.createElement('input');enabled.type='checkbox';enabled.id='autoBinEnabled-'+kind;enabled.checked=typeof prefs[kind]?.enabled==='boolean'?prefs[kind].enabled:!['timeline','compound'].includes(kind);title.append(enabled,document.createTextNode(' '+label));const input=document.createElement('input');input.id='autoBinName-'+kind;input.maxLength=100;input.value=prefs[kind]?.name||name;input.setAttribute('aria-label','Tên Bin cho '+label);const select=document.createElement('select');select.id='autoBinTarget-'+kind;select.setAttribute('aria-label','Bin có sẵn cho '+label);select.add(new Option('Theo tên / tạo Bin mới',''));row.append(title,input,select);el('autoBinGroups').append(row);groups[kind]={enabled,input,select};enabled.onchange=input.oninput=()=>changed();select.onchange=()=>{if(select.value)input.value=select.selectedOptions[0].textContent;changed();};}
 el('autoBinReset').onclick=()=>{for(const [kind,g] of Object.entries(groups)){g.enabled.checked=!['timeline','compound'].includes(kind);g.input.value=defaults[kind][1];g.select.value='';}changed();};
 function controls(){for(const id of ['autoBinReset','autoBinScan','autoBinScope','autoBinUndo','autoBinClose','autoBinArchive'])el(id).disabled=busy;el('autoBinApply').disabled=busy||!token;el('autoBinArchive').hidden=!archiveToken;for(const g of Object.values(groups)){g.enabled.disabled=busy;g.input.disabled=busy||!g.enabled.checked||!!g.select.value;g.select.disabled=busy||!g.enabled.checked;}}
 function invalidate(){token=null;archiveToken=null;confirmation=null;el('autoBinUndo').textContent='Hoàn tác lần gần nhất';el('autoBinArchive').textContent='Kết thúc lần cũ';controls();}
 function message(text){el('autoBinMessage').textContent=text;}
 function request(){return {scope:el('autoBinScope').value,groups:Object.fromEntries(Object.entries(groups).map(([kind,g])=>[kind,{enabled:g.enabled.checked,name:g.input.value,targetId:g.select.value||null}]))};}
 function changed(){invalidate();el('autoBinSummary').replaceChildren();el('autoBinRows').replaceChildren();el('autoBinRecovery').hidden=true;message('Đã thay đổi cấu hình. Quét lại để cập nhật xem trước.');try{localStorage.setItem('hnh-auto-bin-groups',JSON.stringify(Object.fromEntries(Object.entries(groups).map(([k,g])=>[k,{enabled:g.enabled.checked,name:g.input.value}]))));}catch{}}
 async function run(fn){if(busy)return;busy=true;controls();try{const result=await fn();if(!result.ok)throw Error(result.error||'Không thực hiện được');return result;}catch(e){message(e.message);}finally{busy=false;controls();}}
 function textRow(host,text){const p=document.createElement('p');p.textContent=text;host.append(p);}
 async function loadFolders(){if(!window.hnh.autoBinFolders)return;const r=await run(()=>window.hnh.autoBinFolders(el('autoBinScope').value));if(r)for(const g of Object.values(groups)){const chosen=g.select.value;g.select.replaceChildren(new Option('Theo tên / tạo Bin mới',''));for(const f of r.children)g.select.add(new Option(f.name,f.id));g.select.value=chosen;}controls();}
 el('autoBinOpen').onclick=()=>{if(!dialog.open){invalidate();dialog.showModal();loadFolders();}};el('autoBinClose').onclick=()=>dialog.close();dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dialog.addEventListener('keydown',e=>e.stopPropagation());
 el('autoBinScope').onchange=()=>{for(const g of Object.values(groups))g.select.replaceChildren(new Option('Theo tên / tạo Bin mới',''));changed();loadFolders();};
 el('autoBinScan').onclick=async()=>{invalidate();message('Đang quét và đối chiếu Media Pool…');el('autoBinSummary').replaceChildren();el('autoBinRows').replaceChildren();el('autoBinRecovery').hidden=true;const r=await run(()=>window.hnh.autoBinScan(request()));if(!r)return;token=r.recoveryNeeded?null:r.token;archiveToken=r.archiveToken||null;
  for(const g of Object.values(groups)){const chosen=g.select.value;g.select.replaceChildren(new Option('Theo tên / tạo Bin mới',''));for(const f of r.children||[])g.select.add(new Option(f.name,f.id));g.select.value=chosen;}
  textRow(el('autoBinSummary'),'Bin nguồn: '+r.sourceName+' • '+r.rows.length+' mục');for(const [kind,[label]] of Object.entries(defaults))textRow(el('autoBinSummary'),label+': '+(r.counts[kind]||0)+(r.destinations?.[kind]?' → '+r.destinations[kind]:''));textRow(el('autoBinSummary'),'Giữ nguyên / bỏ qua: '+r.counts.skip);if(!r.rows.some(row=>row.kind))token=null;
  for(const row of r.rows.slice(0,200))textRow(el('autoBinRows'),row.name+' → '+(r.destinations?.[row.kind]||'Giữ nguyên')+' • '+row.reason);if(r.rows.length>200)textRow(el('autoBinRows'),'Hiện 200 mục đầu; số lượng tính toàn bộ phạm vi.');
  el('autoBinRecoveryRows').replaceChildren();for(const row of r.recoveryRows||[])textRow(el('autoBinRecoveryRows'),row.name+' • '+row.reason);el('autoBinRecovery').hidden=!(r.recoveryRows?.length);el('autoBinRecovery').open=!!r.recoveryNeeded;
  message(r.recoveryNeeded?'Có mục chưa đối chiếu xong. Xem danh sách rồi Hoàn tác, hoặc Kết thúc lần cũ nếu muốn giữ nguyên Media Pool hiện tại.':'Chưa di chuyển media. Kiểm tra tên Bin đích rồi bấm Sắp xếp. Hoàn tác chỉ giữ lần gần nhất.');controls();};
 el('autoBinApply').onclick=async()=>{const selected=token;invalidate();message('Đang sắp xếp…');const r=await run(()=>window.hnh.autoBinApply(selected));if(r)message((r.failed?r.message+' • '+(r.recovery?.remaining?'Còn '+r.recovery.remaining+' mục cần kiểm tra.':'Đã phục hồi media đã chuyển.'):(r.message||'Hoàn tất'))+' Quét lại để tiếp tục.');};
 el('autoBinUndo').onclick=async()=>{if(confirmation!=='undo'){confirmation='undo';el('autoBinUndo').textContent='Xác nhận hoàn tác';message('Đưa media về Bin gốc nếu còn ở Bin đích. Media đã về gốc được ghi nhận tự động; media ở nơi khác được giữ nguyên.');return;}invalidate();message('Đang đối chiếu và hoàn tác…');const r=await run(()=>window.hnh.autoBinUndo());if(r)message(r.message+(r.conflicts?.length?'\n'+r.conflicts.join('\n'):'')+' Quét lại để tiếp tục.');};
 el('autoBinArchive').onclick=async()=>{if(confirmation!=='archive'){confirmation='archive';el('autoBinArchive').textContent='Xác nhận giữ hiện trạng';message('Giữ nguyên mọi media/Bin, lưu trữ nhật ký cũ và kết thúc khả năng hoàn tác lần đó trong plugin. Chỉ xác nhận sau khi xem các mục chưa giải quyết.');return;}const saved=archiveToken;invalidate();const r=await run(()=>window.hnh.autoBinArchive(saved));if(r)message(r.message);};
 window.hnh.onAutoBinProgress?.(r=>{if(busy)message((r.phase==='scan'?'Đang quét: ':'Đang chuyển: ')+r.done+'/'+r.total);});controls();
})();
