let backupPlan=null,backupOverrides={},backupPage=0,backupBusy=false;
const backupButtons=['exportBackup','openBackup','openPending','analyzeBackup','applyBackup','undoBackup','confirmUndo','chooseSuggested'];
function backupLock(busy){backupBusy=busy;document.querySelector('main').inert=busy;document.querySelector('#mediaWorkspace').inert=busy;for(const el of document.querySelectorAll('#addLibrary,#rescan,#libraries button'))el.disabled=busy;for(const id of backupButtons)$('#'+id).disabled=busy||(id==='applyBackup'&&!backupPlan);$('#cancelBackup').hidden=!busy;for(const el of document.querySelectorAll('#backupRoots input,#backupRoots button,#backupReview select'))el.disabled=busy;}
async function backupRun(fn){if(backupBusy)return;backupLock(true);try{clearTimeout(uiSaveTimer);await window.hnh.updateSettings({ui:currentUi()});return await fn();}catch(e){$('#backupProgress').textContent='Lỗi: '+(e.message||e);}finally{backupLock(false);}}
function backupInvalidate(){backupPlan=null;backupOverrides={};$('#applyBackup').disabled=true;$('#backupReview').textContent='';$('#backupPlanSummary').textContent='';}
function backupShow(data){if(!data)return;backupInvalidate();$('#backupImport').hidden=false;$('#backupSummary').textContent=`${data.files} mục • ${data.waveforms} waveform`+(data.relink?' • Nối từ dữ liệu hiện tại: chọn thư mục mới rồi Đối chiếu file. Chưa đổi dữ liệu.':'');const host=$('#backupRoots');host.textContent='';for(const root of data.roots){const row=document.createElement('div');row.className='backup-root';const label=document.createElement('div');label.textContent='Thư mục cũ: '+root;const input=document.createElement('input');input.value=root;input.dataset.sourceRoot=root;input.setAttribute('aria-label','Thư mục đích cho '+root);input.oninput=backupInvalidate;const button=document.createElement('button');button.className='secondary';button.textContent='Chọn thư mục mới';button.onclick=()=>backupRun(async()=>{const selected=await window.hnh.backupFolder();if(selected){input.value=selected;backupInvalidate();}});row.append(label,input,button);host.appendChild(row);}}
function backupReview(){const host=$('#backupReview');host.textContent='';const rows=backupPlan?.rows||[],pages=Math.max(1,Math.ceil(rows.length/50));backupPage=Math.max(0,Math.min(backupPage,pages-1));for(const row of rows.slice(backupPage*50,(backupPage+1)*50)){const el=document.createElement('div');el.className='backup-review-row';const name=document.createElement('strong');name.textContent=(row.favorite?'★ ':'')+row.name;const info=document.createElement('div');info.textContent=row.originalPath+(row.tags.length?' • '+row.tags.join(', '):'');const select=document.createElement('select');select.setAttribute('aria-label','Ghép file '+row.name);select.add(new Option(row.status==='missing'?'Chưa tìm thấy — để nối lại sau':'Cần xác nhận — để nối lại sau',''));for(const f of row.candidates)select.add(new Option(f.path+' • '+f.size+' bytes',f.path));select.value=backupOverrides[row.id]||'';select.onchange=()=>{backupOverrides[row.id]=select.value;};el.append(name,info,select);host.appendChild(el);}$('#backupPage').textContent=`${rows.length?backupPage+1:0} / ${rows.length?pages:0}`;$('#backupPrev').disabled=backupPage===0;$('#backupNext').disabled=backupPage>=pages-1;}
function backupAdopt(data){state.settings=data.settings;state.settings.ui=state.settings.ui||{};setLibraryFiles(data.index.files||[]);folderSelection=null;folderCacheFiles=null;queryCache.raw=null;$('#libraryFilter').value='all';renderLibraries();renderLibraryFilter();$('#showNameTags').checked=state.settings.ui.showNameTags!==false;$('#showFolders').checked=state.settings.ui.showFolders!==false;$('#autoPreview').checked=true;$('#sortMode').value=state.settings.ui.sortMode||'relevance';$('#extensionFilter').value=state.settings.ui.extension||'all';applyPreviewVolume(state.settings.ui.previewVolume??100,state.settings.ui.previewMuted);$('#loopSelection').checked=!!state.settings.ui.loopSelection;renderCollections();if(state.selected){const f=state.files.find(f=>f.path===state.selected.path);if(f){state.selected=f;$('#tagsInput').value=(state.settings.tags?.[f.path]||[]).join(', ');}else{$('#audio').pause();state.selected=null;resetTrim();$('#tagsInput').disabled=true;$('#saveTags').disabled=true;}}render();startMetadata();}
$('#exportBackup').onclick=()=>backupRun(async()=>{const r=await window.hnh.exportBackup({waveforms:$('#exportWaves').checked,history:$('#exportHistory').checked});$('#backupProgress').textContent=r?`Đã lưu ${r.files} mục, ${r.waveforms} waveform.\n${r.path}`+(r.warningCount?`\n${r.warningCount} file không đọc được nội dung; tags/Favorites vẫn được lưu.\n${r.warnings.join('\n')}`:''):'Đã hủy chọn nơi lưu.';});
$('#openBackup').onclick=()=>backupRun(async()=>backupShow(await window.hnh.openBackup()));
$('#openPending').onclick=()=>backupRun(async()=>backupShow(await window.hnh.openPending()));
$('#analyzeBackup').onclick=()=>backupRun(async()=>{backupInvalidate();const mappings=Object.fromEntries([...document.querySelectorAll('#backupRoots input')].map(el=>[el.dataset.sourceRoot,el.value.trim()]));const plan=await window.hnh.prepareBackup(mappings);backupPlan=plan;backupPage=0;$('#backupPlanSummary').textContent=`${plan.exact} khớp nội dung • ${plan.review} cần xác nhận • ${plan.missing} chưa tìm thấy`;$('#backupWarnings').textContent=plan.warnings.join('\n');backupReview();});
$('#applyBackup').onclick=()=>backupRun(async()=>{if(!backupPlan)return;clearTimeout(uiSaveTimer);await window.hnh.updateSettings({ui:currentUi()});const r=await window.hnh.applyBackup(backupPlan.token,backupOverrides,{waveforms:$('#restoreWaves').checked,collections:$('#restoreCollections').checked,ui:$('#restoreUI').checked,history:$('#restoreHistory').checked});backupAdopt(r);backupInvalidate();$('#backupProgress').textContent=`Đã gộp dữ liệu cho ${r.matched} file; khôi phục ${r.waveforms} waveform.\nCòn ${r.pending} mục chờ nối lại.\nBản sao trước nhập: ${r.backup}`;});
$('#cancelBackup').onclick=()=>window.hnh.cancelBackup();$('#backupPrev').onclick=()=>{backupPage--;backupReview();};$('#backupNext').onclick=()=>{backupPage++;backupReview();};
$('#undoBackup').onclick=()=>{$('#confirmUndo').hidden=false;};$('#confirmUndo').onclick=()=>backupRun(async()=>{clearTimeout(uiSaveTimer);const r=await window.hnh.undoBackup();backupAdopt(r);backupInvalidate();$('#confirmUndo').hidden=true;$('#backupProgress').textContent='Đã khôi phục trạng thái trước lần nhập. Bản sao trạng thái vừa thay thế: '+r.backup;});
window.hnh.onBackupProgress(data=>{if(data.stage==='idle')return;$('#backupProgress').textContent=data.stage+(data.total?` • ${data.current}/${data.total}`:'');});
document.querySelector('.backup-section').addEventListener('keydown',e=>{if(['Enter',' ','ArrowUp','ArrowDown'].includes(e.key))e.stopPropagation();});

window.HnhRelink={open:root=>backupRun(async()=>{backupShow(await window.hnh.relinkLibrary(root));document.querySelector('.backup-section').scrollIntoView({block:'start'});$('#backupProgress').textContent='Chọn thư mục mới để đối chiếu. Khớp nội dung được tự nhận; chỉ khớp vị trí/kích thước vẫn cần bạn xác nhận. Thư mục và metadata cũ được giữ để đối chiếu; sau khi kiểm tra xong có thể xóa thư viện cũ khỏi danh sách.';})};
$('#chooseSuggested').onclick=()=>{if(backupBusy||!backupPlan)return;let count=0;for(const row of backupPlan.rows){if(row.suggested){backupOverrides[row.id]=row.suggested;count++;}}backupReview();$('#backupProgress').textContent='Đã chọn '+count+' mục khớp đường dẫn tương đối và kích thước để bạn áp dụng. Đây chưa phải xác minh nội dung; waveform chỉ chuyển khi hash khớp. Chưa ghi thay đổi.';};
