(() => {
 const el=id=>document.getElementById(id),make=(tag,cls)=>{const n=document.createElement(tag);if(cls)n.className=cls;return n;};
 const header=document.querySelector('header'),nav=document.querySelector('.media-tabs'),actions=document.querySelector('.header-actions');
 header.insertBefore(nav,actions);actions.prepend(el('updateShortcut'),el('helpBtn'));
 const search=document.querySelector('.searchbar');search.append(el('batchToggle'));
 const panel=make('section','finder-filters');panel.id='audioFilterPanel';panel.setAttribute('aria-label','Bộ lọc SFX');const main=document.querySelector('main');
 const bars=[...main.querySelectorAll(':scope > .toolbar')];const info=make('div','compact-info');info.append(el('resultCount'));const active=make('span');active.id='activeFilterSummary';info.append(active);main.insertBefore(info,document.querySelector('.folder-toolbar'));
 const first=make('div','finder-filter-row'),second=make('div','finder-filter-row');const date=main.querySelector(':scope > .quick-date-row');first.append(date.querySelector('label'),el('extensionFilter'),el('libraryFilter'),el('sortMode'));second.append(bars[1].querySelector('label'),el('tagFilter'),el('collectionSelect'));
 const options=make('details','finder-options');const optionTitle=make('summary');optionTitle.textContent='Tùy chọn';const optionBody=make('div','finder-option-body');optionBody.append(...bars[0].querySelectorAll('label'),el('collectionName'),el('saveCollection'),el('deleteCollection'),el('audioQuickReset'),el('audioTagHint'),el('metadataStatus'));options.append(optionTitle,optionBody);second.append(options);panel.append(first,second,el('audioAddedRange'));date.remove();search.after(panel);bars.forEach(b=>b.hidden=true);
 const footer=document.querySelector('footer'),preview=document.querySelector('.preview-block'),tools=document.querySelector('.footer-tools'),now=document.querySelector('.now-playing');
 const tags=make('details','compact-tags');tags.id='tagsEditor';const tagSummary=make('summary');tagSummary.textContent='Sửa tags';const tagBody=make('div','tag-editor-body');tagBody.append(el('tagsInput'),el('saveTags'));tags.append(tagSummary,tagBody);now.append(tags);bars[2].classList.add('collection-name-row');
 const extra=make('details','compact-menu');extra.id='fileMenu';const extraSummary=make('summary');extraSummary.textContent='⋯';extraSummary.setAttribute('aria-label','Thao tác với file');const extraBody=make('div','menu-content');extraBody.append(el('similarBtn'),el('revealBtn'));extra.append(extraSummary,extraBody);extraBody.addEventListener('click',()=>extra.open=false);now.append(extra);
 const bottom=make('div','preview-bottom');bottom.append(document.querySelector('.trim-controls'),tools);footer.append(bottom);const oldCompact=tools.querySelector('.footer-actions.compact');oldCompact?.remove();
 const mode=el('timelineRangeControls'),volume=document.querySelector('.volume-controls');tools.prepend(volume,mode);preview.append(el('timelineRangeBox'));
 const handle=make('div','preview-resizer');handle.tabIndex=0;handle.role='separator';handle.setAttribute('aria-orientation','horizontal');handle.setAttribute('aria-label','Điều chỉnh chiều cao waveform');footer.prepend(handle);
 let drag=null;function height(n){const value=Math.max(36,Math.min(150,n));footer.style.setProperty('--wave-height',value+'px');handle.setAttribute('aria-valuenow',value);drawWaveform();}handle.setAttribute('aria-valuemin','36');handle.setAttribute('aria-valuemax','150');height(40);
 handle.onpointerdown=e=>{drag={y:e.clientY,h:el('waveWrap').getBoundingClientRect().height};handle.setPointerCapture(e.pointerId);e.preventDefault();};handle.onpointermove=e=>{if(drag)height(drag.h+drag.y-e.clientY);};handle.onpointerup=handle.onpointercancel=()=>drag=null;handle.onkeydown=e=>{if(['ArrowUp','ArrowDown','Home'].includes(e.key)){e.preventDefault();e.stopPropagation();height(e.key==='Home'?40:el('waveWrap').getBoundingClientRect().height+(e.key==='ArrowUp'?8:-8));}};
 function summaryText(){const parts=[];const select=(id,defaultValue)=>{const node=el(id);if(node.value!==defaultValue&&node.value)parts.push(node.selectedOptions[0]?.textContent||node.value);};select('audioAddedMode','all');if(el('audioAddedMode').value==='custom')parts.push([el('audioAddedFrom').value,el('audioAddedTo').value].join(' → '));select('extensionFilter','all');select('libraryFilter','all');select('tagFilter','');if(el('durationMin').value||el('durationMax').value)parts.push(`${el('durationMin').value||'0'}–${el('durationMax').value||'∞'}s`);select('sortMode','relevance');active.textContent=parts.length?parts.join(' • '):'Không có bộ lọc nâng cao';active.title=active.textContent;}
 panel.addEventListener('input',()=>queueMicrotask(summaryText));panel.addEventListener('change',()=>queueMicrotask(summaryText));panel.addEventListener('click',()=>setTimeout(summaryText,0));new MutationObserver(summaryText).observe(el('resultCount'),{childList:true,subtree:true,characterData:true});summaryText();
 for(const node of [panel,tags,extra])node.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Escape'){if(node===panel){options.open=false;}else{node.open=false;node.querySelector('summary').focus();}}});
 document.addEventListener('pointerdown',e=>{for(const d of [options,extra,tags])if(d.open&&!d.contains(e.target))d.open=false;});
 document.querySelectorAll('[data-media-tab]').forEach(b=>b.addEventListener('click',()=>{options.open=false;tags.open=false;if(b.dataset.mediaTab==='audio')search.append(el('batchToggle'));else document.querySelector('.media-toolbar').append(el('batchToggle'));}));
})();
