(() => {
 const el=id=>document.getElementById(id),PAGE=48;
 let tab='audio',selected=null,page=0,filtered=[],token=0,busy=false,trackToken=0,renderToken=0,observer=null;
 const controlIds=['mediaSearch','mediaFolder','mediaMode','mediaAddedMode','mediaAddedFrom','mediaAddedTo','mediaTagFilter','mediaView','mediaThumbSize','mediaSort'];
 let saved={};try{saved=JSON.parse(localStorage.getItem('hnh-media-browser-v1')||'{}')||{};}catch{}if(typeof saved!=='object'||Array.isArray(saved))saved={};let direction='asc',restoring=false,audioScroll=0;
 function remember(){if(tab==='audio'||restoring)return;const controls={};for(const id of controlIds)controls[id]=el(id).value;saved[tab]={controls,page,scroll:el('mediaGrid').scrollTop,selected:selected?.path||null,direction,tagFilters:window.HnhUnifiedTags?.values(tab)};try{localStorage.setItem('hnh-media-browser-v1',JSON.stringify(saved));}catch{}}
 function compareFiles(a,b){const key=el('mediaSort').value,dir=direction==='desc'?-1:1;let x,y;if(['added','modified','duration'].includes(key)){const prop={added:'addedAt',modified:'mtimeMs',duration:'duration'}[key];x=a[prop];y=b[prop];const valid=v=>Number.isFinite(v)&&v>0;if(valid(x)!==valid(y))return valid(x)?-1:1;if(!valid(x))return nameCompare(a.filename,b.filename)||a.path.localeCompare(b.path);return (x-y)*dir||nameCompare(a.filename,b.filename)||a.path.localeCompare(b.path);}x=key==='type'?a.extension:a.filename;y=key==='type'?b.extension:b.filename;return nameCompare(String(x||''),String(y||''))*dir||a.path.localeCompare(b.path);}
 let thumbnailRunning=0,pumpCurrent=()=>{},scheduleThumbnails=()=>{},thumbnailTimer=null,activeThumbnail=null,thumbBytes=0,searchTimer;const nameCompare=new Intl.Collator(undefined,{numeric:true,sensitivity:'base'}).compare;const thumbs=new Map();
 const canonical=s=>String(s||'').replace(/\\/g,'/').toLowerCase(),signature=f=>f.path+'|'+f.size+'|'+f.mtimeMs;
 const status=text=>{el('mediaActionStatus').textContent=text;};
 function options(){const kind=tab,files=(state.mediaFiles||[]).filter(f=>HnhMediaTypes.fileKind(f)===kind),folders=new Map();for(const f of files){const parts=String(f.relativePath||f.filename).replace(/\\/g,'/').split('/');parts.pop();for(let i=0;i<=parts.length;i++){const folder=parts.slice(0,i).join('/'),key=JSON.stringify([f.root,folder]);folders.set(key,{root:f.root,folder});}}const select=el('mediaFolder'),before=select.value;select.replaceChildren(new Option('Mọi thư mục',''));for(const [key,f] of [...folders].sort((a,b)=>a[0].localeCompare(b[0]))){select.add(new Option(f.folder?'　'+f.folder:f.root,key));}select.value=folders.has(before)?before:'';}
 function matchesFolder(f){if(!el('mediaFolder').value)return true;const [root,folder]=JSON.parse(el('mediaFolder').value),rel=canonical(f.relativePath);return canonical(f.root)===canonical(root)&&(!folder||rel.startsWith(canonical(folder)+'/'));}
 function buttons(){const ready=!!selected&&!busy;for(const id of ['mediaSaveTags','mediaFavorite','mediaTags','mediaReveal','mediaImport'])el(id).disabled=!ready;el('mediaAudioTrack').disabled=busy||!el('mediaIncludeAudio').checked;const auto=tab==='video'&&el('mediaIncludeAudio').checked&&el('mediaAutoTracks').checked;el('mediaInsert').disabled=!ready||(!auto&&(!el('mediaTrack').value||(tab==='video'&&el('mediaIncludeAudio').checked&&!el('mediaAudioTrack').value)));el('mediaCreateTracks').disabled=busy||!auto;el('mediaRefreshTracks').disabled=busy;for(const id of ['mediaMarkIn','mediaMarkOut','mediaUseRange'])el(id).disabled=!ready||!Number.isFinite(el('mediaVideo').duration);}
 function clearPreview(){token++;selected=null;window.HnhUnifiedTags?.refresh();el('mediaVideo').pause();el('mediaVideo').removeAttribute('src');el('mediaVideo').load();el('mediaImage').removeAttribute('src');el('mediaImage').hidden=true;el('mediaVideo').hidden=true;el('mediaEmpty').hidden=false;el('mediaEmpty').textContent='Chọn file để xem thử';el('mediaName').textContent='Chọn tài nguyên';el('mediaPreviewStatus').textContent='';el('mediaTags').value='';el('mediaUseRange').checked=false;buttons();}
 function render(resetScroll=false){clearTimeout(searchTimer);searchTimer=null;if(tab==='audio')return;stopThumbnails();window.HnhUnifiedTags?.refresh();HnhQuickFilters.tags('media',state.mediaFiles||[],state.settings.tags||{},tab);observer?.disconnect();const generation=++renderToken;const quickMatch=HnhQuickFilters.matcher('media'),favorites=new Set(state.settings.favorites),recent=new Set(state.settings.recent);const query=HnhSearch.compile(el('mediaSearch').value),mode=el('mediaMode').value;filtered=(state.mediaFiles||[]).filter(f=>HnhMediaTypes.fileKind(f)===tab&&(!window.HnhUnifiedTags||HnhUnifiedTags.matches(tab,f))&&quickMatch(f,state.settings.tags?.[f.path]||[])&&matchesFolder(f)&&(mode!=='favorites'||favorites.has(f.path))&&(mode!=='recent'||recent.has(f.path))).map(f=>({f,score:HnhSearch.score(f,query,state.settings.tags?.[f.path]||[])})).filter(x=>x.score>0).sort((a,b)=>compareFiles(a.f,b.f)).map(x=>x.f);
  page=Math.min(page,Math.max(0,Math.ceil(filtered.length/PAGE)-1));window.HnhBatch?.visible(tab,filtered.slice(page*PAGE,(page+1)*PAGE),filtered);el('mediaCount').textContent=filtered.length+(tab==='image'?' ảnh':' video');el('mediaPage').textContent=(filtered.length?page+1:0)+' / '+Math.ceil(filtered.length/PAGE);el('mediaPrev').disabled=page===0;el('mediaNext').disabled=(page+1)*PAGE>=filtered.length;
  const grid=el('mediaGrid');grid.dataset.view=el('mediaView').value;grid.style.setProperty('--thumb-size',el('mediaThumbSize').value+'px');el('mediaSizeLabel').hidden=el('mediaView').value!=='thumbnail';el('mediaDirection').textContent=direction==='asc'?'↑ Tăng dần':'↓ Giảm dần';const scroll=resetScroll?0:grid.scrollTop,focusedPath=grid.contains(document.activeElement)?document.activeElement.dataset.path:null;grid.replaceChildren();if(!filtered.length){const empty=document.createElement('p');empty.className='media-empty';empty.textContent='Chưa có kết quả. Thêm folder trong Thư viện hoặc bỏ bộ lọc.';grid.append(empty);remember();return;}
  if(el('mediaView').value==='details'){const head=document.createElement('div');head.className='media-detail-head';for(const [key,label] of [['name','Tên'],['type','Loại'],['duration','Thời lượng'],['added','Ngày thêm'],['modified','Ngày sửa']]){const b=document.createElement('button');b.textContent=label+(el('mediaSort').value===key?(direction==='asc'?' ↑':' ↓'):'');b.onclick=()=>{direction=el('mediaSort').value===key&&direction==='asc'?'desc':'asc';el('mediaSort').value=key;page=0;render(true);};head.append(b);}grid.append(head);}
  for(const file of filtered.slice(page*PAGE,(page+1)*PAGE)){const card=document.createElement('button');card.className='media-card'+(selected?.path===file.path?' selected':'');card.type='button';card.dataset.path=file.path;card.title=file.path+' • '+HnhDates.label(file.addedAt);card.setAttribute('aria-label',file.filename);const picture=document.createElement('div');picture.className='media-card-picture';const placeholder=document.createElement('span');placeholder.textContent=tab==='image'?'▧':'▶';const image=document.createElement('img');image.hidden=true;image.alt='';picture.append(placeholder,image);if(tab==='video'){const duration=document.createElement('span');duration.className='video-duration';duration.textContent=HnhDuration.format(file.duration,true);duration.title=HnhDuration.title(file.duration);picture.append(duration);}const title=document.createElement('strong');title.textContent=(state.settings.favorites.includes(file.path)?'★ ':'')+file.filename;const desc=document.createElement('small');desc.textContent=(state.settings.tags?.[file.path]||[]).join(' • ')||file.relativePath;const added=document.createElement('small');added.textContent=HnhDates.valid(file.addedAt)?'Thêm: '+new Date(file.addedAt).toLocaleDateString('vi-VN'):'Ngày thêm: chưa rõ';card.append(picture,title,desc,added);card.onclick=()=>select(file);card._thumbnail={image,file,placeholder};const cell=document.createElement('div');cell.className='media-cell';cell.append(card);window.HnhBatch?.decorate(cell,file);grid.append(cell);if(el('mediaView').value!=='thumbnail'){const metrics=document.createElement('span');metrics.className='media-row-metrics';for(const value of [String(file.extension||'').toUpperCase(),tab==='video'?HnhDuration.format(file.duration,true):'—',HnhDates.valid(file.addedAt)?new Date(file.addedAt).toLocaleDateString('vi-VN'):'—',HnhDates.valid(file.mtimeMs)?new Date(file.mtimeMs).toLocaleDateString('vi-VN'):'—']){const item=document.createElement('span');item.textContent=value;metrics.append(item);}card.append(metrics);}}resumeThumbnails();grid.scrollTop=scroll;if(focusedPath){const focus=[...grid.querySelectorAll(".media-card")].find(c=>c.dataset.path===focusedPath);focus?.focus({preventScroll:true});}remember();
 }
 function stopThumbnails(){clearTimeout(thumbnailTimer);thumbnailTimer=null;pumpCurrent=()=>{};scheduleThumbnails=()=>{};observer?.disconnect();if(activeThumbnail)activeThumbnail.cancelled=true;window.hnh.cancelMediaThumbnails?.();}
 function resumeThumbnails(){
  clearTimeout(thumbnailTimer);observer?.disconnect();
  const generation=renderToken,grid=el('mediaGrid'),attempted=new Set();let idleAt=performance.now()+180;
  const current=()=>generation===renderToken&&tab!=='audio'&&el('mediaView').value==='thumbnail';
  function visible(card){if(!card?.isConnected||!current())return false;const a=card.getBoundingClientRect(),b=grid.getBoundingClientRect();return a.width>0&&a.height>0&&a.bottom>b.top&&a.top<b.bottom&&a.right>b.left&&a.left<b.right;}
  function show(item,data){if(!data)return;if(!thumbs.has(signature(item.file))){thumbs.set(signature(item.file),data);thumbBytes+=data.length*2;}while(thumbBytes>16*1024*1024||thumbs.size>80){const first=thumbs.keys().next().value;thumbBytes-=thumbs.get(first).length*2;thumbs.delete(first);}if(item.image.isConnected){item.image.src=data;item.image.hidden=false;item.placeholder.hidden=true;}}
  function pump(){clearTimeout(thumbnailTimer);thumbnailTimer=null;if(!current())return;
   const cards=[...grid.querySelectorAll('.media-card')].filter(card=>card._thumbnail?.image.hidden&&visible(card));
   // Memory hits require no disk reads, including while scrolling.
   for(const card of cards){const data=thumbs.get(signature(card._thumbnail.file));if(data)show(card._thumbnail,data);}
   if(performance.now()<idleAt){thumbnailTimer=setTimeout(pump,Math.ceil(idleAt-performance.now()));return;}
   if(thumbnailRunning)return;
   const card=cards.find(card=>card._thumbnail.image.hidden&&!attempted.has(card));if(!card)return;
   attempted.add(card);const item=card._thumbnail,request={card,cancelled:false};activeThumbnail=request;thumbnailRunning++;
   Promise.resolve().then(()=>current()&&!request.cancelled?window.hnh.mediaThumbnail(item.file):null).then(data=>{if(current()&&!request.cancelled)show(item,data);}).catch(()=>{}).finally(()=>{if(request.cancelled)attempted.delete(card);if(activeThumbnail===request)activeThumbnail=null;thumbnailRunning--;pumpCurrent();});
  }
  scheduleThumbnails=()=>{if(!current())return;idleAt=performance.now()+180;clearTimeout(thumbnailTimer);
   // Abandon an off-screen decode once, rather than reading clips the user has scrolled past.
   if(activeThumbnail&&!activeThumbnail.cancelled&&!visible(activeThumbnail.card)){activeThumbnail.cancelled=true;window.hnh.cancelMediaThumbnails?.();}
   thumbnailTimer=setTimeout(pump,180);
  };
  pumpCurrent=pump;
  observer=new IntersectionObserver(()=>scheduleThumbnails(),{root:grid,rootMargin:'0px'});
  if(current()){for(const card of grid.querySelectorAll('.media-card'))observer.observe(card);scheduleThumbnails();}
 }
 async function select(file,resume){if(busy)return;const mine=++token;selected=file;window.HnhUnifiedTags?.refresh();remember();const video=el('mediaVideo'),image=el('mediaImage');video.pause();if(tab==='video'){video.removeAttribute('src');video.load();}else image.removeAttribute('src');el('mediaName').textContent=file.filename;el('mediaTags').value=(state.settings.tags?.[file.path]||[]).join(', ');el('mediaFavorite').textContent=state.settings.favorites.includes(file.path)?'★ Đã yêu thích':'☆ Yêu thích';el('mediaUseRange').checked=false;el('mediaIn').value='0';el('mediaOut').value='';el('mediaPreviewStatus').textContent='Đang mở preview…';el('mediaEmpty').hidden=true;image.hidden=tab!=='image';video.hidden=tab!=='video';buttons();for(const card of el('mediaGrid').querySelectorAll('.media-card'))card.classList.toggle('selected',card.dataset.path===file.path);
  try{await new Promise(resolve=>setTimeout(resolve,70));if(mine!==token)return;const url=await window.hnh.mediaPreview(file);if(mine!==token)return;if(tab==='image'){image.onload=()=>{if(mine===token)el('mediaPreviewStatus').textContent=image.naturalWidth+' × '+image.naturalHeight+' px';};image.onerror=()=>{if(mine===token){image.hidden=true;el('mediaEmpty').hidden=false;el('mediaEmpty').textContent='Không hỗ trợ preview ảnh này';el('mediaPreviewStatus').textContent='Có thể thử Import vào Resolve hoặc mở thư mục.';}};image.src=url;}else{
    video.onloadedmetadata=()=>{if(mine!==token)return;const duration=video.duration;el('mediaOut').value=Number.isFinite(duration)?duration.toFixed(3):'';el('mediaPreviewStatus').textContent=video.videoWidth+' × '+video.videoHeight+(Number.isFinite(duration)?' • '+duration.toFixed(2)+' giây':'');buttons();if(Number.isFinite(duration)&&duration>0){file.duration=duration;for(const card of el("mediaGrid").querySelectorAll(".media-card")){if(card.dataset.path===file.path){const metric=card.querySelector(".media-row-metrics>span:nth-child(2)");if(metric)metric.textContent=HnhDuration.format(duration,true);const badge=card.querySelector(".video-duration");if(badge){badge.textContent=HnhDuration.format(duration,true);badge.title=HnhDuration.title(duration);}}}window.hnh.saveDuration(file,duration).catch(()=>{});}};video.onerror=()=>{if(mine===token){el('mediaPreviewStatus').textContent='Preview không hỗ trợ codec này. Vẫn có thể thử Import hoặc chèn toàn bộ bằng Resolve.';buttons();}};video.src=url;if(resume)video.addEventListener('loadedmetadata',()=>{if(mine===token){restorePreview(resume);window.dispatchEvent(new Event('hnh-media-tab'));}},{once:true});
  }}catch(e){if(mine===token)el('mediaPreviewStatus').textContent=e.message;}
 }
 async function tracks(){const mine=++trackToken,old=el('mediaTrack').value;try{const r=await window.hnh.mediaTracks();if(mine!==trackToken)return;el('mediaTrack').replaceChildren(new Option('Chọn track video',''));for(const t of r.tracks||[]){const option=new Option('V'+t.index+' • '+(t.name||'Video')+(t.locked?' (khóa)':''),String(t.index));option.disabled=!!t.locked;el('mediaTrack').add(option);}const audioSelect=el('mediaAudioTrack'),oldAudio=audioSelect.value;audioSelect.replaceChildren(new Option('Chọn audio track',''));for(const t of r.audioTracks||[]){const option=new Option('A'+t.index+' • '+(t.name||'Audio')+(t.locked?' (khóa)':''),String(t.index));option.disabled=!!t.locked;audioSelect.add(option);}const audioValid=[...audioSelect.options].filter(o=>o.value&&!o.disabled);audioSelect.value=audioValid.some(o=>o.value===oldAudio)?oldAudio:(audioValid[0]?.value||'');const valid=[...el('mediaTrack').options].filter(o=>o.value&&!o.disabled);el('mediaTrack').value=valid.some(o=>o.value===old)?old:(valid[0]?.value||'');if(!r.ok)status(r.error||'Chưa có timeline.');else if(!valid.length)status('Cần có track video không khóa trong timeline.');}catch(e){status(e.message);}buttons();}
 const sessions={};
 const previewIds=['mediaTags','mediaIn','mediaOut','mediaUseRange','mediaIncludeAudio','mediaAutoTracks','mediaCreateTracks','mediaTrack','mediaAudioTrack','mediaStillSeconds','videoLoopRange'];
 function captureSession(){if(tab==='audio')return;const values={};for(const id of previewIds){const n=el(id);if(n)values[id]={value:n.value,checked:n.checked};}sessions[tab]={nodes:[...el('mediaGrid').childNodes],filtered,selected,values,time:el('mediaVideo').currentTime,previewScroll:document.querySelector('.media-preview-scroll').scrollTop,files:state.mediaFiles,tags:state.settings.tags,favorites:state.settings.favorites,recent:state.settings.recent,view:el('mediaView').value,previewStatus:el('mediaPreviewStatus').textContent,actionStatus:el('mediaActionStatus').textContent,loaded:tab==='video'?el('mediaVideo').readyState>=1:el('mediaImage').complete&&el('mediaImage').naturalWidth>0,url:(tab==='video'?el('mediaVideo'):el('mediaImage')).getAttribute('src'),batch:document.body.classList.contains('batch-enabled')};}
 function restorePreview(snapshot){for(const [id,value] of Object.entries(snapshot.values)){const n=el(id);if(n){n.value=value.value;if(typeof value.checked==='boolean')n.checked=value.checked;}}if(tab==='video'&&Number.isFinite(el('mediaVideo').duration))try{el('mediaVideo').currentTime=Math.min(snapshot.time,el('mediaVideo').duration);}catch{}document.querySelector('.media-preview-scroll').scrollTop=snapshot.previewScroll;buttons();}
 function restoreSession(old){const snapshot=sessions[tab];if(!snapshot)return false;const file=snapshot.selected&&(state.mediaFiles||[]).find(f=>signature(f)===signature(snapshot.selected));selected=file||null;
  const valid=snapshot.files===state.mediaFiles&&snapshot.tags===state.settings.tags&&snapshot.favorites===state.settings.favorites&&snapshot.recent===state.settings.recent&&snapshot.batch===document.body.classList.contains('batch-enabled');
  if(valid){filtered=snapshot.filtered;const grid=el('mediaGrid');grid.replaceChildren(...snapshot.nodes);grid.dataset.view=snapshot.view;grid.style.setProperty('--thumb-size',el('mediaThumbSize').value+'px');el('mediaSizeLabel').hidden=snapshot.view!=='thumbnail';el('mediaDirection').textContent=direction==='asc'?'↑ Tăng dần':'↓ Giảm dần';el('mediaCount').textContent=filtered.length+(tab==='image'?' ảnh':' video');el('mediaPage').textContent=(filtered.length?page+1:0)+' / '+Math.ceil(filtered.length/PAGE);el('mediaPrev').disabled=page===0;el('mediaNext').disabled=(page+1)*PAGE>=filtered.length;window.HnhBatch?.visible(tab,filtered.slice(page*PAGE,(page+1)*PAGE),filtered);resumeThumbnails();}else render(true);
  el('mediaGrid').scrollTop=Math.max(0,Number(old.scroll)||0);el('mediaVideo').hidden=tab!=='video'||!file;el('mediaImage').hidden=tab!=='image'||!file;el('mediaEmpty').hidden=!!file;el('mediaName').textContent=file?.filename||'Chọn tài nguyên';el('mediaPreviewStatus').textContent=file?snapshot.previewStatus:'';el('mediaActionStatus').textContent=snapshot.actionStatus;el('mediaFavorite').textContent=state.settings.favorites.includes(file?.path)?'★ Đã yêu thích':'☆ Yêu thích';
  if(file){if(snapshot.loaded&&snapshot.url===(tab==='video'?el('mediaVideo'):el('mediaImage')).getAttribute('src'))restorePreview(snapshot);else select(file,snapshot);}else{el('mediaTags').value='';el('mediaUseRange').checked=false;buttons();}window.HnhUnifiedTags?.refresh();return true;
 }
 function setTab(next){if(busy||next===tab)return;if(searchTimer&&tab!=='audio')render(true);if(tab==='audio'){window.HnhBrowserState?.save();audioScroll=el('results').scrollTop;}else{remember();captureSession();}restoring=true;clearTimeout(searchTimer);stopThumbnails();renderToken++;token++;trackToken++;el('mediaVideo').pause();selected=null;tab=next;try{localStorage.setItem('hnh-last-tab',tab);}catch{}window.HnhBatch?.tab(tab);document.body.dataset.mediaTab=tab;for(const button of document.querySelectorAll('[data-media-tab]'))button.setAttribute('aria-pressed',String(button.dataset.mediaTab===tab));document.querySelector('main').hidden=tab!=='audio';document.querySelector('footer').hidden=tab!=='audio';el('mediaWorkspace').hidden=tab==='audio';el('audio').pause();el('mediaImageOptions').hidden=tab!=='image';el('mediaVideoOptions').hidden=tab!=='video';if(tab!=='audio'){const old=saved[tab]||{},c=old.controls||{};options();HnhQuickFilters.tags('media',state.mediaFiles||[],state.settings.tags||{},tab);const defaults={mediaMode:'all',mediaAddedMode:'all',mediaView:tab==='video'?'list':'thumbnail',mediaThumbSize:'160',mediaSort:'name'};for(const id of controlIds){el(id).value=c[id]??defaults[id]??'';if(el(id).tagName==='SELECT'&&!el(id).value&&defaults[id])el(id).value=defaults[id];}HnhQuickFilters.restore('media',{addedMode:el('mediaAddedMode').value,addedFrom:el('mediaAddedFrom').value,addedTo:el('mediaAddedTo').value});window.HnhUnifiedTags?.restore(tab,old.tagFilters);direction=old.direction==='desc'?'desc':'asc';page=Math.max(0,Number(old.page)||0);if(!restoreSession(old)){render(true);el('mediaGrid').scrollTop=Math.max(0,Number(old.scroll)||0);const file=filtered.find(f=>f.path===old.selected);if(file)select(file);else{el('mediaVideo').hidden=true;el('mediaImage').hidden=true;el('mediaEmpty').hidden=false;el('mediaName').textContent='Chọn tài nguyên';el('mediaTags').value='';buttons();}}tracks();}else el('results').scrollTop=audioScroll;restoring=false;remember();window.dispatchEvent(new Event('hnh-media-tab'));}
 async function run(fn){if(busy||!selected)return;busy=true;buttons();try{await fn(selected);}catch(e){status('Lỗi: '+e.message);}finally{busy=false;buttons();render();}}
 async function usage(file){await persistUsage(file);}
 for(const button of document.querySelectorAll('[data-media-tab]'))button.onclick=()=>setTab(button.dataset.mediaTab);
 el('mediaLibrary').onclick=()=>el('libraryPanel').classList.remove('hidden');
 for(const id of ['mediaSearch','mediaFolder','mediaMode','mediaSort'])el(id).addEventListener(id==='mediaSearch'?'input':'change',()=>{page=0;clearTimeout(searchTimer);if(id==='mediaSearch'&&(state.mediaFiles||[]).length>10000)searchTimer=setTimeout(()=>render(true),120);else render(true);});
 for(const id of ['mediaView','mediaThumbSize'])el(id).addEventListener('input',()=>{render(true);});el('mediaDirection').onclick=()=>{direction=direction==='asc'?'desc':'asc';page=0;render(true);};let saveTimer;el('mediaGrid').addEventListener('scroll',()=>{scheduleThumbnails();clearTimeout(saveTimer);saveTimer=setTimeout(remember,150);});window.addEventListener('beforeunload',remember);
 el('mediaPrev').onclick=()=>{page--;render(true);};el('mediaNext').onclick=()=>{page++;render(true);};
 el('mediaSaveTags').onclick=()=>run(async file=>{const tags=el('mediaTags').value.split(',').map(t=>t.trim()).filter(Boolean);state.settings=await window.hnh.updateSettings({tags:{...state.settings.tags,[file.path]:[...new Set(tags)].slice(0,30)}});status('Đã lưu tags cho '+file.filename);});
 el('mediaFavorite').onclick=()=>run(async file=>{await toggleFavorite(file);el('mediaFavorite').textContent=state.settings.favorites.includes(file.path)?'★ Đã yêu thích':'☆ Yêu thích';});
 el('mediaReveal').onclick=()=>selected&&window.hnh.revealInExplorer(selected.path);
 el('mediaRefreshTracks').onclick=tracks;el('mediaTrack').onchange=buttons;el('mediaAudioTrack').onchange=buttons;el('mediaIncludeAudio').onchange=buttons;el('mediaAutoTracks').onchange=buttons;el('mediaCreateTracks').onchange=buttons;
 el('mediaImport').onclick=()=>run(async file=>{const r=await window.hnh.mediaImport(file);if(!r.ok)throw Error((r.error||'Không import được')+(r.detail?' • '+r.detail:''));status('Đã import '+file.filename+(r.reused?' • dùng file đã có trong Media Pool':''));await usage(file);});
 el('mediaInsert').onclick=()=>run(async file=>{const opts={autoTracks:el('mediaAutoTracks').checked,createTracks:el('mediaCreateTracks').checked,includeAudio:tab==='video'&&el('mediaIncludeAudio').checked,audioTrackIndex:Number(el('mediaAudioTrack').value),trackIndex:Number(el('mediaTrack').value),seconds:Number(el('mediaStillSeconds').value)};if(tab==='video'&&el('mediaUseRange').checked){const duration=el('mediaVideo').duration,inSeconds=Number(el('mediaIn').value),outSeconds=Number(el('mediaOut').value);if(!el('mediaOut').value||!Number.isFinite(duration)||inSeconds<0||outSeconds<=inSeconds||outSeconds>duration+.001)throw Error('Cần 0 ≤ In < Out ≤ thời lượng video.');opts.range={inSeconds,outSeconds,duration};}const r=await window.hnh.mediaInsert(file,opts);if(!r.ok)throw Error((r.error||'Không chèn được')+(r.detail?' • '+r.detail:''));status('Đã chèn '+file.filename+' tại '+r.timecode+' • V'+r.trackIndex+(r.linked?' + A'+r.audioTrackIndex+' • đã liên kết':'')+(r.warning?' • '+r.warning:''));await usage(file);await tracks();});
 el('mediaMarkIn').onclick=()=>{el('mediaIn').value=el('mediaVideo').currentTime.toFixed(3);el('mediaUseRange').checked=true;};el('mediaMarkOut').onclick=()=>{el('mediaOut').value=el('mediaVideo').currentTime.toFixed(3);el('mediaUseRange').checked=true;};
 el('mediaWhole').onclick=()=>{el('mediaUseRange').checked=false;el('mediaIn').value='0';el('mediaOut').value=Number.isFinite(el('mediaVideo').duration)?el('mediaVideo').duration.toFixed(3):'';};
 for(const id of ['mediaIn','mediaOut'])el(id).oninput=()=>el('mediaUseRange').checked=true;
 el('mediaWorkspace').addEventListener('keydown',e=>{const typing=/INPUT|SELECT|TEXTAREA/.test(e.target.tagName);if(typing)return;if(e.key==='i'||e.key==='o'){e.preventDefault();if(tab==='video')el(e.key==='i'?'mediaMarkIn':'mediaMarkOut').click();}if(e.key==='Enter'&&e.target.tagName!=='BUTTON'){e.preventDefault();el(e.ctrlKey?'mediaImport':'mediaInsert').click();}});
 window.HnhMedia={clearThumbnailMemory(){for(const snapshot of Object.values(sessions)){snapshot.files=null;for(const node of snapshot.nodes)for(const img of node.querySelectorAll?.('.media-card-picture img')||[]){img.removeAttribute('src');img.hidden=true;}}stopThumbnails();renderToken++;thumbs.clear();thumbBytes=0;window.hnh.cancelMediaThumbnails?.();},performanceStats:()=>({thumbnailRunning,thumbnailEntries:thumbs.size,thumbnailCacheBytes:thumbBytes}),current:()=>({tab,selected}),remapTag(from,to){const k=t=>String(t||'').trim().normalize('NFC').toLocaleLowerCase('vi');for(const name of ['image','video']){const c=saved[name]?.controls;if(c&&k(c.mediaTagFilter)===k(from))c.mediaTagFilter=to;const f=saved[name]?.tagFilters;if(f?.selected)f.selected=[...new Set(f.selected.map(t=>k(t)===k(from)?to:t))];}try{localStorage.setItem('hnh-media-browser-v1',JSON.stringify(saved));}catch{}},restoreLast(){let last;try{last=localStorage.getItem('hnh-last-tab');}catch{}if(['image','video'].includes(last))setTab(last);},batchRefresh(){render();},filterChanged(){page=0;render(true);},resolveChanged(){if(tab!=='audio')tracks();},updated(){if(tab==='audio')return;if(selected){const current=(state.mediaFiles||[]).find(f=>signature(f)===signature(selected));if(!current)clearPreview();else{selected=current;el('mediaTags').value=(state.settings.tags?.[selected.path]||[]).join(', ');el('mediaFavorite').textContent=state.settings.favorites.includes(selected.path)?'★ Đã yêu thích':'☆ Yêu thích';}}options();render();}};

})();
