(() => {
 const el=id=>document.getElementById(id),create=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;},key=t=>t.trim().normalize('NFC').toLocaleLowerCase('vi');
 let mode='folders',selected=[],match='all',cacheFiles,cacheTags,counts=[],busy=false;
 const side=el('folderBrowser'),nav=create('div');nav.className='sidebar-tabs';const folders=create('button','Thư mục'),tags=create('button','Tags');nav.append(folders,tags);side.prepend(nav);
 const pane=create('div');pane.id='sidebarTags';pane.hidden=true;const search=create('input');search.id='sidebarTagSearch';search.placeholder='Tìm tag…';search.setAttribute('aria-label','Tìm tag');const list=create('div');list.id='sidebarTagList';const hint=create('small','Số SFX trong toàn bộ thư viện');pane.append(search,hint,list);side.append(pane);
 const filters=create('div');filters.id='selectedTagFilters';filters.hidden=true;const select=create('select');select.id='tagMatchMode';select.setAttribute('aria-label','Cách kết hợp tags');select.add(new Option('Có tất cả','all'));select.add(new Option('Có ít nhất một','any'));const chips=create('div');chips.className='selected-tag-chips';const clear=create('button','Bỏ lọc tags');clear.className='secondary';filters.append(select,chips,clear);document.querySelector('.folder-toolbar').after(filters);
 const editor=el('tagsEditor');editor.querySelector('summary').textContent='+ Tag';const quick=create('div');quick.className='quick-tag-add';const input=create('input');input.id='quickTagInput';input.placeholder='Gõ tag rồi Enter';input.setAttribute('aria-label','Thêm tag cho SFX');input.setAttribute('list','knownTags');const choices=create('datalist');choices.id='knownTags';const add=create('button','Thêm');add.id='quickTagAdd';const status=create('small');status.id='quickTagStatus';quick.append(input,choices,add,status);const body=editor.querySelector('.tag-editor-body');const advanced=create('details');const summary=create('summary','Sửa toàn bộ tags…');advanced.append(summary,el('tagsInput'),el('saveTags'));body.append(quick,advanced);
 const current=create('div');current.id='currentSoundTags';document.querySelector('.now-playing').before(current);
 function catalog(){if(cacheFiles===state.files&&cacheTags===state.settings.tags)return;cacheFiles=state.files;cacheTags=state.settings.tags;const map=new Map();for(const f of state.files){for(const [k,label] of new Map((state.settings.tags?.[f.path]||[]).map(t=>[key(t),t]))){const entry=map.get(k)||{label,count:0};entry.count++;map.set(k,entry);}}counts=[...map.values()].sort((a,b)=>a.label.localeCompare(b.label,'vi',{numeric:true}));choices.replaceChildren(...counts.map(t=>new Option(t.label,t.label)));}
 function filterChips(){filters.hidden=!selected.length;select.value=match;chips.replaceChildren();for(const tag of selected){const b=create('button',tag+' ×');b.setAttribute('aria-label','Bỏ lọc tag '+tag);b.onclick=()=>{selected=selected.filter(t=>key(t)!==key(tag));render();};chips.append(b);}}
 function listTags(){list.replaceChildren();const query=HnhSearch.norm(search.value),items=counts.filter(t=>HnhSearch.norm(t.label).includes(query));for(const t of items){const b=create('button'),label=create('span',t.label),n=create('small',String(t.count));b.append(label,n);b.setAttribute('aria-pressed',String(selected.some(x=>key(x)===key(t.label))));b.onclick=()=>{const exists=selected.some(x=>key(x)===key(t.label));selected=exists?selected.filter(x=>key(x)!==key(t.label)):[...selected,t.label];el('tagFilter').value='';render();};list.append(b);}if(!items.length)list.append(create('p',counts.length?'Không tìm thấy tag.':'Chưa có tag. Chọn SFX rồi bấm + Tag.'));}
 async function change(operation,tag){if(busy||!state.selected)return;const file={...state.selected};busy=true;input.disabled=add.disabled=true;status.textContent='Đang lưu…';try{const result=await window.hnh.bulkMetadata({files:[file],operation,tags:[tag]});state.settings=result.settings;if(state.selected?.path===file.path)el('tagsInput').value=(state.settings.tags?.[file.path]||[]).join(', ');if(operation==='addTags')input.value='';status.textContent='Đã lưu cho '+file.filename;render();}catch(e){status.textContent=e.message;}finally{busy=false;refresh();}}
 function addTag(){const text=input.value.trim();if(!text){status.textContent='Nhập hoặc chọn một tag.';return;}if(text.includes(',')){status.textContent='Thêm từng tag; dùng Sửa toàn bộ tags nếu cần nhập nhiều tag.';return;}const existing=counts.find(t=>key(t.label)===key(text));change('addTags',existing?.label||text);}
 function refresh(){catalog();el('folderTree').hidden=mode!=='folders';side.querySelector('.folder-caption').hidden=mode!=='folders';pane.hidden=mode!=='tags';folders.setAttribute('aria-pressed',String(mode==='folders'));tags.setAttribute('aria-pressed',String(mode==='tags'));listTags();filterChips();current.replaceChildren();const f=state.selected;input.disabled=add.disabled=busy||!f;current.hidden=!f;for(const tag of state.settings.tags?.[f?.path]||[]){const b=create('button',tag+' ×');b.title='Gỡ tag '+tag+' khỏi file đang chọn';b.disabled=busy;b.onclick=()=>change('removeTags',tag);current.append(b);}}
 folders.onclick=()=>{mode='folders';refresh();};tags.onclick=()=>{mode='tags';refresh();};search.oninput=listTags;select.onchange=()=>{match=select.value;render();};clear.onclick=()=>{selected=[];el('tagFilter').value='';render();};add.onclick=addTag;input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();e.stopPropagation();addTag();}};
 for(const node of [nav,pane,filters,current])node.addEventListener('keydown',e=>e.stopPropagation());
 el('audioQuickReset').addEventListener('click',()=>{selected=[];render();});el('tagFilter').addEventListener('change',()=>{selected=[];render();});
 window.HnhSidebarTags={remapTag(from,to){selected=[...new Set(selected.map(t=>key(t)===key(from)?to:t))];},refresh,matches(file){if(!selected.length)return true;const have=new Set((state.settings.tags?.[file.path]||[]).map(key));return match==='all'?selected.every(t=>have.has(key(t))):selected.some(t=>have.has(key(t)));},values(){return {sidebarTags:[...selected],tagMatch:match};},restore(f){selected=Array.isArray(f.sidebarTags)?f.sidebarTags.filter(t=>typeof t==='string'):[];match=f.tagMatch==='any'?'any':'all';}};refresh();
})();
