(() => {
 const el=id=>document.getElementById(id),make=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;},key=t=>String(t||'').trim().normalize('NFC').toLocaleLowerCase('vi');
 const filters={image:{selected:[],match:'all'},video:{selected:[],match:'all'}};let busy=false;
 const browser=document.querySelector('.media-browser'),catalog=make('div'),side=make('aside'),search=make('input'),list=make('div'),mode=make('select'),clear=make('button','Bỏ lọc tags'),heading=make('small');catalog.className='media-catalog';side.className='media-tag-sidebar';search.placeholder='Tìm tag…';search.id='mediaSidebarTagSearch';search.setAttribute('aria-label','Tìm tag trong tab');list.id='mediaSidebarTagList';mode.id='mediaTagMatch';mode.add(new Option('Có tất cả','all'));mode.add(new Option('Có ít nhất một','any'));clear.className='secondary';side.append(make('strong','Tags'),search,heading,mode,clear,list);catalog.append(side,el('mediaGrid'));browser.append(catalog);
 const quick=make('div'),input=make('input'),add=make('button','+ Tag'),datalist=make('datalist'),chips=make('div'),message=make('small');quick.className='media-quick-tags';input.id='mediaQuickTag';input.placeholder='Gõ tag rồi Enter';input.setAttribute('list','mediaKnownTags');datalist.id='mediaKnownTags';chips.className='media-current-tags';chips.id='mediaCurrentTags';quick.append(chips,input,add,datalist,message);document.querySelector('.media-tags').before(quick);
 let countFiles,countTags,countCache=new Map(),choiceEntries;
 function counts(kind){if(countFiles!==state.mediaFiles||countTags!==state.settings.tags){countFiles=state.mediaFiles;countTags=state.settings.tags;countCache.clear();}if(countCache.has(kind))return countCache.get(kind);const all=new Map();for(const file of state.mediaFiles||[]){if(kind&&HnhMediaTypes.fileKind(file)!==kind)continue;for(const tag of new Map((state.settings.tags?.[file.path]||[]).map(t=>[key(t),t])).values()){const k=key(tag),r=all.get(k)||{label:tag,count:0};r.count++;all.set(k,r);}}const result=[...all.values()].sort((a,b)=>a.label.localeCompare(b.label,'vi',{numeric:true}));countCache.set(kind,result);return result;}
 function refresh(){const current=window.HnhMedia?.current();if(!current||current.tab==='audio')return;const {tab,selected}=current,f=filters[tab],entries=counts(tab);heading.textContent='Số file trong tab '+(tab==='image'?'Ảnh':'Video');mode.value=f.match;list.replaceChildren();for(const r of entries.filter(r=>HnhSearch.norm(r.label).includes(HnhSearch.norm(search.value)))){const b=make('button'),label=make('span',r.label),n=make('small',String(r.count));b.append(label,n);b.setAttribute('aria-pressed',String(f.selected.some(t=>key(t)===key(r.label))));b.onclick=()=>{const exists=f.selected.some(t=>key(t)===key(r.label));f.selected=exists?f.selected.filter(t=>key(t)!==key(r.label)):[...f.selected,r.label];el('mediaTagFilter').value='';HnhMedia.filterChanged();};list.append(b);}if(!list.children.length)list.append(make('small','Chưa có tag phù hợp.'));clear.textContent=f.selected.length?'Bỏ '+f.selected.length+' tag đang lọc':'Bỏ lọc tags';clear.disabled=!f.selected.length;chips.replaceChildren();for(const tag of state.settings.tags?.[selected?.path]||[]){const b=make('button',tag+' ×');b.title='Gỡ tag khỏi file đang chọn';b.disabled=busy;b.onclick=()=>change('removeTags',tag);chips.append(b);}input.disabled=add.disabled=busy||!selected;const entriesAll=counts();if(choiceEntries!==entriesAll){choiceEntries=entriesAll;datalist.replaceChildren(...entriesAll.map(r=>new Option(r.label,r.label)));}}
 async function change(operation,tag){const file=HnhMedia.current().selected;if(!file||busy)return;busy=true;refresh();message.textContent='Đang lưu…';try{const result=await window.hnh.bulkMetadata({files:[{...file}],operation,tags:[tag]});state.settings=result.settings;input.value='';message.textContent='Đã lưu cho '+file.filename;render();HnhMedia.updated();}catch(e){message.textContent=e.message;}finally{busy=false;refresh();}}
 function addTag(){const tag=input.value.trim();if(!tag||tag.includes(',')){message.textContent='Nhập một tag; dùng ô Tags bên dưới để sửa nhiều tag.';return;}change('addTags',counts().find(r=>key(r.label)===key(tag))?.label||tag);}
 add.onclick=addTag;input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();e.stopPropagation();addTag();}};search.oninput=refresh;mode.onchange=()=>{filters[HnhMedia.current().tab].match=mode.value;HnhMedia.filterChanged();};clear.onclick=()=>{filters[HnhMedia.current().tab].selected=[];HnhMedia.filterChanged();};el('mediaTagFilter').addEventListener('change',()=>{filters[HnhMedia.current().tab].selected=[];HnhMedia.filterChanged();});el('mediaQuickReset').addEventListener('click',()=>{filters[HnhMedia.current().tab].selected=[];HnhMedia.filterChanged();});
 const dialog=make('dialog'),title=make('h2','Quản lý tags'),from=make('select'),to=make('input'),description=make('p'),apply=make('button','Đổi tên / Gộp tag'),close=make('button','Đóng'),resultText=make('p');dialog.id='tagManager';from.id='renameTagFrom';from.setAttribute('aria-label','Tag cần đổi');to.id='renameTagTo';to.placeholder='Tên tag mới hoặc tag để gộp vào';to.maxLength=160;to.setAttribute('aria-label','Tên tag đích');apply.id='renameTagApply';close.className='secondary';dialog.append(title,make('p','Áp dụng cho cả âm thanh, ảnh và video trong dữ liệu đang dùng, kể cả đường dẫn chưa có trong index. Nếu tên đích đã tồn tại, các tag sẽ được gộp; không nhân đôi tag trên file. Các bản backup/pending restore cũ không đổi.'),from,to,description,apply,close,resultText);document.body.append(dialog);
 function describe(){const source=key(from.value),dest=key(to.value),n=Object.values(state.settings.tags||{}).filter(a=>a.some(t=>key(t)===source)).length,exists=Object.values(state.settings.tags||{}).some(a=>a.some(t=>key(t)===dest));description.textContent=n+' file sẽ đổi từ “'+from.value+'” sang “'+to.value.trim()+'”.'+(exists&&dest!==source?' Tag đích đã tồn tại: sẽ gộp.':'');apply.disabled=busy||!source||!dest;}
 function openManager(){from.replaceChildren();const unique=new Map(Object.values(state.settings.tags||{}).flat().map(t=>[key(t),t]));for(const tag of [...unique.values()].sort((a,b)=>a.localeCompare(b,'vi')))from.add(new Option(tag,tag));to.value='';resultText.textContent='';describe();dialog.showModal();}
 for(const container of [el('sidebarTags'),side]){const b=make('button','Quản lý tags');b.className='secondary manage-tags';b.onclick=openManager;container.append(b);}from.onchange=describe;to.oninput=describe;close.onclick=()=>dialog.close();dialog.addEventListener('keydown',e=>e.stopPropagation());
 apply.onclick=async()=>{if(busy)return;busy=true;apply.disabled=close.disabled=true;from.disabled=to.disabled=true;try{const r=await window.hnh.renameTag({from:from.value,to:to.value});state.settings=r.settings;const map=t=>key(t)===key(r.from)?r.to:t;for(const kind of ['image','video'])filters[kind].selected=[...new Set(filters[kind].selected.map(map))];for(const id of ['tagFilter','mediaTagFilter']){const node=el(id);if(key(node.value)===key(r.from)){if(![...node.options].some(o=>o.value===r.to))node.add(new Option(r.to,r.to));node.value=r.to;}}HnhSidebarTags.remapTag(r.from,r.to);HnhMedia.remapTag(r.from,r.to);renderCollections();render();HnhMedia.updated();window.HnhBrowserState?.remapTag(r.from,r.to);window.HnhBrowserState?.save();resultText.textContent='Đã cập nhật '+r.count+' file. Bản sao trước thay đổi: '+r.backup;from.replaceChildren(new Option(r.to,r.to));to.value='';}catch(e){resultText.textContent=e.message;}finally{busy=false;close.disabled=from.disabled=to.disabled=false;describe();refresh();}};
 window.HnhUnifiedTags={refresh,values(kind){return {...filters[kind],selected:[...filters[kind].selected]};},restore(kind,v){filters[kind]={selected:Array.isArray(v?.selected)?v.selected.filter(t=>typeof t==='string'):[],match:v?.match==='any'?'any':'all'};search.value='';},matches(kind,file){const f=filters[kind],have=new Set((state.settings.tags?.[file.path]||[]).map(key));return !f.selected.length||(f.match==='any'?f.selected.some(t=>have.has(key(t))):f.selected.every(t=>have.has(key(t))));}};
})();
