(() => {
 const el=id=>document.getElementById(id),dialog=el('updateDialog');let busy=false,lastInfo=null,prompted=false;const installedDialog=el('installedDialog');const notesText=entries=>(entries||[]).map(r=>'v'+r.version+'\n'+(r.notes||'Chưa có ghi chú.')).join('\n\n────────────────────\n\n');function combined(info){return (info.historyNotice?info.historyNotice+'\n\n':'')+(info.historyEntries?.length?notesText(info.historyEntries):info.release?.notes||'Chưa có ghi chú thay đổi.');}function installedView(all=false){if(!lastInfo)return;const change=lastInfo.installed;el('installedTitle').textContent=all?'Lịch sử đến v'+lastInfo.current:'Có gì mới trong v'+lastInfo.current;el('installedHint').textContent=!all&&change?.from?'Các thay đổi từ v'+change.from+' đến v'+change.to:!all?'Không xác định được phiên bản trước; hiển thị toàn bộ lịch sử đi kèm từ phiên bản sớm nhất có ghi chú.':'Lịch sử đi kèm plugin, xem được khi không có mạng.';el('installedNotes').textContent=notesText(all?lastInfo.localHistory:change?.entries||lastInfo.localHistory);el('installedAcknowledge').hidden=!change?.pending;if(!installedDialog.open)installedDialog.showModal();el('installedTitle').focus({preventScroll:true});installedDialog.scrollTop=0;}function maybeInstalled(){if(prompted||!lastInfo?.installed?.pending)return;if(document.querySelector('dialog[open]'))return;prompted=true;installedView();}el('showInstalledHistory').onclick=()=>installedView(true);el('installedClose').onclick=()=>installedDialog.close();el('installedAcknowledge').onclick=async()=>{try{show(await window.hnh.acknowledgeInstalled());installedDialog.close();}catch(e){el('installedHint').textContent=e.message;}};installedDialog.addEventListener('keydown',e=>e.stopPropagation());document.addEventListener('click',()=>setTimeout(maybeInstalled,100));setTimeout(maybeInstalled,1000);
 function show(info){lastInfo=info;el('installedSummary').textContent=info.installed?.from?'Đã nâng từ v'+info.installed.from+' lên v'+info.current:info.installed?.unknown?'Không xác định được bản cũ; lịch sử đi kèm vẫn có đầy đủ các bản đã ghi nhận.':'';el('updateAuto').checked=info.auto;let message='Đang dùng v'+info.current+'. ';if(info.error)message+=info.error;else if(info.available)message+='Có bản mới v'+info.release.version+'.';else if(info.release&&!info.release.ready)message+='Bản trên GitHub chưa có gói cài '+info.release.assetName+'.';else if(info.release)message+='Chưa có bản mới hơn.';else message+='Chưa kiểm tra cập nhật.';if(info.lastAttempt)message+=' Kiểm tra gần nhất: '+new Date(info.lastAttempt).toLocaleString('vi-VN');el('updateStatus').textContent=message;el('updateRelease').hidden=!info.release;if(info.release){el('updateReleaseTitle').textContent=info.available?'Thay đổi từ v'+info.current+' đến v'+info.release.version:'Bản trên GitHub v'+info.release.version;el('updateReleaseNotes').textContent=combined(info);}el('updateShortcut').textContent=info.available?'Cập nhật • v'+info.release.version:'Cập nhật';el('updateOpen').textContent=info.available?'Tải bản mới v'+info.release.version:'Mở trang phát hành';return info;}
 async function check(manual){if(busy)return;busy=true;el('updateCheck').disabled=true;el('updateStatus').textContent='Đang kiểm tra trên GitHub…';try{const info=show(await window.hnh.checkUpdates(manual));if(info.available&&!info.error&&(manual||info.auto&&!info.ignored&&!info.deferred)&&(manual||!document.querySelector('dialog[open]'))){el('updateVersion').textContent='Có bản mới v'+info.release.version;el('updateNotes').textContent=combined(info);el('updateIgnore').onclick=async()=>{await window.hnh.configureUpdates({ignore:info.release.version});dialog.close();};el('updateLater').onclick=async()=>{await window.hnh.configureUpdates({defer:info.release.version});dialog.close();};dialog.showModal();}}catch(e){el('updateStatus').textContent='Không kiểm tra được cập nhật: '+e.message;}finally{busy=false;el('updateCheck').disabled=false;}}
 el('updateShortcut').onclick=()=>{const help=el('updatesPanel');if(!help.open)help.showModal();help.scrollTop=0;el('updateCheck').focus({preventScroll:true});};
 el('closeUpdatesPanel').onclick=()=>el('updatesPanel').close();el('updatesPanel').addEventListener('keydown',e=>e.stopPropagation());
 el('updateCheck').onclick=()=>check(true);el('updateAuto').onchange=async()=>{try{show(await window.hnh.configureUpdates({auto:el('updateAuto').checked}));}catch(e){el('updateStatus').textContent=e.message;}};
 for(const id of ['updateOpen','updateDownload'])el(id).onclick=async()=>{try{await window.hnh.openUpdates();}catch(e){el('updateStatus').textContent=e.message;}};
 el('updateLater').onclick=()=>dialog.close();dialog.addEventListener('keydown',e=>e.stopPropagation());
 window.hnh.updateState().then(info=>{show(info);setTimeout(maybeInstalled,1000);}).catch(e=>{el('updateStatus').textContent=e.message;});setTimeout(()=>check(false),4500);
})();
