(() => {
 const el=id=>document.getElementById(id),video=el('mediaVideo'),host=el('mediaVideoOptions');
 const panel=document.createElement('div');panel.className='video-preview-tools';panel.innerHTML='<div class="video-transport"><button id="videoPlayToggle" type="button">▶ Phát</button><button id="videoPlayRange" type="button">▶ Đoạn In/Out</button><button id="videoGoIn" class="secondary" type="button">Về In</button><button id="videoGoOut" class="secondary" type="button">Về Out</button></div><label><input id="videoLoopRange" type="checkbox" /> Lặp đoạn In/Out</label><p id="videoRangeInfo" role="status"></p><div class="video-preview-volume"><label for="videoVolume">Âm lượng nghe thử</label><input id="videoVolume" type="range" min="0" max="100" value="100" /><span id="videoVolumeLabel">100%</span><label><input id="videoMute" type="checkbox" /> Tắt tiếng</label></div><small>Space: phát/dừng · ←/→: 1 giây · Shift + ←/→: 5 giây · I/O: đánh dấu. Chỉ áp dụng khi đang thao tác preview hoặc danh sách video.</small>';
 host.prepend(panel);let audition=false,frame=0,generation=0,prefs={};try{prefs=JSON.parse(localStorage.getItem('hnh-video-preview-v1')||'{}')||{};}catch{}
 video.volume=Number.isFinite(prefs.volume)?Math.max(0,Math.min(1,prefs.volume)):1;video.muted=prefs.muted===true;
 const ready=()=>window.HnhMedia?.current().tab==='video'&&!!window.HnhMedia.current().selected&&Number.isFinite(video.duration)&&video.duration>0&&!video.error;
 function range(){const a=Number(el('mediaIn').value),b=Number(el('mediaOut').value);return ready()&&el('mediaIn').value!==''&&el('mediaOut').value!==''&&Number.isFinite(a)&&Number.isFinite(b)&&a>=0&&b>a&&b<=video.duration+.001?{a,b:Math.min(b,video.duration)}:null;}
 function update(){const r=range(),ok=ready();el('videoPlayToggle').disabled=!ok;el('videoPlayToggle').textContent=video.paused?'▶ Phát':'❚❚ Dừng';for(const id of ['videoPlayRange','videoGoIn','videoGoOut','videoLoopRange'])el(id).disabled=!r;el('videoRangeInfo').textContent=!ok?'Chọn video có preview để đánh dấu đoạn.':r?'In '+r.a.toFixed(3)+'s → Out '+r.b.toFixed(3)+'s • Đoạn '+(r.b-r.a).toFixed(3)+' giây':'Đoạn chưa hợp lệ: cần 0 ≤ In < Out ≤ thời lượng video.';if(audition&&!r){audition=false;video.pause();}}
 function volume(){el('videoVolume').value=Math.round(video.volume*100);el('videoVolumeLabel').textContent=Math.round(video.volume*100)+'%';el('videoMute').checked=video.muted;try{localStorage.setItem('hnh-video-preview-v1',JSON.stringify({volume:video.volume,muted:video.muted}));}catch{}}
 function stopFrame(){cancelAnimationFrame(frame);frame=0;}
 function boundary(){if(!audition)return;const r=range();if(!r){audition=false;video.pause();return;}if(video.currentTime>=r.b||video.ended){if(el('videoLoopRange').checked){video.currentTime=r.a;if(video.paused)startPlay();}else{video.pause();video.currentTime=r.b;audition=false;}}else if(video.currentTime<r.a)video.currentTime=r.a;}
 function tick(){frame=0;if(video.paused)return;boundary();if(!video.paused)frame=requestAnimationFrame(tick);}
 async function startPlay(){const mine=generation;try{await video.play();}catch(e){if(mine===generation&&e.name!=='AbortError')el('videoRangeInfo').textContent='Không phát được preview: '+e.message;}}
 function play(useRange=false){if(!ready())return;const r=range();if(useRange&&!r)return;audition=useRange;if(useRange)video.currentTime=r.a;startPlay();}
 function toggle(){if(!video.paused){video.pause();return;}const r=range();if(el('mediaUseRange').checked&&r){audition=true;if(video.currentTime<r.a||video.currentTime>=r.b)video.currentTime=r.a;startPlay();}else play(false);}
 el('videoPlayToggle').onclick=toggle;el('videoPlayRange').onclick=()=>play(true);for(const [id,k] of [['videoGoIn','a'],['videoGoOut','b']])el(id).onclick=()=>{const r=range();if(r){audition=false;video.pause();video.currentTime=r[k];}};
 el('videoVolume').oninput=()=>video.volume=Number(el('videoVolume').value)/100;el('videoMute').onchange=()=>video.muted=el('videoMute').checked;video.addEventListener('volumechange',volume);volume();
 video.addEventListener('play',()=>{if(el('mediaUseRange').checked&&range())audition=true;boundary();stopFrame();if(!video.paused)frame=requestAnimationFrame(tick);update();});video.addEventListener('pause',()=>{stopFrame();update();});video.addEventListener('timeupdate',()=>{if(!video.paused)boundary();});video.addEventListener('ended',()=>{boundary();update();});video.addEventListener('emptied',()=>{generation++;audition=false;stopFrame();update();});for(const event of ['loadedmetadata','error','durationchange'])video.addEventListener(event,()=>setTimeout(update,0));
 for(const id of ['mediaIn','mediaOut','mediaUseRange'])el(id).addEventListener('input',()=>{if(id==='mediaUseRange'&&!el(id).checked)audition=false;update();});for(const id of ['mediaMarkIn','mediaMarkOut','mediaWhole'])el(id).addEventListener('click',()=>{if(id==='mediaWhole')audition=false;update();});
 el('mediaWorkspace').addEventListener('keydown',e=>{if(!ready()||e.ctrlKey||e.metaKey||e.altKey||e.target.closest('input,select,textarea,[contenteditable=true]'))return;if(e.target.closest('button')&&!e.target.closest('.media-card'))return;const key=e.key.toLowerCase();if(![' ','arrowleft','arrowright','i','o'].includes(key))return;e.preventDefault();e.stopImmediatePropagation();if(e.repeat&&[' ','i','o'].includes(key))return;if(key===' ')toggle();else if(key==='i'||key==='o')el(key==='i'?'mediaMarkIn':'mediaMarkOut').click();else{audition=false;video.currentTime=Math.max(0,Math.min(video.duration,video.currentTime+(key==='arrowleft'?-1:1)*(e.shiftKey?5:1)));}},true);
 window.addEventListener('hnh-media-tab',()=>{generation++;audition=false;stopFrame();update();});
 update();
})();
