const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const MAX=96*1024*1024;
function validateWave(data,range){const b=Buffer.from(data);if(b.length<44||b.length>MAX||b.toString('ascii',0,4)!=='RIFF'||b.toString('ascii',8,12)!=='WAVE'||b.toString('ascii',12,16)!=='fmt '||b.readUInt32LE(16)!==16||b.readUInt16LE(20)!==1||b.toString('ascii',36,40)!=='data')throw Error('File WAV không hợp lệ.');const channels=b.readUInt16LE(22),rate=b.readUInt32LE(24),bits=b.readUInt16LE(34),align=channels*3,bytes=b.readUInt32LE(40);if(![1,2].includes(channels)||rate!==48000||bits!==24||b.readUInt16LE(32)!==align||b.readUInt32LE(28)!==rate*align||bytes!==b.length-44||b.readUInt32LE(4)!==b.length-8||bytes%align)throw Error('Thông số WAV không hợp lệ.');const frames=bytes/align,expected=Math.round(range.outSeconds*rate)-Math.round(range.inSeconds*rate);if(Math.abs(frames-expected)>1||frames<1)throw Error('Thời lượng WAV không khớp In/Out.');return {buffer:b,frames,channels,seconds:frames/rate};}
function registerAudioExport({ipcMain,dialog,getWindow,loadIndex}){
 const pending=new Map();let preparing=false,writing=false;
 async function fileInfo(input){const index=await loadIndex(),file=index.files.find(f=>f.path===input?.path);if(!file||!['wav','mp3','flac','aiff','aif','m4a','aac','ogg'].includes(file.extension)||file.size!==input.size||file.mtimeMs!==input.mtimeMs)throw Error('File đã thay đổi hoặc không còn trong thư viện.');const stat=await fs.stat(file.path);if(!stat.isFile()||stat.size!==file.size||stat.mtimeMs!==file.mtimeMs)throw Error('File nguồn đã thay đổi; quét lại trước khi export.');if(stat.size>64*1024*1024)throw Error('Bản này xuất SFX có file nguồn tối đa 64 MB.');return file;}
 const targetExists=async p=>{try{await fs.lstat(p);return true;}catch(e){if(e.code==='ENOENT')return false;throw e;}};
 function prune(){for(const [id,p] of pending)if(Date.now()-p.time>10*60*1000)pending.delete(id);}
 ipcMain.handle('export:prepare',async(_e,request)=>{if(preparing||writing)throw Error('Đang xử lý một yêu cầu export.');preparing=true;try{prune();const file=await fileInfo(request.file);require('./trim').validateRange(request.range);if(request.range.duration>1200)throw Error('Bản này hỗ trợ nguồn SFX dài tối đa 20 phút.');if((request.range.outSeconds-request.range.inSeconds)*48000*6+44>MAX)throw Error('Đoạn chọn quá dài để xuất WAV trong phiên bản này.');const name=path.basename(file.path,path.extname(file.path))+'_'+request.range.inSeconds.toFixed(3)+'-'+request.range.outSeconds.toFixed(3)+'.wav';const choice=await dialog.showSaveDialog(getWindow(),{title:'Xuất đoạn In/Out — WAV 24-bit / 48 kHz',defaultPath:name,filters:[{name:'WAV audio',extensions:['wav']}],properties:['createDirectory','showOverwriteConfirmation']});if(choice.canceled||!choice.filePath)return {canceled:true};let dest=path.resolve(choice.filePath);if(path.extname(dest).toLowerCase()!=='.wav')dest+='.wav';if(dest.toLowerCase()===path.resolve(file.path).toLowerCase()||await targetExists(dest))throw Error('Chọn tên file mới. Export không ghi đè file đã có.');await fileInfo(request.file);const bytes=new Uint8Array(await fs.readFile(file.path));await fileInfo(request.file);const token=crypto.randomUUID();pending.set(token,{file,range:request.range,dest,time:Date.now()});return {token,bytes,range:request.range};}finally{preparing=false;}});
 ipcMain.handle('export:cancel',(_e,token)=>{pending.delete(token);return true;});
 ipcMain.handle('export:save',async(_e,token,data)=>{if(writing)throw Error('Đang ghi file export.');prune();const job=pending.get(token);if(!job)throw Error('Yêu cầu export hết hạn; thử lại.');pending.delete(token);writing=true;let handle,created=false;try{await fileInfo(job.file);const wav=validateWave(data,job.range);handle=await fs.open(job.dest,'wx');created=true;await handle.writeFile(wav.buffer);await handle.sync();await handle.close();handle=null;return {ok:true,path:job.dest,seconds:wav.seconds,channels:wav.channels};}catch(e){if(handle)await handle.close().catch(()=>{});if(created)await fs.unlink(job.dest).catch(()=>{});throw e;}finally{writing=false;}});
}
module.exports={registerAudioExport,validateWave};
