const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const LEGACY_BINS={video:'01_VIDEO',audio:'02_AUDIO',image:'03_IMAGE',other:'04_OTHER'};
const BINS={video:'01_🎬 VIDEO',audio:'02_🎵 AUDIO',image:'03_🖼 IMAGE',other:'04_📦 OTHER',timeline:'05_📋 TIMELINES',compound:'06_🧩 COMPOUND'};
const matchesBin=(name,kind)=>name===BINS[kind]||name===LEGACY_BINS[kind];
function list(value){if(Array.isArray(value))return value;if(value&&typeof value==='object'){const keys=Object.keys(value);if(keys.every(k=>/^\d+$/.test(k)))return keys.sort((a,b)=>Number(a)-Number(b)).map(k=>value[k]);}throw Error('Resolve không trả danh sách hợp lệ; đã dừng để tránh bỏ sót media.');}
async function id(o){const value=await o?.GetUniqueId?.();if(!value)throw Error('Resolve không trả ID ổn định.');return String(value);}
function classify(props,isTimeline=false,enabled={}){
 const type=String(props.Type||'').trim().toLowerCase(),file=String(props['File Path']||'').trim();
 if(isTimeline&&enabled.timeline)return {kind:'timeline',reason:'Timeline được nhận diện qua project'};
 if(!isTimeline&&type==='compound clip'&&enabled.compound)return {kind:'compound',reason:'Resolve trả loại Compound Clip'};
 if(isTimeline||/timeline|compound|multicam|fusion|generator|title/.test(type))return {kind:null,reason:'Timeline hoặc clip đặc biệt'};
 if(!file)return {kind:null,reason:'Không có đường dẫn nguồn; cần kiểm tra'};
 if(/^(video|video \+ audio|video\+audio|video with audio|image sequence)$/.test(type))return {kind:'video',reason:'Loại media từ Resolve'};
 if(type==='audio')return {kind:'audio',reason:'Loại media từ Resolve'};
 if(/^(still|image|still image)$/.test(type))return {kind:'image',reason:'Loại media từ Resolve'};
 if(type)return {kind:null,reason:'Loại Resolve chưa xác định an toàn: '+type};
 const ext=path.extname(file).toLowerCase();
 for(const [kind,extensions] of Object.entries({video:['.mp4','.mov','.mxf','.braw','.r3d','.avi','.mkv','.mts','.m2ts','.webm'],audio:['.wav','.mp3','.flac','.m4a','.aac','.aif','.aiff','.ogg'],image:['.jpg','.jpeg','.png','.webp','.tif','.tiff','.bmp','.exr','.dpx']}))if(extensions.includes(ext))return {kind,reason:'Đuôi file; Resolve chưa trả loại'};
 return {kind:'other',reason:'File nguồn chưa xác định loại'};
}
function configuration(request='root'){
 const scope=typeof request==='string'?request:request?.scope||'root';if(!['root','current'].includes(scope))throw Error('Phạm vi không hợp lệ.');
 const groups={};for(const kind of Object.keys(BINS)){const raw=typeof request==='object'?request.groups?.[kind]:null;const name=String(raw?.name??BINS[kind]).trim();if(!name||name.length>100||/[\\/\x00-\x1f]/.test(name))throw Error('Tên Bin phải có 1–100 ký tự, không chứa dấu phân cách thư mục.');groups[kind]={enabled:raw?.enabled??!['timeline','compound'].includes(kind),name,targetId:raw?.targetId?String(raw.targetId):null};if(typeof groups[kind].enabled!=='boolean')throw Error('Tùy chọn nhóm không hợp lệ.');}return {scope,groups};
}
const fingerprint=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
const breathe=()=>new Promise(r=>setTimeout(r,0));
class AutoBin{
 constructor({getResolve,dir,progress=()=>{}}){this.getResolve=getResolve;this.file=path.join(dir,'auto-bin-last.json');this.progress=progress;this.plan=null;}
 async context(){const resolve=await this.getResolve();if(!resolve)throw Error('Chưa kết nối Resolve.');const project=await (await resolve.GetProjectManager()).GetCurrentProject();if(!project)throw Error('Hãy mở project.');const pool=await project.GetMediaPool();if(typeof pool.MoveClips!=='function'||typeof pool.AddSubFolder!=='function')throw Error('Resolve chưa cung cấp API Auto Bin.');return {project,pool,key:(await id(project))+'|'+(await id(pool)),root:await pool.GetRootFolder()};}
 async same(ctx){if((await this.context()).key!==ctx.key)throw Error('Project đã thay đổi; thao tác đã dừng.');}
 async fresh(folder){if(typeof folder.GetIsFolderStale==='function'&&await folder.GetIsFolderStale())throw Error('Bin đang cũ trong project cộng tác. Hãy làm mới Media Pool rồi quét lại.');}
 async read(){try{return JSON.parse(await fs.readFile(this.file,'utf8'));}catch(e){if(e.code==='ENOENT')return null;throw Error('Không đọc được nhật ký Auto Bin; giữ nguyên project.');}}
 async write(journal){await fs.mkdir(path.dirname(this.file),{recursive:true});const tmp=this.file+'.'+crypto.randomUUID()+'.tmp';await fs.writeFile(tmp,JSON.stringify(journal,null,2));await fs.rename(tmp,this.file);}
 async folders(scope='root'){const config=configuration(scope),ctx=await this.context(),source=config.scope==='root'?ctx.root:await ctx.pool.GetCurrentFolder();await this.fresh(source);const children=[];for(const f of list(await source.GetSubFolderList()))children.push({id:await id(f),name:String(await f.GetName())});await this.same(ctx);return {children};}
 async inspect(scope,groups=configuration(scope).groups){if(!['root','current'].includes(scope))throw Error('Phạm vi không hợp lệ.');const ctx=await this.context(),source=scope==='root'?ctx.root:await ctx.pool.GetCurrentFolder();await this.fresh(source);const sourceId=await id(source),children=[];
  for(const child of list(await source.GetSubFolderList()))children.push({id:await id(child),name:String(await child.GetName()),object:child});
  const timelines=new Set(),count=Number(await ctx.project.GetTimelineCount());if(!Number.isInteger(count)||count<0||count>5000)throw Error('Không đọc được danh sách timeline an toàn.');
  for(let i=1;i<=count;i++){const timeline=await ctx.project.GetTimelineByIndex(i),item=await timeline?.GetMediaPoolItem?.();if(!item)throw Error('Không nhận diện được timeline trong Media Pool; đã dừng.');timelines.add(await id(item));if(i%20===0)await breathe();}
  const items=list(await source.GetClipList());if(items.length>10000)throw Error('Bin có hơn 10.000 mục; hãy chia nhỏ phạm vi.');const rows=[],seen=new Set();
  for(const item of items){const uid=await id(item);if(seen.has(uid))throw Error('Media Pool trả ID trùng.');seen.add(uid);const props=await item.GetClipProperty();if(!props||typeof props!=='object')throw Error('Không đọc được thuộc tính media.');const decision=classify(props,timelines.has(uid),Object.fromEntries(Object.entries(groups).map(([k,v])=>[k,v.enabled])));if(decision.kind&&!groups[decision.kind].enabled){decision.reason='Nhóm đã tắt: giữ nguyên media';decision.kind=null;}rows.push({id:uid,name:String(await item.GetName()),type:String(props.Type||''),file:String(props['File Path']||''),...decision,object:item});if(rows.length%20===0){this.progress({phase:'scan',done:rows.length,total:items.length});await breathe();}}
  const targets={};for(const [kind,config] of Object.entries(groups)){if(!config.enabled)continue;let matches;if(config.targetId){matches=children.filter(f=>f.id===config.targetId);if(matches.length!==1)throw Error('Bin đích đã chọn không còn trong phạm vi; hãy chọn lại.');}else matches=children.filter(f=>f.name===config.name||(config.name===BINS[kind]&&matchesBin(f.name,kind)));if(matches.length>1)throw Error('Có nhiều Bin cùng nhóm '+config.name+'. Hãy chọn chính xác một Bin.');targets[kind]=matches[0]||{id:null,name:config.name};}
  await this.same(ctx);const serial={key:ctx.key,sourceId,children:children.map(({id,name})=>({id,name})).sort((a,b)=>a.id.localeCompare(b.id)),rows:rows.map(({object,...r})=>r).sort((a,b)=>a.id.localeCompare(b.id))};return {ctx,source,sourceId,targets,sourceName:String(await source.GetName()),children,rows,hash:fingerprint(serial)};
 }
 async reconcile(ctx){const journal=await this.read();if(!journal||journal.key!==ctx.key||journal.status==='archived')return {journal,rows:[],needed:false};const folders=await this.tree(ctx),locations=new Map();let total=0;for(const [folderId,folder] of folders){for(const clip of list(await folder.GetClipList())){if(++total>50000)throw Error('Media Pool quá lớn để đối chiếu tự động.');const uid=await id(clip);if(locations.has(uid))throw Error('Media có ID trùng; không thể đối chiếu an toàn.');locations.set(uid,folderId);if(total%50===0)await breathe();}await breathe();}
  const rows=(journal.rows||[]).map(row=>{const location=locations.get(row.id);const state=location===row.from?'source':location===row.to?'target':location?'elsewhere':'missing';return {id:row.id,name:row.name,state,location:location||null,reason:state==='source'?'Đã về Bin gốc':state==='target'?'Còn trong Bin Auto Bin':state==='elsewhere'?'Đã chuyển sang Bin khác':'Không tìm thấy media theo ID'};});
  for(let i=0;i<rows.length;i++)journal.rows[i].restored=rows[i].state==='source';
  const allSource=rows.every(r=>r.state==='source'),allTarget=rows.every(r=>r.state==='target');journal.status=allSource?'undone':allTarget&&journal.status==='complete'?'complete':'recovery-needed';await this.same(ctx);await this.write(journal);return {journal,rows,needed:journal.status==='recovery-needed'};
 }
 async scan(request='root'){this.plan=null;this.archivePlan=null;const config=configuration(request),data=await this.inspect(config.scope,config.groups),token=crypto.randomUUID();const recovery=await this.reconcile(data.ctx);this.plan={token,...config,hash:data.hash,expires:Date.now()+300000};if(recovery.needed)this.archivePlan={token:crypto.randomUUID(),key:data.ctx.key,hash:fingerprint(recovery.journal),positions:fingerprint(recovery.rows),expires:Date.now()+300000};return {token,scope:config.scope,sourceName:data.sourceName,children:data.children.map(({object,...f})=>f),destinations:Object.fromEntries(Object.entries(data.targets).map(([kind,t])=>[kind,t.name])),rows:data.rows.map(({object,file,...r})=>r),counts:Object.fromEntries([...Object.keys(BINS),'skip'].map(k=>[k,data.rows.filter(r=>k==='skip'?!r.kind:r.kind===k).length])),undoAvailable:recovery.journal?.key===data.ctx.key&&recovery.journal.status!=='archived'&&recovery.journal.rows?.some(r=>!r.restored),recoveryNeeded:recovery.needed,recoveryRows:recovery.rows,archiveToken:this.archivePlan?.token};}
 async archive(token){const plan=this.archivePlan;this.archivePlan=null;this.plan=null;if(!plan||plan.token!==token||Date.now()>plan.expires)throw Error('Hãy quét và xem lại tình trạng trước khi kết thúc lần cũ.');const ctx=await this.context();if(ctx.key!==plan.key)throw Error('Project đã thay đổi.');const recovery=await this.reconcile(ctx);if(fingerprint(recovery.journal)!==plan.hash||fingerprint(recovery.rows)!==plan.positions)throw Error('Tình trạng đã thay đổi; hãy quét lại.');const journal=recovery.journal;const dir=path.join(path.dirname(this.file),'auto-bin-history');await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,crypto.randomUUID()+'.json'),JSON.stringify(journal,null,2),{flag:'wx'});journal.status='archived';journal.archivedAt=new Date().toISOString();await this.write(journal);return {message:'Đã lưu trữ nhật ký cũ. Không di chuyển hoặc xóa media/Bin. Hãy quét lại.'};}
 async apply(token){const plan=this.plan;this.plan=null;if(!plan||plan.token!==token||Date.now()>plan.expires)throw Error('Bản xem trước hết hạn; hãy quét lại.');const data=await this.inspect(plan.scope,plan.groups);if(data.hash!==plan.hash)throw Error('Media Pool đã thay đổi; hãy quét lại trước khi sắp xếp.');const previous=(await this.reconcile(data.ctx)).journal;if(previous?.rows?.some(r=>!r.restored)&&!['complete','archived','undone'].includes(previous.status))throw Error('Còn thao tác chưa phục hồi; hãy hoàn tác trước.');const moves=data.rows.filter(r=>r.kind);if(!moves.length)return {moved:0,message:'Không có media cần sắp xếp.'};
  const journal={version:1,key:data.ctx.key,startedAt:new Date().toISOString(),status:'running',rows:[],created:[]};await this.write(journal);let moved=0;
  try{for(const kind of Object.keys(BINS)){const group=moves.filter(r=>r.kind===kind);if(!group.length)continue;await this.same(data.ctx);await this.fresh(data.source);const targetInfo=data.targets[kind];let target=targetInfo.object||Object.values(data.targets).find(t=>t.name===targetInfo.name&&t.object)?.object;
    if(!target){const matches=list(await data.source.GetSubFolderList());for(const child of matches)if(String(await child.GetName())===targetInfo.name)throw Error('Bin đích vừa thay đổi; hãy quét lại.');target=await data.ctx.pool.AddSubFolder(data.source,targetInfo.name);if(!target)throw Error('Không tạo được '+targetInfo.name);targetInfo.object=target;journal.created.push(await id(target));await this.write(journal);}
    await this.fresh(target);const targetId=await id(target);
    for(const row of group){await this.same(data.ctx);await this.fresh(data.source);await this.fresh(target);const sourceItems=list(await data.source.GetClipList());let item=null;for(const candidate of sourceItems)if(await id(candidate)===row.id)item=candidate;if(!item)throw Error('Media đã chuyển khỏi Bin nguồn.');
     const record={id:row.id,name:row.name,from:data.sourceId,to:targetId,restored:false};journal.rows.push(record);await this.write(journal);
     const result=await data.ctx.pool.MoveClips([item],target);let inTarget=false;for(const c of list(await target.GetClipList()))if(await id(c)===row.id)inTarget=true;let stillInSource=false;for(const c of list(await data.source.GetClipList()))if(await id(c)===row.id)stillInSource=true;if(!result||!inTarget||stillInSource)throw Error('Resolve không xác nhận di chuyển '+row.name);moved++;this.progress({phase:'move',done:moved,total:moves.length});await breathe();
    }
   }journal.status='complete';await this.write(journal);return {moved,message:'Đã sắp xếp '+moved+' media vào Bin thật trong Resolve.'};
  }catch(e){journal.status='interrupted';await this.write(journal);let recovery;try{recovery=await this.restore(journal);}catch(error){recovery={remaining:journal.rows.filter(r=>!r.restored).length,error:error.message};}return {moved,failed:true,message:e.message,recovery};}
 }
 async tree(ctx){const folders=new Map(),stack=[ctx.root];while(stack.length){if(folders.size>=2000)throw Error('Media Pool quá lớn để phục hồi tự động.');const f=stack.pop(),uid=await id(f);if(folders.has(uid))throw Error('Cấu trúc Bin có ID trùng.');await this.fresh(f);folders.set(uid,f);stack.push(...list(await f.GetSubFolderList()));if(folders.size%20===0)await breathe();}return folders;}
 async restore(journal){const ctx=await this.context();if(ctx.key!==journal.key)throw Error('Hãy mở đúng project đã chạy Auto Bin.');const folders=await this.tree(ctx),conflicts=[];let restored=0;
  for(const row of [...journal.rows].reverse()){if(row.restored)continue;await this.same(ctx);const origin=folders.get(row.from),dest=folders.get(row.to);if(!origin){conflicts.push(row.name+': Bin nguồn không còn');continue;}await this.fresh(origin);if(dest)await this.fresh(dest);let already=false,item=null;for(const c of list(await origin.GetClipList()))if(await id(c)===row.id)already=true;if(dest)for(const c of list(await dest.GetClipList()))if(await id(c)===row.id)item=c;
   if(already&&!item){row.restored=true;await this.write(journal);continue;}if(!item||already){conflicts.push(row.name+': vị trí media đã thay đổi');continue;}
   try{await ctx.pool.MoveClips([item],origin);}catch{}let confirmed=false;for(const c of list(await origin.GetClipList()))if(await id(c)===row.id)confirmed=true;let stillInDest=false;for(const c of list(await dest.GetClipList()))if(await id(c)===row.id)stillInDest=true;if(confirmed&&!stillInDest){row.restored=true;restored++;await this.write(journal);}else conflicts.push(row.name+': Resolve chưa xác nhận phục hồi');await breathe();
  }const remaining=journal.rows.filter(r=>!r.restored).length;journal.status=remaining?'recovery-needed':'undone';await this.write(journal);return {restored,remaining,conflicts,message:remaining?'Còn '+remaining+' media cần kiểm tra.':'Đã hoàn tác. Bin trống được giữ lại.'};
 }
 async undo(){this.plan=null;const ctx=await this.context(),recovery=await this.reconcile(ctx),journal=recovery.journal;if(journal&&journal.key!==ctx.key)throw Error('Hãy mở đúng project đã chạy Auto Bin.');if(!journal||journal.status==='archived'||!journal.rows?.some(r=>!r.restored))return {remaining:0,restored:0,conflicts:[],message:'Media đã về Bin gốc hoặc không còn lần Auto Bin cần hoàn tác.'};return this.restore(journal);}
}
function registerAutoBin({ipcMain,exclusive,...options}){const service=new AutoBin(options);for(const [channel,method] of [['folders','folders'],['scan','scan'],['apply','apply'],['undo','undo'],['archive','archive']])ipcMain.handle('auto-bin:'+channel,(_e,arg)=>exclusive(async()=>{try{return {ok:true,...await service[method](arg)};}catch(e){return {ok:false,error:e.message};}}));}
module.exports={AutoBin,classify,configuration,registerAutoBin};
