const { contextBridge, ipcRenderer } = require('electron/renderer');

contextBridge.exposeInMainWorld('hnh', {
  autoBinFolders: scope=>ipcRenderer.invoke('auto-bin:folders',scope),
  autoBinScan: scope=>ipcRenderer.invoke('auto-bin:scan',scope),
  autoBinApply: token=>ipcRenderer.invoke('auto-bin:apply',token),
  autoBinArchive: token=>ipcRenderer.invoke('auto-bin:archive',token),
  autoBinUndo: ()=>ipcRenderer.invoke('auto-bin:undo'),
  onAutoBinProgress: callback=>{const listener=(_e,data)=>callback(data);ipcRenderer.on('auto-bin:progress',listener);return ()=>ipcRenderer.removeListener('auto-bin:progress',listener);},
  renameTag: request=>ipcRenderer.invoke('metadata:rename-tag',request),
  cancelMediaThumbnails: ()=>ipcRenderer.invoke('media:cancel-thumbnails'),
  cacheStats: ()=>ipcRenderer.invoke('maintenance:stats'),
  clearCache: kind=>ipcRenderer.invoke('maintenance:clear',kind),
  exportDiagnostics: ()=>ipcRenderer.invoke('maintenance:export'),
  getWaveform: (file) => ipcRenderer.invoke('waveform:get', file),
  putWaveform: (file, data) => ipcRenderer.invoke('waveform:put', file, data),
  saveDurations: (entries) => ipcRenderer.invoke('audio:metadata-batch', entries),
  saveDuration: (file, duration) => ipcRenderer.invoke('audio:metadata', file, duration),
  onLibraryChanged: (callback) => { const listener=(_e,data)=>callback(data); ipcRenderer.on('library:changed',listener); return ()=>ipcRenderer.removeListener('library:changed',listener); },
  onResolveChanged: (callback) => { const listener=(_e,data)=>callback(data); ipcRenderer.on('resolve:changed',listener); return ()=>ipcRenderer.removeListener('resolve:changed',listener); },
  onScanStatus: (callback) => { const listener=(_e,data)=>callback(data); ipcRenderer.on('library:scan-status',listener); return ()=>ipcRenderer.removeListener('library:scan-status',listener); },
  onBackupProgress: callback => {const listener=(_e,data)=>callback(data);ipcRenderer.on('backup:progress',listener);return ()=>ipcRenderer.removeListener('backup:progress',listener);},
  exportBackup: options=>ipcRenderer.invoke('backup:export',options),
  openBackup: ()=>ipcRenderer.invoke('backup:open'),
  relinkLibrary: root=>ipcRenderer.invoke('backup:library',root),
  openPending: ()=>ipcRenderer.invoke('backup:pending'),
  backupFolder: ()=>ipcRenderer.invoke('backup:folder'),
  prepareBackup: mappings=>ipcRenderer.invoke('backup:prepare',mappings),
  applyBackup: (token,overrides,options)=>ipcRenderer.invoke('backup:apply',token,overrides,options),
  undoBackup: ()=>ipcRenderer.invoke('backup:undo'),
  cancelBackup: ()=>ipcRenderer.invoke('backup:cancel'),
  openDeveloperContact: () => ipcRenderer.invoke('help:developer-contact'),
  mediaTracks: ()=>ipcRenderer.invoke('media:tracks'),
  mediaPreview: file=>ipcRenderer.invoke('media:preview',file),
  mediaThumbnail: file=>ipcRenderer.invoke('media:thumbnail',file),
  mediaImport: file=>ipcRenderer.invoke('media:import',file),
  mediaInsert: (file,options)=>ipcRenderer.invoke('media:insert',file,options),
  updateState: ()=>ipcRenderer.invoke('updates:state'),
  acknowledgeInstalled:()=>ipcRenderer.invoke('updates:ack-installed'),
  prepareAudioExport:request=>ipcRenderer.invoke('export:prepare',request),
  saveAudioExport:(token,data)=>ipcRenderer.invoke('export:save',token,data),
  cancelAudioExport:token=>ipcRenderer.invoke('export:cancel',token),
  checkUpdates: manual=>ipcRenderer.invoke('updates:check',manual),
  configureUpdates: patch=>ipcRenderer.invoke('updates:configure',patch),
  openUpdates: ()=>ipcRenderer.invoke('updates:open'),
  getState: () => ipcRenderer.invoke('app:get-state'),
  addLibrary: types => ipcRenderer.invoke('library:add',types),
  setLibraryTypes: (folder,types)=>ipcRenderer.invoke('library:types',folder,types),
  removeLibrary: (p) => ipcRenderer.invoke('library:remove', p),
  rescan: () => ipcRenderer.invoke('library:rescan'),
  bulkMetadata: request=>ipcRenderer.invoke('metadata:bulk',request),
  updateSettings: (patch) => ipcRenderer.invoke('settings:update', patch),
  getResolveStatus: () => ipcRenderer.invoke('resolve:status'),
  retryResolve: () => ipcRenderer.invoke('resolve:retry'),
  getAudioTracks: () => ipcRenderer.invoke('resolve:tracks'),
  importToMediaPool: (p) => ipcRenderer.invoke('resolve:import', p),
  getTimelineRange:()=>ipcRenderer.invoke('resolve:timeline-range'),
  insertTimelineRange:request=>ipcRenderer.invoke('resolve:insert-range',request),
  insertAtPlayhead: (p,trackIndex,range,options) => ipcRenderer.invoke('resolve:insert',p,trackIndex,range,options),
  prepareSfxDrag: input=>ipcRenderer.invoke('sfx:prepare-drag',input),
  startSfxDrag: token=>ipcRenderer.send('sfx:start-drag',token),
  onSfxDragError: cb=>ipcRenderer.on('sfx:drag-error',(_e,message)=>cb(message)),
  readAudioFile: (p) => ipcRenderer.invoke('audio:read', p),
  revealInExplorer: (p) => ipcRenderer.invoke('shell:reveal', p)
});
