const fs=require('node:fs/promises');
function collection(raw){if(Array.isArray(raw))return raw;if(raw&&typeof raw==='object'&&Object.keys(raw).every(k=>/^\d+$/.test(k)))return Object.keys(raw).sort((a,b)=>a-b).map(k=>raw[k]);throw Error('Không đọc được danh sách clip; không thể xác nhận track trống.');}
async function isFree(t,index,start,end){if(await t.GetIsTrackLocked('audio',index))return false;if(typeof t.GetIsTrackEnabled==='function'&&!await t.GetIsTrackEnabled('audio',index))return false;for(const clip of collection(await t.GetItemListInTrack('audio',index))){const a=Number(await clip.GetStart()),b=Number(await clip.GetEnd());if(!Number.isFinite(a)||!Number.isFinite(b)||b<a)throw Error('Không xác định được vùng clip trên A'+index);if(a<end&&b>start)return false;}return true;}
async function chooseAudioTrack({timeline:t,preferred,start,end,create=false,placement='top',guard=async()=>{}}){
 if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)throw Error('Chưa xác định được độ dài đoạn cần chèn.');for(const key of ['GetIsTrackLocked','GetItemListInTrack'])if(typeof t[key]!=='function')throw Error('Resolve thiếu '+key+' để chọn track an toàn.');const count=Number(await t.GetTrackCount('audio'));if(!Number.isInteger(count)||count<0)throw Error('Không đọc được số audio track.');
 for(const index of [...new Set([Number(preferred),...Array.from({length:count},(_,i)=>i+1)])].filter(i=>Number.isInteger(i)&&i>0&&i<=count))if(await isFree(t,index,start,end))return {trackIndex:index,created:false};
 if(!create)throw Error('Không có track đủ chỗ trống. Bật Tạo track khi cần hoặc chọn vị trí khác.');if(!['top','bottom'].includes(placement))throw Error('Vị trí tạo track không hợp lệ.');await guard();if(Number(await t.GetTrackCount('audio'))!==count)throw Error('Danh sách track vừa thay đổi; hãy thử lại.');
 let ok;try{ok=await t.AddTrack('audio',placement==='top'&&count?{audioType:'stereo',index:1}:'stereo');}catch(e){throw Error('Resolve không xác nhận tạo track. Kiểm tra timeline trước khi thử lại. '+e.message);}
 const after=Number(await t.GetTrackCount('audio')),index=placement==='top'?1:after;
 if(!ok||after!==count+1)throw Error('Resolve không xác nhận tạo đúng một track. Kiểm tra timeline trước khi thử lại.');
 if(collection(await t.GetItemListInTrack('audio',index)).length||!await isFree(t,index,start,end))throw Error('Đã thêm track nhưng Resolve không đặt track trống tại vị trí yêu cầu. Kiểm tra track mới trước khi thử lại.');
 return {trackIndex:index,created:true,warning:placement==='top'?'Đã tạo A1 mới; các audio track cũ dịch xuống một vị trí.':'Đã tạo A'+index+' mới.'};
}
function createSmartInserter({getResolve,loadIndex,importItem,resultItems,getPosition}){
 return async function insert(filePath,preferred,range,options={}){let createdWarning='';try{
  const index=await loadIndex(),file=index.files.find(f=>f.path===filePath);if(!file||!['wav','mp3','flac','aiff','aif','m4a','aac','ogg'].includes(file.extension))throw Error('SFX không còn trong thư viện.');const stat=await fs.stat(file.path);if(!stat.isFile()||stat.size!==file.size||stat.mtimeMs!==file.mtimeMs)throw Error('File thay đổi; hãy quét lại thư viện.');if(range)require('./trim').validateRange(range);
  const resolve=await getResolve();if(!resolve)throw Error('Chưa kết nối Resolve.');const pm=await resolve.GetProjectManager(),project=await pm.GetCurrentProject(),timeline=project&&await project.GetCurrentTimeline();if(!timeline)throw Error('Mở project và timeline trước khi chèn.');const projectId=await project.GetUniqueId(),timelineId=await timeline.GetUniqueId(),pos=await getPosition(timeline);
  const guard=async()=>{const p=await pm.GetCurrentProject(),t=p&&await p.GetCurrentTimeline();if(!p||!t||await p.GetUniqueId()!==projectId||await t.GetUniqueId()!==timelineId)throw Error('Project hoặc timeline vừa thay đổi.');const latest=await getPosition(t);if(latest.recordFrame!==pos.recordFrame||latest.fps!==pos.fps)throw Error('Playhead/FPS vừa thay đổi; hãy chèn lại tại vị trí mới.');};
  if(typeof timeline.DeleteClips!=='function')throw Error('Resolve thiếu API kiểm tra/thu hồi clip vừa chèn.');const imported=await importItem(resolve,project,file.path);if(!imported.ok)return imported;await require('./av-insert').audioSource(imported.item);
  let sourceFps=Number(await imported.item.GetClipProperty('FPS')),frames=Number(await imported.item.GetClipProperty('Frames'));if(!Number.isFinite(sourceFps)||sourceFps<=0)sourceFps=pos.fps;const duration=Number.isFinite(frames)&&frames>0?frames/sourceFps:Number(file.duration);if(!Number.isFinite(duration)||duration<=0)throw Error('Chưa đọc được thời lượng nguồn. Nghe Preview để cập nhật rồi thử lại.');
  if(range&&range.outSeconds>duration+.001)throw Error('Đoạn chọn vượt thời lượng nguồn.');const seconds=range?range.outSeconds-range.inSeconds:duration,expected=seconds*pos.fps,end=pos.recordFrame+Math.ceil(expected)+2;if(!Number.isFinite(expected)||expected<=0)throw Error('Độ dài chèn không hợp lệ.');const trim=range?require('./trim').trimFrames(range,sourceFps,frames):{};
  await guard();const chosen=await chooseAudioTrack({timeline,preferred,start:pos.recordFrame,end,create:options.create===true,placement:options.placement||'top',guard});createdWarning=chosen.warning||'';await guard();if(!await isFree(timeline,chosen.trackIndex,pos.recordFrame,end))throw Error('Track vừa có clip khác hoặc đã bị khóa.');const pool=await project.GetMediaPool();let clips;
  try{clips=resultItems(await pool.AppendToTimeline([{mediaPoolItem:imported.item,mediaType:2,trackIndex:chosen.trackIndex,recordFrame:pos.recordFrame,...trim}]));}catch(e){throw Error('Resolve báo lỗi khi chèn; kiểm tra timeline trước khi thử lại. '+e.message);}
  try{if(clips.length!==1)throw Error('Resolve không trả đúng một clip audio.');const clip=clips[0],where=resultItems(await clip.GetTrackTypeAndIndex()),a=Number(await clip.GetStart()),length=Number(await clip.GetDuration());if(where[0]!=='audio'||Number(where[1])!==chosen.trackIndex||!Number.isFinite(a)||Math.abs(a-pos.recordFrame)>.01||!Number.isFinite(length)||Math.abs(length-expected)>2)throw Error('Vị trí hoặc độ dài clip không khớp.');}
  catch(e){let removed=false;if(clips.length)try{removed=!!await timeline.DeleteClips(clips,false);}catch{}throw Error(e.message+(removed?' Đã gỡ clip vừa chèn.':' Kiểm tra timeline trước khi thử lại.'));}
  return {ok:true,trackIndex:chosen.trackIndex,created:chosen.created,warning:createdWarning,reused:imported.reused,...pos};
 }catch(e){return {ok:false,error:e.message,warning:createdWarning};}};
}
module.exports={chooseAudioTrack,isFree,collection,createSmartInserter};
