const fs=require('node:fs/promises'),path=require('node:path'),https=require('node:https'),crypto=require('node:crypto');
const history=require('./changelog');
// Repo dùng chung với MRM: một release có thể chỉ có MRM -> phiên bản plugin lấy từ TÊN FILE zip, không từ tag
const REPO='dmina97-cpu/mrm-media-resource-manager',API='https://api.github.com/repos/'+REPO+'/releases?per_page=30',PAGE='https://github.com/'+REPO+'/releases';
const ASSET=/^HNH_SFX_Finder(?:_MRM)?_v((?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*))\.zip$/;
function pluginAsset(data){return (data?.assets||[]).map(a=>({a,m:ASSET.exec(String(a?.name||''))})).filter(x=>x.m).sort((x,y)=>newer(x.m[1],y.m[1])?-1:1)[0]||null;}
function version(s){const m=/^v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/.exec(String(s));return m?m.slice(1).map(Number):null;}
function newer(a,b){const x=version(a),y=version(b);if(!x||!y)return false;for(let i=0;i<3;i++){if(x[i]!==y[i])return x[i]>y[i];}return false;}
function release(data){if(Array.isArray(data))data=pickRelease(data);if(!data||data.draft||data.prerelease||!version(data.tag_name))throw Error('Chưa có bản phát hành chính thức hợp lệ.');const hit=pluginAsset(data);const v=hit?hit.m[1]:version(data.tag_name).join('.'),name=hit?hit.a.name:'HNH_SFX_Finder_MRM_v'+v+'.zip';return {version:v,tag:data.tag_name,notes:String(data.body||'').slice(0,6000),ready:!!hit&&hit.a.state==='uploaded'&&hit.a.size>0,assetName:name};}
/** Trong danh sách release: bản chính thức có gói plugin mới nhất (bỏ release chỉ có MRM). */
function pickRelease(list){const ok=list.filter(r=>r&&!r.draft&&!r.prerelease&&version(r.tag_name));const withPlugin=ok.filter(r=>pluginAsset(r)).sort((x,y)=>newer(pluginAsset(x).m[1],pluginAsset(y).m[1])?-1:1);return withPlugin[0]||ok[0]||null;}
function request(url=API){return new Promise((resolve,reject)=>{const req=https.get(url,{headers:{'User-Agent':'HNH-SFX-Finder-Updater','Accept':'application/vnd.github+json'}},res=>{let size=0;const chunks=[];res.on('error',reject);res.on('data',chunk=>{size+=chunk.length;if(size>1024*1024){req.destroy(Error('Thông tin cập nhật vượt giới hạn.'));return;}chunks.push(chunk);});res.on('end',()=>{if(res.statusCode!==200){reject(Error([403,429].includes(res.statusCode)?'GitHub đang giới hạn lượt kiểm tra. Hãy thử lại sau.':res.statusCode===404?'Chưa có bản phát hành công khai.':'Không đọc được bản cập nhật (HTTP '+res.statusCode+').'));return;}try{resolve(JSON.parse(Buffer.concat(chunks)));}catch{reject(Error('Thông tin cập nhật không hợp lệ.'));}});});const deadline=setTimeout(()=>req.destroy(Error('Kiểm tra cập nhật quá thời gian chờ.')),12000);req.on('close',()=>clearTimeout(deadline));req.on('error',reject);});}
async function requestHistory(from,to){const entries=[];for(let page=1;page<=5;page++){const data=await request('https://api.github.com/repos/'+REPO+'/releases?per_page=100&page='+page);if(!Array.isArray(data))throw Error('Danh sách release không hợp lệ.');for(const raw of data){if(!pluginAsset(raw))continue;try{entries.push(release(raw));}catch{}}if(data.length<100)return {entries,partial:false};}return {entries,partial:true};}
class Updater{
 constructor(dir,current,fetch=request,now=Date.now,fetchHistory=fetch===request?requestHistory:null){this.file=path.join(dir,'update-state.json');this.current=current;this.fetch=fetch;this.now=now;this.fetchHistory=fetchHistory;this.queue=Promise.resolve();}
 run(fn){const next=this.queue.then(fn);this.queue=next.catch(()=>{});return next;}
 async load(){try{return {...{auto:true},...JSON.parse(await fs.readFile(this.file,'utf8'))};}catch(e){if(e.code==='ENOENT'||e instanceof SyntaxError)return {auto:true};throw e;}}
 async save(s){await fs.mkdir(path.dirname(this.file),{recursive:true});const tmp=this.file+'.'+crypto.randomUUID()+'.tmp';try{await fs.writeFile(tmp,JSON.stringify(s));await fs.rename(tmp,this.file);}finally{await fs.unlink(tmp).catch(()=>{});}}
 view(s){const installed=s.installedChange?.to===this.current?{...s.installedChange,entries:history.between(s.installedChange.from,this.current)}:null;const r=s.release&&version(s.release.version)?s.release:null;return {current:this.current,installed,localHistory:history.between(null,this.current),historyEntries:r?history.between(this.current,r.version,[...(s.historyEntries||[]),r]):[],historyNotice:s.historyNotice||'',auto:s.auto!==false,lastAttempt:s.lastAttempt||null,release:r,error:s.error||'',available:!!r?.ready&&newer(r.version,this.current),deferred:!!r&&s.deferredVersion===r.version&&s.snoozeUntil>this.now(),ignored:!!r&&s.ignoredVersion===r.version};}
 async trackInstall(s){if(s.lastSeenVersion===this.current)return s;let from=history.valid(s.lastSeenVersion)?s.lastSeenVersion:null;if(!from){try{const receipt=JSON.parse((await fs.readFile(path.join(__dirname,'install-receipt.json'),'utf8')).replace(/^\uFEFF/,''));if(receipt.to===this.current&&history.valid(receipt.from))from=receipt.from;}catch{}}s.lastSeenVersion=this.current;if(!from||newer(this.current,from)){s.installedChange={from,to:this.current,unknown:!from,pending:true};}else s.installedChange=null;await this.save(s);return s;}
 state(){return this.run(async()=>this.view(await this.trackInstall(await this.load())));}
 acknowledge(){return this.run(async()=>{const s=await this.trackInstall(await this.load());if(s.installedChange)s.installedChange.pending=false;await this.save(s);return this.view(s);});}
 configure(patch){return this.run(async()=>{const s=await this.load();if(typeof patch?.auto==='boolean')s.auto=patch.auto;if(patch?.ignore&&patch.ignore===s.release?.version)s.ignoredVersion=patch.ignore;if(patch?.defer&&patch.defer===s.release?.version){s.deferredVersion=patch.defer;s.snoozeUntil=this.now()+86400000;}await this.save(s);return this.view(s);});}
 check(manual=false){return this.run(async()=>{const s=await this.trackInstall(await this.load()),now=this.now(),age=now-(s.lastAttempt||0);if(!manual&&s.auto===false)return this.view(s);if(s.lastAttempt&&age>=0&&age<(manual?60000:86400000))return {...this.view(s),cached:true};s.lastAttempt=now;await this.save(s);try{s.release=release(await this.fetch());s.error='';s.historyEntries=[];s.historyNotice='';if(newer(s.release.version,this.current)&&this.fetchHistory){try{const h=await this.fetchHistory(this.current,s.release.version);s.historyEntries=h.entries;s.historyNotice=h.partial?'Lịch sử GitHub vượt giới hạn truy vấn; phần dưới có thể chưa đầy đủ.':'';}catch(e){s.historyNotice='Chưa tải đủ lịch sử GitHub; đang dùng ghi chú đi kèm và bản mới nhất. '+e.message;}}else if(newer(s.release.version,this.current))s.historyNotice='Lịch sử tổng hợp từ ghi chú đi kèm plugin và release mới nhất.';}catch(e){s.error=e.message||'Không kiểm tra được cập nhật.';}await this.save(s);return this.view(s);});}
}
function registerUpdater({ipcMain,dir,current,shell}){const updater=new Updater(dir,current);ipcMain.handle('updates:state',()=>updater.state());ipcMain.handle('updates:ack-installed',()=>updater.acknowledge());ipcMain.handle('updates:check',(_e,manual)=>updater.check(manual===true));ipcMain.handle('updates:configure',(_e,patch)=>updater.configure(patch));ipcMain.handle('updates:open',async()=>{const info=await updater.state(),r=info.release;const url=info.available&&version(r?.tag)?'https://github.com/'+REPO+'/releases/tag/'+encodeURIComponent(r.tag):PAGE;await shell.openExternal(url);return true;});return updater;}
module.exports={Updater,version,newer,release,pickRelease,registerUpdater};
