const fs=require('node:fs/promises'),path=require('node:path'),{pathToFileURL}=require('node:url');
const library=require('./library');
function numeric(value){const n=Number(String(value??'').replace(/,/g,'').trim());return Number.isFinite(n)&&n>0?n:null;}
function clipRange(kind,options,sourceFps,frames,timelineFps){
 if(kind==='image'){const seconds=Number(options.seconds);if(!Number.isFinite(seconds)||seconds<=0||seconds>3600)throw Error('Thời lượng ảnh cần lớn hơn 0 và tối đa 3600 giây.');return {startFrame:0,endFrame:Math.max(1,Math.round(seconds*timelineFps))-1};}
 if(options.range){if(!sourceFps)throw Error('Resolve chưa trả FPS nguồn; hãy Import trước hoặc chèn toàn bộ video.');return require('./trim').trimFrames(options.range,sourceFps,frames);}
 if(!frames)throw Error('Không đọc được số frame của video từ Resolve. Hãy thử Import trước.');return {startFrame:0,endFrame:Math.floor(frames)-1};
}
function registerVisualMedia({ipcMain,nativeImage,thumbnailDecoder,dir,loadIndex,getResolve,importItem,resultItems,getPosition,exclusive}){
 const cache=path.join(dir,'thumbnails-v1');let thumbnailEpoch=0,thumbnailQueue=Promise.resolve(),writes=0,indexStamp=null,indexFiles=null;
 async function fileInfo(input){
  const stamp=await fs.stat(path.join(dir,'sfx-index.json')).then(s=>s.size+'|'+s.mtimeMs).catch(()=>null);
  if(!stamp||stamp!==indexStamp||!indexFiles){const index=await loadIndex();indexFiles=new Map(index.files.map(f=>[f.path,f]));indexStamp=stamp;}
  const file=indexFiles.get(input?.path);if(file&&(file.size!==input.size||file.mtimeMs!==input.mtimeMs))throw Error('Lựa chọn đã cũ; hãy chọn lại file sau khi quét.');if(!file||!['image','video'].includes(library.kind(file.extension)))throw Error('File không còn trong thư viện ảnh/video.');const stat=await fs.stat(file.path);if(!stat.isFile()||stat.size!==file.size||stat.mtimeMs!==file.mtimeMs)throw Error('File đã thay đổi; hãy quét lại thư viện.');return file;
 }
 async function context(){const resolve=await getResolve();if(!resolve)throw Error('Chưa kết nối Resolve.');const pm=await resolve.GetProjectManager(),project=pm&&await pm.GetCurrentProject();if(!project)throw Error('Hãy mở project trong Resolve.');const timeline=await project.GetCurrentTimeline();if(!timeline)throw Error('Hãy mở timeline trong Resolve.');return {resolve,project,timeline};}
 async function tracks(type='video'){const {timeline}=await context(),count=Number(await timeline.GetTrackCount(type))||0,result=[];for(let i=1;i<=count;i++){let name='',locked=false;try{name=String(await timeline.GetTrackName(type,i)||'');locked=!!(await timeline.GetIsTrackLocked(type,i));}catch{}result.push({index:i,name,locked});}return result;}
 ipcMain.handle('media:tracks',async()=>{try{return {ok:true,tracks:await tracks(),audioTracks:await tracks('audio')};}catch(e){return {ok:false,error:e.message,tracks:[]};}});
 ipcMain.handle('media:preview',async(_e,input)=>{const file=await fileInfo(input);return pathToFileURL(file.path).href;});
 ipcMain.handle('media:cancel-thumbnails',()=>{thumbnailEpoch++;thumbnailDecoder?.cancel();return true;});
 ipcMain.handle('media:thumbnail',(_e,input)=>{const epoch=thumbnailEpoch;const next=thumbnailQueue.then(async()=>{if(epoch!==thumbnailEpoch)return null;const file=await fileInfo(input),key=library.fingerprint(file),dest=path.join(cache,key+'.png');try{return 'data:image/png;base64,'+(await fs.readFile(dest)).toString('base64');}catch{}if(epoch!==thumbnailEpoch)return null;if(!thumbnailDecoder&&typeof nativeImage?.createThumbnailFromPath!=='function')return null;
  try{let bytes;if(thumbnailDecoder){bytes=await thumbnailDecoder.create(file.path,library.kind(file.extension));}else{const image=await nativeImage.createThumbnailFromPath(file.path,{width:320,height:180});if(image.isEmpty())return null;bytes=image.toPNG();}if(epoch!==thumbnailEpoch||!bytes)return null;if(bytes.length>2*1024*1024)return null;await fileInfo(input);if(epoch!==thumbnailEpoch)return null;await fs.mkdir(cache,{recursive:true});await fs.writeFile(dest,bytes);if(++writes%32===0){const names=await fs.readdir(cache);if(names.length>1000){const entries=await Promise.all(names.map(async name=>({name,time:(await fs.stat(path.join(cache,name))).mtimeMs})));entries.sort((a,b)=>a.time-b.time);for(const e of entries.slice(0,entries.length-1000))await fs.unlink(path.join(cache,e.name));}}return 'data:image/png;base64,'+bytes.toString('base64');}catch{return null;}});thumbnailQueue=next.catch(()=>{});return next;});
 ipcMain.handle('media:import',(_e,input)=>exclusive(async()=>{try{const file=await fileInfo(input),resolve=await getResolve();if(!resolve)throw Error('Chưa kết nối Resolve.');const pm=await resolve.GetProjectManager(),project=pm&&await pm.GetCurrentProject();if(!project)throw Error('Hãy mở project trong Resolve.');const imported=await importItem(resolve,project,file.path);return {ok:imported.ok,error:imported.error,detail:imported.detail,reused:imported.reused};}catch(e){return {ok:false,error:e.message};}}));
 ipcMain.handle('media:insert',(_e,input,options={})=>exclusive(async()=>{
  try{const file=await fileInfo(input),kind=library.kind(file.extension);if(kind==='image')clipRange(kind,options,null,null,24);else if(options.range)require('./trim').validateRange(options.range);
   const {resolve,project,timeline}=await context(),trackIndex=Number(options.trackIndex),count=Number(await timeline.GetTrackCount('video')),auto=kind==='video'&&options.includeAudio===true&&options.autoTracks===true;
   if(!auto&&(!Number.isInteger(trackIndex)||trackIndex<1||trackIndex>count))throw Error('Track video không còn tồn tại. Hãy tải lại danh sách track.');
   if(!auto&&typeof timeline.GetIsTrackLocked==='function'&&await timeline.GetIsTrackLocked('video',trackIndex))throw Error('Track video đang khóa. Hãy mở khóa hoặc chọn track khác.');
   const imported=await importItem(resolve,project,file.path);if(!imported.ok)return {ok:false,error:imported.error,detail:imported.detail};
   let fps=null,frames=null,type='';try{fps=numeric(await imported.item.GetClipProperty('FPS'));frames=numeric(await imported.item.GetClipProperty('Frames'));type=String(await imported.item.GetClipProperty('Type')||'');}catch{}
   if(kind==='image'&&(/sequence/i.test(type)||/^video$/i.test(type)))throw Error('Resolve đang nhận ảnh này thành image sequence. Bật Show Individual Frames trong Media Storage rồi import ảnh riêng.');
   const pos=await getPosition(timeline),range=clipRange(kind,options,fps,frames,pos.fps),pool=await project.GetMediaPool();
   if(kind==='video'&&options.includeAudio===true){await require('./av-insert').audioSource(imported.item);let chosen={videoTrack:trackIndex,audioTrack:Number(options.audioTrackIndex),created:[]};if(auto)chosen=await require('./free-tracks').chooseTracks({timeline,videoTrack:trackIndex,audioTrack:Number(options.audioTrackIndex),start:pos.recordFrame,end:pos.recordFrame+Math.ceil((range.endFrame-range.startFrame+1)/fps*pos.fps)+2,resultItems,create:options.createTracks===true});let linked;try{linked=await require('./av-insert').appendAV({timeline,pool,item:imported.item,range,pos,sourceFps:fps,videoTrack:chosen.videoTrack,audioTrack:chosen.audioTrack,resultItems});}catch(e){throw Error(e.message+(chosen.created.length?" Track mới đã tạo: "+chosen.created.join(", ")+".":""));}return {ok:true,trackIndex:chosen.videoTrack,timecode:pos.timecode,reused:imported.reused,...linked,warning:[chosen.created.length?"Đã tạo "+chosen.created.join(", "):"",linked.roundingWarning||""].filter(Boolean).join(" • ")};}
   const result=await pool.AppendToTimeline([{mediaPoolItem:imported.item,mediaType:1,trackIndex,recordFrame:pos.recordFrame,...range}]),items=resultItems(result);
   if(!items.length)throw Error('Resolve không chèn được file này. Kiểm tra định dạng và track đích.');
   let warning='';if(kind==='image'){try{const duration=Number(await items[0].GetDuration());if(Number.isFinite(duration)&&Math.abs(duration-(range.endFrame+1))>1)warning='Resolve áp dụng thời lượng ảnh khác yêu cầu; kiểm tra và chỉnh độ dài clip trên timeline.';}catch{warning='Đã chèn; kiểm tra thời lượng ảnh trên timeline.';}}
   return {ok:true,trackIndex,timecode:pos.timecode,reused:imported.reused,warning};
  }catch(e){return {ok:false,error:e.message};}
 }));
}
module.exports={registerVisualMedia,clipRange,numeric};
